### ISSUE TITLE
Mods for Minecraft 1.17.x require additional changes for compatibility

### ISSUE THREAD

**Issue by smmmadden** [CreativeMD/AmbientSounds#101]
**FYI:** Mostly a reminder than issue since these files are often forgotten to be updated.  There are files to change for 1.17.1 to work.
**mods.toml**, ***mixins*** and **pack.mcmeta** need updating for every major release of Minecraft depending on what is included.
Minecraft 1.17.x - Minimum Java Level Supported: 16.0.1
pack.mcmeta files Pack Format=7 for 1.17.x release, 6 for 1.16 and 5 for 1.15, etc.
Minecraft Vanilla Launcher (new one from Microsoft Store) has loading issues that require additional changes to our mods and modpacks.  Read conversation towards the bottome on CurseForge Support: https://forums.minecraftforge.net/topic/105079-forge-1171-not-launching/?_fromLogin=1
This describes how to workaround the breaking change Microsoft made with the new Vanilla Minecraft launcher

**Comment by CreativeMD** [comment]
Don't think this has anything to do with my mods.
