### ISSUE TITLE
Any chance for Fabric support?

### ISSUE THREAD

**Issue by PureTryOut** [CreativeMD/AmbientSounds#102]
The current state of modding in Minecraft is annoying. There are mods that require Forge, and there are mods that require Fabric. Some do both which is awesome, but sadly most don't. AmbientSounds is one of those mods that works only with Forge and sadly it means I have to miss out on it as I have several other mods that require Fabric instead. Are there any plans on making a Fabric version of AmbientSounds as well?

**Comment by CreativeMD** [comment]
Nope I will stick to Forge.

**Comment by PureTryOut** [comment]
Sorry for asking further, but any particular reason why? It's too bad but I'm fine with the fact if you really don't want to support it, but giving a good explanation on why now might prevent further questions from others in the future. And at least you'll have a place to point people too then.

**Comment by CreativeMD** [comment]
I have to support multiple versions of minecraft. I have more than 10 mods. I don't want to spend extra time for fabric. It would require a lot of effort and I don't really see the benefit. I'm very sad about the situation, it feels like we as a modding community have made a few steps back in time. Forge might not be perfect, but would be cool if Fabric could run alongside it.
