### ISSUE TITLE
[1.16.5] Crash with AS 3.1.11 when joining server

### ISSUE THREAD

**Issue by Brycey92** [CreativeMD/AmbientSounds#103]
[crash-2021-11-21_17.52.45-fml.txt](https://github.com/CreativeMD/AmbientSounds/files/7598374/crash-2021-11-21_17.52.45-fml.txt)

**Comment by CreativeMD** [comment]
I don't think this issue is related to my mod.

**Comment by Brycey92** [comment]
Whoops, that is 100% not the crash report the game gave me! Here's the correct one, and I'm thinking I should restart my computer since there were double the crash reports this time I checked and I haven't crashed since this one :sweat_smile: 
[crash-2021-11-24_14.41.18-client.txt](https://github.com/CreativeMD/AmbientSounds/files/7598568/crash-2021-11-24_14.41.18-client.txt)

**Comment by CreativeMD** [comment]
This is a client side mod which cannot be installed on server side.

**Comment by Brycey92** [comment]
Ahhh that makes sense, thanks!

**Comment by Brycey92** [comment]
Ahh that makes sense, thanks!
