### ISSUE TITLE
1.12.2 Crashes

### ISSUE THREAD

**Issue by mxnmnm** [CreativeMD/AmbientSounds#104]
RandomTweaks allows me to reload the sound system, but it seems to occasionally crash and this mod is blamed for it. 
https://gist.github.com/mxnmnm/d54593bddcaeb4205bd85654efa17d82

**Comment by CreativeMD** [comment]
Why would you need that? The issue of the sound system not working at times has been fixed.

**Comment by mxnmnm** [comment]
Hmmmm, I guess it is another mod causing the sound issues, either way I don't think things should crash because crashing bad :(

**Comment by CreativeMD** [comment]
I don't think I can fix it :|

**Comment by mxnmnm** [comment]
F
