### ISSUE TITLE
[1.18.1] AmbientSounds / CreativeCore Config Crash

### ISSUE THREAD

**Issue by Boomflex** [CreativeMD/AmbientSounds#107]
Hello there Creative, hope you're good? :)

AS: AmbientSounds_v5.0.0-pre02_mc1.18.1.jar
CC: CreativeCore_v2.4.0_mc1.18.1.jar

Noticed a crash if using the Mods config: https://streamable.com/l6xkgs

https://pastebin.com/rqSGWk4E

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore. Thanks a lot for reporting this issue!
