### ISSUE TITLE
1.18 High mountain windsounds played in normal terrain

### ISSUE THREAD

**Issue by deadpho3nix** [CreativeMD/AmbientSounds#108]
hi, first of all i really want to thank you for your hard work on the mod. I have been using the mod for a very long time as it really adds a lot to the game.

I have noticed that the sound file of mountain air now also plays on normal terrain. Probably a bug because of the changes to the height of the game world.

Sometimes it can be fixed by pausing and unpausing the game.

Maybe this info can help you find the bug. I am very happy with the new update and look forward to a few hours of fun with your mod :)

**Comment by CreativeMD** [comment]
Can you use the command /ambient-debug and send me a screenshot of when it is happening?

**Comment by deadpho3nix** [comment]
![screenshot1](https://user-images.githubusercontent.com/55642361/146414287-3391bbfd-c0ab-4f46-a8e8-29622d6f736e.png)
![screenshot2](https://user-images.githubusercontent.com/55642361/146414292-90405162-8acf-4f9e-9906-9c97f3291d62.png)

sure :)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting the issue and helping out!
