### ISSUE TITLE
[1.18.1] Crash while /ambience-debug in multiplayer (repeating crash)

### ISSUE THREAD

**Issue by Eleroyy** [CreativeMD/AmbientSounds#110]
Game crashed while I wanted to do the /ambient-debug command in multiplayer. The crash always occure in multiplayer but not in singleplayer. The server is vanilla, nothing special. 

First crash:
[crash-2021-12-17_21.22.01-client.txt](https://github.com/CreativeMD/AmbientSounds/files/7737580/crash-2021-12-17_21.22.01-client.txt)

Second crash:
[crash-2021-12-17_21.31.54-client.txt](https://github.com/CreativeMD/AmbientSounds/files/7737611/crash-2021-12-17_21.31.54-client.txt)

Third crash:
[crash-2021-12-17_21.35.41-client.txt](https://github.com/CreativeMD/AmbientSounds/files/7737635/crash-2021-12-17_21.35.41-client.txt)

ps: thanks fot the nice mod :)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for reporting this issue!
