### ISSUE TITLE
[1.18.1] No sound played in "minecraft:forest" in multiplayer

### ISSUE THREAD

**Issue by deadpho3nix** [CreativeMD/AmbientSounds#111]
Hey Creative

I noticed another bug. I don't know if it's the same in singleplayer but in multiplayer no sound is played in minecraft:forest biom. I have directly attached the screenshots.

greetings

**Comment by deadpho3nix** [comment]
![screenshot1](https://user-images.githubusercontent.com/55642361/146684918-fc62a1ae-feec-47a2-b16d-993fc7629a29.png)
![screenshot2](https://user-images.githubusercontent.com/55642361/146684919-b78d181f-f229-4b61-9f62-5294c765d2fb.png)

**Comment by CreativeMD** [comment]
Should be better in the newest version. Thanks for reporting this issue!
