### ISSUE TITLE
[Bug 1.18.1] Forest sounds underground

### ISSUE THREAD

**Issue by Matthysse** [CreativeMD/AmbientSounds#112]
Hello!
On 1.18.1, I heard a constant forest sound underground, which is not supposed to happen. 
![2021-12-22_15 21 20](https://user-images.githubusercontent.com/32510957/147108044-33694b12-bd0c-40b5-bed1-e5ee9d805b46.png)
If these bird sounds come from the fact that I'm in a lush cave, it's weird too, lush caves aren't supposed to have birds.

**Comment by CreativeMD** [comment]
There are no birds playing. At least not from AmbientSounds. Only some crickets and a frog from time to time. I'm still not sure what the lush cave should sound like, but that's my current attempt. If you have better ideas let me know.
