### ISSUE TITLE
[1.18.1] Ressource packs not loaded

### ISSUE THREAD

**Issue by Matthysse** [CreativeMD/AmbientSounds#113]
Hello!
I made a ressourcepack that worked for 1.16.5 and added sounds to the game thanks to your mod, I could load it on 1.12.2 as well without any modification, but on 1.18.1 it just deoesn't work.

**Comment by CreativeMD** [comment]
The engine system has been reworked completely. You will have to redo your resourcepack. Just take a look in the assets folder of the mod.
