### ISSUE TITLE
[1.12.2] Birds continue to sing at full intensity during rain/thunderstorm

### ISSUE THREAD

**Issue by LenKagamine** [CreativeMD/AmbientSounds#114]
I do know they still technically sing during thunderstorms, but in the mod the loop still plays at full volume, even though realistically most would be hiding from the bad weather, and those that do still stay out would be muffled by the rain.

**Comment by CreativeMD** [comment]
AmbientSounds plays all other sounds quieter while having rain/ thunder. It's always helpful to provide a screenshot with /ambient-debug turned on, so I can see what is going wrong here. But unfortunately I have dropped support for 1.12, so I won't fix it for that version.

**Comment by LenKagamine** [comment]
Ah ok. Thanks anyways.
