### ISSUE TITLE
1.18.1 Sounds seem to play in wrong places

### ISSUE THREAD

**Issue by Shadow212121** [CreativeMD/AmbientSounds#117]
wind sound effects seem to play in almost every biome, not sure if this is intentional or not. Sounds from the surface also seem to continue playing while you go deep into caves for some reason. Breaks immersion a bit when im hearing birds chirping in a deepslate cave. The wind seems to be almost constant everywhere on the surface as well.

**Comment by TheRealDadbeard** [comment]
Seems to happen for me to when I am close to a big mountain

**Comment by CreativeMD** [comment]
Please update, lots of issues have already been fixed. If the issue still persists, use the command /ambient-debug and make a screenshot when things don't work as expected. Through that way I can see what situation you are in and why the wind sound is playing (so I can fix it).

**Comment by CreativeMD** [comment]
I will close this issue for now. Just reply here if there is still an issue.
