### ISSUE TITLE
[1.16] crash happening in some biomes

### ISSUE THREAD

**Issue by jinkhya** [CreativeMD/AmbientSounds#118]
Hello, I'm having some crashes when entering some biomes. In this case, a mesa biome (from OTG with far from home7 preset)
Here's the crash-log : https://gist.github.com/jinkhya/618e53747c7ca47bb5113d31f5611046 
Thanks in advance !
Jin

**Comment by CreativeMD** [comment]
AmbientSounds is a client side only mod, it cannot be installed on server side.

**Comment by jinkhya** [comment]
But it isn't installed on the server, it's only in my client. That crash-log is my client, while playing on a server.

**Comment by CreativeMD** [comment]
Oh right, I see it now. But I'm very confused as to way this crash happens. Maybe the jar is corrupted? Maybe try to just install CreativeCore and AmbientSounds to check if they run fine on their own.

**Comment by CreativeMD** [comment]
Will close this issue for now. If there are any news post them here.
