### ISSUE TITLE
Sound inside buildings seem very loud even if they are pretty closed up

### ISSUE THREAD

**Issue by TheRealDadbeard** [CreativeMD/AmbientSounds#120]
I have a couple of locations that I have been in on my server that seem way too loud for how closed of they are. I did a couple of screenshots on those. Like the wind was blowing and ambience was the same loudness as if you were standing outside.

Minecraft 1.18.1
Forge 39.0.10
Ambient Sounds 5.0.0

Using ATM7 modpack
![2022-01-07_22 00 34](https://user-images.githubusercontent.com/23340600/148660394-0e86d8e0-50cc-4eb5-84f1-6aa47f2b3c1a.png)
![2022-01-07_22 28 15](https://user-images.githubusercontent.com/23340600/148660395-cddcd100-0695-416d-b14d-158934ad57a8.png)
![2022-01-07_22 49 44](https://user-images.githubusercontent.com/23340600/148660397-25389ad1-a802-4488-a9e0-9c2b29c956c7.png)

**Comment by CreativeMD** [comment]
Thanks a lot for your screenshots. Helped a lot. I hope the new version solves all your issues (will be available in a few minutes).
