### ISSUE TITLE
Amb Sounds for MC 1.17.1 (4.0.4) version is corrupt.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [CreativeMD/AmbientSounds#121]
When I open the java file it says it is corrupt, so cant be installed. If the mod is supposed to be setup in some special way, might be an actual idea to put installation instructions in the place where it is downloaded from!

**Comment by CreativeMD** [comment]
You install it like any other Forge mod, search for a tutorial about how to install Forge + Mods.
