### ISSUE TITLE
No Ambient Sounds

### ISSUE THREAD

**Issue by LuciusofLegend** [CreativeMD/AmbientSounds#122]
Hi there, I installed this mod and didn't notice any new sounds.  I have my 'Ambient/Environment' sound setting at 100% as well as my master volume.  I was hearing the Minecraft soundtrack as well.  (This is all just to say that it wasn't my sound settings).  I noticed that the mod is not listed in ModMenu, is it maybe incompatible with ModMenu?  It may also be some other mod incompatibility since I have 85 client side mods.  I can list all the mods for you if that is helpful.  Thanks in advance!

**Comment by LuciusofLegend** [comment]
My sound settings:
![Sound Settings](https://user-images.githubusercontent.com/83921153/151053171-46c7c7e7-0793-4f25-8d96-2d03a227a813.png)

**Comment by CreativeMD** [comment]
Use the command /ambient-debug, there you can see if something is playing or not.

**Comment by LuciusofLegend** [comment]
I could not use the command.  At first I thought it was just because I was on a server.  Then I tried on singleplayer.  Then I tried on singleplayer with cheats.  Unknown command.

**Comment by CreativeMD** [comment]
That means AmbientSounds is not even installed.

**Comment by LuciusofLegend** [comment]
I must have done something wrong.  I got Dynamic Surroundings instead.  I'm surprised you can get it on 1.18.1.

**Comment by LuciusofLegend** [comment]
Thanks for your help and sorry for the inconvenience.
