### ISSUE TITLE
Any plan for fabric? (NOT AN ISSUE)

### ISSUE THREAD

**Issue by StockiesLad** [CreativeMD/AmbientSounds#124]
I REALLLY like this mod and think it's amazing for dynamic surroundings. I actually compiled the source code from dynamic surroundings for 1.18.1 fabric. Are there any plans for a fabric port so I can put these two masterpieces together?

Disclaimer: I understand how difficult it is to program and code, I say this with the most respect and refrain from making it appear like a demand. It's merely a suggestion.

**Comment by CreativeMD** [comment]
Nope it's not planned. Unfortunately it would also require to port CreativeCore which is a lot more difficult. I think it's already difficult enough to support the different minecraft versions. I hope some day forge and fabric can run alongside each other.
