### ISSUE TITLE
Mod crashes with Optfine or Magnesium, and probably without them too when reloading resource packs.

### ISSUE THREAD

**Issue by Huetete** [CreativeMD/AmbientSounds#126]
Mod Version:

AmbientSounds_v3.1.11_mc1.16.5

Forge Version:

Release 1.16.5-forge-36.2.22

Link to client log:

https://rentry.co/265bs

Link to crash log:

https://rentry.co/h2dn2

Mod List:

![image](https://user-images.githubusercontent.com/101783989/158955260-fc2b5499-494e-4839-994e-816b310815a1.png)

**Comment by CreativeMD** [comment]
Unfortunately I got no idea why it is crashing. I know for sure AmbientSounds works alongside Optifine just fine, no idea about Magnesium. Also i don't support 1.16.5. I guess try to remove a few mods and see if it works then.
