### ISSUE TITLE
Crash on reloading resource pack

### ISSUE THREAD

**Issue by FreezePhoenix** [CreativeMD/AmbientSounds#127]
https://github.com/CreativeMD/AmbientSounds/blob/3f6fa0acc5dbfbced04951dd1c28ea1d2e292b75/src/main/java/team/creative/ambientsounds/AmbientSounds.java#L66

This method cannot return null. Not exactly sure what it's supposed to return, but it's not supposed to return null. Easiest fix would probably be to change it to a reload listener that doesn't have to `prepare`.

**Comment by NekoCompiler** [comment]
Both resource pack and shadow pack with optifine.

It crashes every time I switch shadow pack or resource pack.

It happens on 1.18.2 with latest Forge and Optifine.

**Comment by FreezePhoenix** [comment]
Seems to be specific to Forge.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version.
