### ISSUE TITLE
[Issue] Without some sounds

### ISSUE THREAD

**Issue by rabrunos** [CreativeMD/AmbientSounds#128]
The game does not play some sounds, for example: sound when jumping on a stone block, walking on some blocks, etc.

Some sounds are too low.

When I use the `/ambient-reload` command, the sound stays for a few seconds only and then goes back to being muted and presents this error in the log:

https://mclo.gs/o1msunl

### Specs

Forge 40.0.18
Minecraft 1.18.2
[Mods](https://mclo.gs/DtJrWrf)

---
I tested again but only tested with AmbientSounds 5.0.13 and CreativeCore 2.6.0 (_I removed all other mods._)

https://mclo.gs/X0OrqK2

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
