### ISSUE TITLE
[1.18.2] Weather Volume

### ISSUE THREAD

**Issue by offypoffy** [CreativeMD/AmbientSounds#130]
I am unsure if this is intentional or not, but I've noticed that the Vanilla Weather volume settings have no effect on the mod's Weather volume and besides manually adjusting the mod's config I see no way to reduce the volume without also reducing all other ambient sounds.

I don't know if this has been suggested in the past or is even possible but it would be nice if the weather specific sounds could sync with the vanilla weather volume settings in some way.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for letting me know!!! Very much appreciated.
