### ISSUE TITLE
Multiple Audio

### ISSUE THREAD

**Issue by smithincqhs** [CreativeMD/AmbientSounds#131]
So I have managed to fix the bug on my own but it is still a bit of a pain. I have a lot of options for audio output on my computer. As such, I use the option to set the audio output in Minecraft's settings. Turns out, for whatever reason, this breaks the audio and doesn't allow looping audio to run. Things like wolf howls at night still play but biome ambience loops do not. No errors appear in the ambience-debug.

My temporary solution: Turn on and off both of my main audio outputs and click through all the audio options in-game.

Currently using:
Forge 1.18.2 40.0.23
AmbientSounds FORGE 1.18.2 v5.0.16
CreativeCore 1.18.2 v2.5.9
Optifine 1.18.2 HD U H7

Update: This is not a fix, it only worked the one time. Still have yet to find a solution

**Comment by CreativeMD** [comment]
Update to a newer forge version fixed it!
