### ISSUE TITLE
No sounds for Taiga

### ISSUE THREAD

**Issue by its-theo** [CreativeMD/AmbientSounds#132]
Hey,
I recently downloaded the plugin and installed it. I started my survival world, and the plugin worked fine! I was living in a birch forest, the bird sounds were really beautiful! But then I moved to a different Biome (The Old Growth Pine Taiga), and I cannot hear any sounds of birds etc... the plugin does obviously not play any sounds in that biome - Please fix that as I really like your plugin and I really like my biome :)

**Comment by CreativeMD** [comment]
Can you use the command /ambient-debug and make a screenshot of the situation. This will make it a lot easier for me to fix this issue.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists in the newest version post here again and share a screenshot while having /ambient-debug enabled.

**Comment by its-theo** [comment]
> I will close this issue for now. If it still persists in the newest version post here again and share a screenshot while having /ambient-debug enabled.

I reinstalled Fabric and that fixed it (somehow?) but thanks for replying :)
