### ISSUE TITLE
No sounds high up in the Jungle

### ISSUE THREAD

**Issue by Tytonn** [CreativeMD/AmbientSounds#133]
Hey recently I've been making a treehouse in the jungle and noticed that my ambient sounds would stop at around Y=87 is there any way to change this? Thanks in advance.

**Comment by CreativeMD** [comment]
Use the command /ambient-debug and send a screenshot of the situation. That way I can see a lot more information and get an idea why it's not working.

**Comment by CreativeMD** [comment]
Hopefully fixed in the newest version of the mod.
