### ISSUE TITLE
1.18.2 Forest sounds plays when placing decorative leaves 

### ISSUE THREAD

**Issue by ili0s** [CreativeMD/AmbientSounds#136]
When using leaves as decoration (like making plants and etc) it causes forest sounds to play even when inside a building

**Comment by CreativeMD** [comment]
Things are handled a little bit different in the newest version for 1.19. That might fix your issue. I also have dropped support for 1.18.

**Comment by Roadhog360** [comment]
I know this may be slightly off-topic, but considering the current 1.19 backlash, both with underdelivering, and reports, I have noticed not a lot of mods that I am using have updated to 1.19. Please reconsider. :)

**Comment by CreativeMD** [comment]
@Roadhog360 mods always require some time to update. There are lots of changes, but once 1.19.1 comes up things will be quite stable. I got plenty of stuff to do and I save a lot of time when I only support one version. The version for 1.18 is fine and works, so I don't see the need to port all the new features back.

**Comment by Roadhog360** [comment]
I meant reconsider for not supporting old versions. I get that not everyone has the time to maintain the last few versions, but considering the backlash, I would highly recommend at least accepting reports for the 1.18 version. I have a gut feeling 1.18 is going to have a lot more mod downloads than 1.19 for the time being if Mojang continues to ignore the negative feedback, and release the update the way it is. I have seen a lot of people suggested boycotting 1.19 all together.

**Comment by CreativeMD** [comment]
I think 1.19 will be quite a big version. Mods for 1.18 are stable enough.
