### ISSUE TITLE
Playing the sound of caves, even when I got out of it

### ISSUE THREAD

**Issue by Mornikale1** [CreativeMD/AmbientSounds#138]
Hello, I faced a small problem in your mod, when I go into the cave, the sounds of the caves are played, but when I go to the surface, the sounds of the caves are still played, but not the sounds of nature, restarting the game sometimes helps, but often the bug repeats, If you can fix it, I'll be glad, thanks in advance) (There may be problems in other mods)

Game:
Minecraft - 1.19 (Client)
Modloader - Fabric 0.14.8-1.19
Version of Ambient Sounds -  [AmbientSounds_FABRIC_v5.2.0_mc1.19.jar]
Version of Creative Core - [CreativeCore_FABRIC_v2.7.2_mc1.19.jar]

**Comment by CreativeMD** [comment]
Can you use the command /ambient-debug and make a few screenshots of the situation?

**Comment by Mornikale1** [comment]
ok i will do

**Comment by Mornikale1** [comment]
here you are

![2022-06-30_08 36 16](https://user-images.githubusercontent.com/100231671/176601196-41a3f581-76a3-498e-b05d-130793cd86df.png)
![2022-06-30_08 36 22](https://user-images.githubusercontent.com/100231671/176601210-1340fa1a-537e-4779-99b6-150fec912c21.png)
![2022-06-30_08 37 23](https://user-images.githubusercontent.com/100231671/176601223-e9bc0e2e-4184-476e-b576-0fda1d1d50b5.png)
![2022-06-30_08 36 24](https://user-images.githubusercontent.com/100231671/176601234-9b97a5cb-8ad6-4c64-a3bd-40aa8b1020a3.png)
![2022-06-30_08 36 48](https://user-images.githubusercontent.com/100231671/176601248-6a389829-138e-44c9-9e12-f600ae43889e.png)
![2022-06-30_08 37 06](https://user-images.githubusercontent.com/100231671/176601259-5e7bf1f9-8298-4f58-a0e8-29675014c17d.png)

**Comment by CreativeMD** [comment]
If you are two high up in the air there won't be any biome sounds but instead a wind. This region is called `sky` and is present in some of your screenshots.

Furthermore the engine needs a few seconds to adapt to the new environment, but you probably waited already a few seconds before taking the screenshot. I have tried to reproduce it myself, but could not. I got no idea how this can happen.

**Comment by CreativeMD** [comment]
Are there any news about this issue?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists please respond here.
