### ISSUE TITLE
1.18.2 Forest birds plays on beach.

### ISSUE THREAD

**Issue by zEpiixz** [CreativeMD/AmbientSounds#140]
![2022-07-06_09 44 40](https://user-images.githubusercontent.com/40037440/177497511-cc71f62c-79dc-41cf-99fd-a87ec03c217f.png)

**Comment by CreativeMD** [comment]
There are trees, so yeah there are bird sounds. Not sure if that is a real problem? I could mute forest sounds for beaches? Will close this issue for now. Would be very happy if you could still respond to my questions.

**Comment by zEpiixz** [comment]
I think muting the forest sounds on beaches would be ideal. Because the sounds sound more like passerine and various forest related birds which also doesnt mix very well with the seagull sound which i think for beaches is enough.  It just feels a bit weird when there is one palm tree sometimes and the birds are rocking their sound lol

**Comment by CreativeMD** [comment]
Ok, I will see what I can do about it (added it to my todo list).
