### ISSUE TITLE
Crash with Oh, the biomes you'll go

### ISSUE THREAD

**Issue by SheReyy** [CreativeMD/AmbientSounds#141]
Minecraft: 1.16.5
Forge: 36.2.33
Ambient Sounds: AmbientSounds_v3.1.11_mc1.16.5.jar
BYG: byg-1.3.5.jar

In the Guiana Clearing Biome, I get a crash sometimes.
[Here](https://gist.github.com/IamRyan30/a9be1e936f307cbc8a61676d6a693262)'s the log.

**Comment by CreativeMD** [comment]
Please post the crash-report here. The log does not include any crash at all.

**Comment by SheReyy** [comment]
Look at the full log.

**Comment by SheReyy** [comment]
I deleted the rest of the log. Only the crash should be visible now.

**Comment by CreativeMD** [comment]
Normally the crash is at the end of the file, sorry must have overlooked it. I have seen this crash before and it normally does happen if AmbientSounds is installed on server side (which is not the case here). To be honest I got no idea what is going wrong. Maybe it's a conflict with another mod. You could try to install just CreativeCore and AmbientSounds and see if it works. Then add more and more mods till it crashes again. Also have to say that I have dropped support for 1.16.5. I'm very sorry for the situation, but I don't see a different way to help you at the moment.

**Comment by SheReyy** [comment]
Understood. It doesn't happen that often, but yeah. Might be a loading order issue or something. I'll look into it more at some point.

**Comment by CreativeMD** [comment]
Ok. I will close this issue for now.
