### ISSUE TITLE
sound changes upon nearing houses

### ISSUE THREAD

**Issue by pkaifes** [CreativeMD/AmbientSounds#143]
Hello! Firstly, I love this mod. But is there a way to have the sounds played based on biome, rather than what blocks I'm near? I built my house in a meadow, very few trees around, and my house is made from spruce. but upon nearing/ entering my house, suddenly the taiga and cold forest ambiance starts going and it's somewhat obnoxious, like I've suddenly entered a jungle. I've turned the volume down for now, but then it feels weird to actually enter a taiga, and the ambiance isn't there. Any recommendations? Thank you.

**Comment by CreativeMD** [comment]
Can you type in the command /ambient-debug ingame and send a few screenshots while the debug is active around your house. I need to more information to see what could cause this issue.

**Comment by pkaifes** [comment]
yeah, thank you for looking into this
![2022-08-08_23 43 44](https://user-images.githubusercontent.com/58061585/183566406-3c664f63-e004-4b51-978f-4005cb9ef23c.png)

![2022-08-08_23 43 26](https://user-images.githubusercontent.com/58061585/183566394-de66c65a-772f-42a3-9834-67c15c6f534c.png)

![2022-08-08_23 41 23](https://user-images.githubusercontent.com/58061585/183566373-ee80fd93-41dc-45c0-a62e-b300e5cf1121.png)
![2022-08-08_23 41 38](https://user-images.githubusercontent.com/58061585/183566377-99dd4d38-fafb-4d7b-84d7-f5faaa95d54f.png)
![2022-08-08_23 41 54](https://user-images.githubusercontent.com/58061585/183566386-2c7bd737-d778-4597-ac84-fcbbb96b2bc3.png)
.

**Comment by CreativeMD** [comment]
Because you have leaves and logs there AmbientSounds thinks there are trees. I think the best way to solve is to check whether leaves are placed or naturally generated. Will try to fix it the next days.

**Comment by pkaifes** [comment]
Thank you very much for your help, and yes, the leaves and logs were placed manually.

**Comment by CreativeMD** [comment]
Fixed in the newest version, hope that makes it better. Let me know what you think here. I will still close this issue for now.

**Comment by pkaifes** [comment]
Cool, can't wait to try it! Do you know when the update will be available on CurseForge for Fabric? or is there a process you have for exporting the code repo to a jar that I could do manually?

**Comment by CreativeMD** [comment]
It finally has been approved after one day. You can download it now.
