### ISSUE TITLE
Fantastic mod! Volume customization?

### ISSUE THREAD

**Issue by cemerson** [CreativeMD/AmbientSounds#147]
Hey there. This is a great mod - nice work. Quick question - is it possible to set a global volume on this mod's sounds? I've looked through the Wiki and the JAR/JSON contents but don't see anything that looks like this yet.

**Comment by CreativeMD** [comment]
Added in the newest version. Using the command /cmdclientconfig you can configure the volume in `general`. You can also use the `Ambient/ Environment` slider from minecraft to adjust the volume.
