### ISSUE TITLE
Is it possible for ambient sounds like the birds, or the dripping in dripstone caves to stop playing while underwater?

### ISSUE THREAD

**Issue by HereToSaySomething** [CreativeMD/AmbientSounds#149]
So I was trying this mod out on 1.19.2 and I was very happy with most of the results. The only thing that bothers me is when I can hear birds while swimming underwater in rivers, or when I hear drops of water in submerged dripstone caves, which doesn't make much sense so it is quite immersion-breaking. The audio is overlayed on top of the underwater sounds this mod adds. I was using Sound Physics Remastered, but then I tried the mod without Sound Physics Remastered and the issue persists. Is it possible for this to be fixed?

**Comment by CreativeMD** [comment]
Underwater "mutes" (or decreases the volume) of all the other sounds. In theory this should make them quite difficult to be heard, but maybe this effect is not enough? Can you use the command /ambient-debug and make some screenshots underwater?

**Comment by HereToSaySomething** [comment]
![2022-10-17_20 56 32](https://user-images.githubusercontent.com/79809777/196311657-e247bb3a-250c-4f8f-b077-980536e5bceb.png)
![2022-10-17_21 03 01](https://user-images.githubusercontent.com/79809777/196311672-91886d0e-53ff-43e8-aecd-f3f010af52dd.png)
![2022-10-17_21 06 19](https://user-images.githubusercontent.com/79809777/196311702-cc0f63df-86e7-4d25-8d3e-5adbe69c00d9.png)
![2022-10-17_21 17 38](https://user-images.githubusercontent.com/79809777/196312661-1dd455f2-0502-4887-a884-b2514bc1834b.png)

I am noticing that it _occasionally_ "mutes" the other sounds. But it usually takes a whole minute to do so, and even then, it only does this sometimes, and in certain places, like at the very bottom of the river. Also, the outside-of-water audio is still audible, just quieter. And in the underwater dripstone cave, it didn't "mute" at all. 

I think **if** the audio from outside the water is supposed to be somewhat audible when you are underwater but near the surface of the water, then the above-water audio should have some sort of filter that distorts the sound because, despite the volume, it does not sound right for the audio to be so clear when you are underwater.
Also maybe have a sound play for when you go above the surface for air and a sound for when you dive back in. That way, the transition between above water and below water is more smooth and less jarring, And if you do that, you probably want one quieter variant for exiting the water when you exit slower, like when pressing the space bar, versus when you swim up faster, like during the swimming animation. I don't know these are just some ideas I had.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I finally found time to look at the issue. Seems this functionality did not work at all. It has been fixed now. New versions should be available in a few minutes. Thank you so much for your time and effort to report this issue in all the detail.

**Comment by HereToSaySomething** [comment]
Thank you for actually going out of your way to fix the issue so quickly. Your efforts are well appreciated.
