### ISSUE TITLE
Client Crashed 1.12

### ISSUE THREAD

**Issue by sofifreak** [CreativeMD/AmbientSounds#15]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (backpacks16840.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  LoadingPlugin ([1.12] VersionChecker-1.3.0.jar)
  SFRCore (solar-flux-reborn.jar)
  Inventory Tweaks Coremod (inventorytweaks.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-beta1-1.12-anarchy.jar)
  BetterFoliageLoader (betterfoliage.jar)
  IELoadingPlugin (immersive-engineering.jar)
  DynamicSurroundingsCore (dsurround.jar)
  HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  DLFMLCorePlugin (dynamic-lights.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/9/17 9:32 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at paulscode.sound.SoundSystem.stop(SoundSystem.java:1188)
	at com.creativemd.ambientsounds.AmbientSoundEngine.stop(AmbientSoundEngine.java:241)
	at com.creativemd.ambientsounds.AmbientSound.stopSound(AmbientSound.java:220)
	at com.creativemd.ambientsounds.AmbientSound.tick(AmbientSound.java:238)
	at com.creativemd.ambientsounds.TickHandler.onTick(TickHandler.java:241)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_231_TickHandler_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at paulscode.sound.SoundSystem.stop(SoundSystem.java:1188)
	at com.creativemd.ambientsounds.AmbientSoundEngine.stop(AmbientSoundEngine.java:241)
	at com.creativemd.ambientsounds.AmbientSound.stopSound(AmbientSound.java:220)
	at com.creativemd.ambientsounds.AmbientSound.tick(AmbientSound.java:238)
	at com.creativemd.ambientsounds.TickHandler.onTick(TickHandler.java:241)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_231_TickHandler_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Sofifreak'/81302, l='MpServer', x=192.76, y=88.00, z=611.11]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (113,64,457), Chunk: (at 1,4,9 in 7,28; contains blocks 112,0,448 to 127,255,463), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 94357291 game time, 3144566 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 51 total; [EntityCreeper['Creeper'/96769, l='MpServer', x=253.50, y=59.00, z=663.50], EntityWitch['Witch'/96768, l='MpServer', x=257.50, y=59.00, z=662.50], EntityItemFrame['entity.ItemFrame.name'/7, l='MpServer', x=193.97, y=90.50, z=610.50], EntityItemFrame['entity.ItemFrame.name'/8, l='MpServer', x=193.97, y=90.50, z=612.50], EntityItemFrame['entity.ItemFrame.name'/9, l='MpServer', x=188.50, y=90.50, z=613.97], EntityItemFrame['entity.ItemFrame.name'/10, l='MpServer', x=189.03, y=90.50, z=614.50], EntityItemFrame['entity.ItemFrame.name'/11, l='MpServer', x=189.03, y=95.50, z=614.50], EntityItemFrame['entity.ItemFrame.name'/12, l='MpServer', x=188.50, y=95.50, z=615.03], EntityItemFrame['entity.ItemFrame.name'/14, l='MpServer', x=188.50, y=90.50, z=609.03], EntityItemFrame['entity.ItemFrame.name'/15, l='MpServer', x=186.50, y=90.50, z=609.03], EntityItemFrame['entity.ItemFrame.name'/16, l='MpServer', x=191.50, y=84.50, z=610.03], EntityItemFrame['entity.ItemFrame.name'/17, l='MpServer', x=188.97, y=89.50, z=608.50], EntityPlayerSP['Sofifreak'/81302, l='MpServer', x=192.76, y=88.00, z=611.11], EntityBat['Bat'/92952, l='MpServer', x=200.77, y=62.10, z=598.38], EntityBat['Bat'/92956, l='MpServer', x=201.44, y=62.10, z=596.50], EntityCreeper['Creeper'/96809, l='MpServer', x=115.50, y=39.00, z=681.50], EntitySheep['Sheep'/71, l='MpServer', x=137.87, y=82.00, z=575.59], EntityBat['Bat'/95345, l='MpServer', x=201.44, y=62.10, z=599.73], EntityCow['Cow'/121, l='MpServer', x=239.30, y=89.00, z=539.45], EntityCreeper['Creeper'/96637, l='MpServer', x=245.50, y=15.00, z=641.50], EntityCreeper['Creeper'/96636, l='MpServer', x=245.50, y=15.00, z=641.50], EntityItemFrame['entity.ItemFrame.name'/18820, l='MpServer', x=187.50, y=90.50, z=609.03], EntityHorse['Horse'/81300, l='MpServer', x=197.98, y=90.00, z=638.11], EntityMinecartChest['Minecart with Chest'/81303, l='MpServer', x=128.51, y=33.00, z=665.61], EntityMinecartChest['Minecart with Chest'/81304, l='MpServer', x=143.50, y=33.06, z=677.50], EntityChicken['Chicken'/81307, l='MpServer', x=209.41, y=90.00, z=661.18], EntitySheep['Sheep'/81309, l='MpServer', x=238.29, y=91.00, z=655.76], EntitySheep['Sheep'/81311, l='MpServer', x=238.05, y=91.00, z=656.80], EntitySheep['Sheep'/81310, l='MpServer', x=240.55, y=91.00, z=644.43], EntityCow['Cow'/81313, l='MpServer', x=241.21, y=91.00, z=652.59], EntityChicken['Chicken'/81315, l='MpServer', x=236.82, y=91.00, z=657.17], EntityCow['Cow'/81314, l='MpServer', x=240.16, y=91.00, z=648.61], EntityCow['Cow'/81317, l='MpServer', x=237.31, y=91.00, z=644.72], EntityCow['Cow'/81316, l='MpServer', x=237.37, y=91.00, z=653.21], EntityCow['Cow'/81319, l='MpServer', x=241.17, y=91.00, z=656.49], EntityChicken['Chicken'/81318, l='MpServer', x=236.82, y=91.00, z=649.17], EntityCow['Cow'/81321, l='MpServer', x=241.52, y=91.00, z=646.98], EntitySheep['Sheep'/81320, l='MpServer', x=207.39, y=88.10, z=593.46], EntityCow['Cow'/81323, l='MpServer', x=241.44, y=91.00, z=647.99], EntitySheep['Sheep'/81325, l='MpServer', x=237.47, y=91.00, z=647.26], EntityChicken['Chicken'/81324, l='MpServer', x=238.17, y=91.00, z=653.26], EntityChicken['Chicken'/81327, l='MpServer', x=241.55, y=91.00, z=644.00], EntityCow['Cow'/81326, l='MpServer', x=241.18, y=91.00, z=645.63], EntitySheep['Sheep'/81329, l='MpServer', x=252.65, y=91.00, z=567.24], EntitySheep['Sheep'/86203, l='MpServer', x=269.52, y=91.00, z=564.79], EntityCow['Cow'/86205, l='MpServer', x=252.53, y=92.00, z=630.20], EntityChicken['Chicken'/86208, l='MpServer', x=266.42, y=91.00, z=682.22], EntitySkeleton['Skeleton'/93636, l='MpServer', x=198.72, y=61.00, z=592.77], EntityMinecartChest['Minecart with Chest'/81352, l='MpServer', x=118.51, y=34.00, z=664.49], EntityCreeper['Creeper'/96734, l='MpServer', x=241.50, y=51.00, z=686.50], EntityItem['item.item.egg'/96480, l='MpServer', x=209.21, y=90.00, z=660.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3755450144 bytes (3581 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 Optifine OptiFine_1.12_HD_U_C5_pre 103 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	forge{14.21.1.2443} [Minecraft Forge] (modpack.jar) 
	UCHIJA	backpacks16840{3.3.2} [Backpacks!] (backpacks16840.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	versionchecker{1.3.0} [Version Checker] ([1.12] VersionChecker-1.3.0.jar) 
	UCHIJA	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.7 mc1.12.jar) 
	UCHIJA	antiqueatlas{4.4.4} [Antique Atlas] (antiqueatlas-1.12-4.4.4.jar) 
	UCHIJA	antiqueatlasoverlay{1.2} [Antique Atlas Overlay] (antiqueatlas-1.12-4.4.4.jar) 
	UCHIJA	baubles{1.5.1} [Baubles] (baubles.jar) 
	UCHIJA	betterunderground{1.0.1} [Better Underground] (better-underground.jar) 
	UCHIJA	betterfoliage{2.1.8} [Better Foliage] (betterfoliage.jar) 
	UCHIJA	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCHIJA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.12-1.5.1.jar) 
	UCHIJA	codechickenlib{3.1.2.297} [CodeChicken Lib] (codechickenlib.jar) 
	UCHIJA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJA	brandonscore{2.3.2} [Brandon's Core] (brandons-core.jar) 
	UCHIJA	cavern{1.10.1} [Cavern] (cavern.jar) 
	UCHIJA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJA	chisel{MC1.12-0.0.13.15} [Chisel] (Chisel-MC1.12-0.0.13.15.jar) 
	UCHIJA	shadowmc{3.8.0} [ShadowMC] (ShadowMC-1.12-3.8.0.jar) 
	UCHIJA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.12-1.3.0.jar) 
	UCHIJA	cofhcore{4.3.4} [CoFH Core] (cofhcore.jar) 
	UCHIJA	cofhworld{1.0.1} [CoFH World] (cofhworld.jar) 
	UCHIJA	ctm{MC1.12-0.2.1.5} [CTM] (CTM-MC1.12-0.2.1.5.jar) 
	UCHIJA	customnpcs{1.12} [CustomNPCs] (custom-npcs.jar) 
	UCHIJA	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCHIJA	draconicevolution{2.3.3} [Draconic Evolution] (draconic-evolution.jar) 
	UCHIJA	dsurround{3.4.7.0} [ยง3Dynamic Surroundings] (dsurround.jar) 
	UCHIJA	presets{3.4.7.0} [ยง3Presets!] (dsurround.jar) 
	UCHIJA	dynamiclights{1.4.6} [Dynamic Lights] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_onfire{1.0.7} [Dynamic Lights on burning] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_creepers{1.0.6} [Dynamic Lights on Creepers] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_dropitems{1.1.0} [Dynamic Lights on ItemEntities] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_entityclasses{1.0.1} [Dynamic Lights on specified Entities] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_mobequipment{1.1.0} [Dynamic Lights on Mob Equipment] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_flamearrows{1.0.1} [Dynamic Lights on Flame enchanted Arrows] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_floodlights{1.0.3} [Dynamic Lights Flood Light] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_otherplayers{1.0.9} [Dynamic Lights Other Player Light] (dynamic-lights.jar) 
	UCHIJA	dynamiclights_theplayer{1.1.3} [Dynamic Lights Player Light] (dynamic-lights.jar) 
	UCHIJA	enderore{1.12-b1} [Ender Ore] (Ender Ore-1.12-b2.jar) 
	UCHIJA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCHIJA	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHIJA	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCHIJA	gottschcore{1.1.2} [GottschCore] (gottschcore.jar) 
	UCHIJA	fastladder{1.0.6} [FastLadder!] (FastLadder-mc1.12-v1.0.6.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.8.0-beta1-1.12-anarchy.jar) 
	UCHIJA	ic2{2.8.16-ex112} [IndustrialCraft 2] (ic2.jar) 
	UCHIJA	jei{4.7.8.92} [Just Enough Items] (jei.jar) 
	UCHIJA	mantle{1.12-1.3.1.18} [Mantle] (mantle.jar) 
	UCHIJA	natura{1.12-4.3.0.17} [Natura] (natura.jar) 
	UCHIJA	forestry{5.5.1.184} [Forestry] (forestry.jar) 
	UCHIJA	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCHIJA	fw{1.6.0} [Fullscreen Windowed] (FullscreenWindowed-1.12-1.6.0.jar) 
	UCHIJA	gardenstuff{1.12-2.1.0} [Garden Stuff] (GardenStuff-1.12-2.1.0.jar) 
	UCHIJA	goldcauldron{1.1} [Gold Cauldron] (goldcauldron-1.1.jar) 
	UCHIJA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJA	hammercore{1.9.4.0} [Hammer Core] (HammerCore-1.12-1.9.4.0.jar) 
	UCHIJA	harvestcraft{1.12.1b} [Pam's HarvestCraft] (harvestcraft.jar) 
	UCHIJA	hopperducts{1.5} [Hopper Ducts] (hopperducts-mc1.12-1.5.jar) 
	UCHIJA	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCHIJA	tconstruct{1.12-2.7.2.19} [Tinkers' Construct] (tconstruct.jar) 
	UCHIJA	immersiveengineering{0.12-71} [Immersive Engineering] (immersive-engineering.jar) 
	UCHIJA	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHIJA	teslacorelib{1.0.8} [Tesla Core Lib] (tesla-core-lib.jar) 
	UCHIJA	industrialforegoing{1.12-1.12} [Industrial Foregoing] (industrial-foregoing.jar) 
	UCHIJA	inventorytweaks{1.63+beta.108.6ff67c4} [Inventory Tweaks] (inventorytweaks.jar) 
	UCHIJA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJA	jehc{1.3.0} [Just Enough HarvestCraft] (jehc-1.12-1.3.0.jar) 
	UCHIJA	journeymap{1.12-5.5.0b3} [JourneyMap] (journeymap.jar) 
	UCHIJA	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCHIJA	refinedstorage{1.5.17} [Refined Storage] (refinedstorage.jar) 
	UCHIJA	moartinkers{0.5.4} [Moar Tinkers] (moartinkers.jar) 
	UCHIJA	nei{${mod_version}} [Not Enough Items] (nei.jar) 
	UCHIJA	nex{2.1.11.12} [NetherEx] (NetherEx-1.12-2.1.11.12.jar) 
	UCHIJA	openglider{@VERSION@} [Open Glider] (open-glider.jar) 
	UCHIJA	plants{1.2.0} [Plants] (Plants-1.12-1.2.0(1).jar) 
	UCHIJA	reauth{3.5.1} [ReAuth] (reauth.jar) 
	UCHIJA	reborncore{3.2.5.88} [Reborn Core] (reborncore.jar) 
	UCHIJA	rebornstorage{1.0.0} [RebornStorage] (rebornstorage.jar) 
	UCHIJA	refinedstorageaddons{0.1.1} [Refined Storage Addons] (refinedstorageaddons-0.1.1.jar) 
	UCHIJA	rftools{6.13} [RFTools] (rftools.jar) 
	UCHIJA	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8.jar) 
	UCHIJA	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCHIJA	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCHIJA	signpost{1.05.5} [Sign Post] (signpost.jar) 
	UCHIJA	simplecorn{2.3.2} [Simple Corn] (SimpleCorn1.12-2.3.2.jar) 
	UCHIJA	simplequarry{1.0.7} [Simple Quarry] (SimpleQuarry-1.12-1.0.7.jar) 
	UCHIJA	simplebedrolls{1.2.1} [Simple Bedrolls] (simply-bedrolls.jar) 
	UCHIJA	simulatednights{1.12-2.1.0} [Simulated Nights] (simulatednights-1.12-2.1.0.jar) 
	UCHIJA	solarfluxreborn{3.25r} [Solar Flux Reborn] (solar-flux-reborn.jar) 
	UCHIJA	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCHIJA	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCHIJA	subcommonlib{1.2.0.1} [Subaraki's Common Library] (subcommonlib-sublib-1.12-1.2.0.1.jar) 
	UCHIJA	telepads{1.11.2-1.0.2.1} [Telepads] (telepads.jar) 
	UCHIJA	thermalfoundation{2.3.4} [Thermal Foundation] (thermalfoundation.jar) 
	UCHIJA	thermaldynamics{2.3.4} [Thermal Dynamics] (thermaldynamics.jar) 
	UCHIJA	thermalexpansion{5.3.4} [Thermal Expansion] (thermalexpansion.jar) 
	UCHIJA	waystones{4.0.15} [Waystones] (waystones.jar) 
	UCHIJA	teslacorelib_registries{1.0.8} [Tesla Core Lib Registries] (tesla-core-lib.jar) 
	UD	solarfluxreborncore{3.25r} [Solar Flux Reborn: Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (backpacks16840.jar)
  brad16840.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
LoadingPlugin ([1.12] VersionChecker-1.3.0.jar)
  
SFRCore (solar-flux-reborn.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
Inventory Tweaks Coremod (inventorytweaks.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-beta1-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
BetterFoliageLoader (betterfoliage.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
IELoadingPlugin (immersive-engineering.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
DynamicSurroundingsCore (dsurround.jar)
  org.blockartistry.DynSurround.asm.Transformer
HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  team.chisel.ctm.client.asm.CTMTransformer
DLFMLCorePlugin (dynamic-lights.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GT 740M/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.5.88
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.12-forge1.12-14.21.1.2443
	LWJGL: 2.9.4
	OpenGL: GeForce GT 740M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: FaithfulMods 1.12-rv1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz

**Comment by CreativeMD** [comment]
This is a known issue and already reported here: https://github.com/CreativeMD/AmbientSounds/issues/7 .
We are still waiting for the author of the paulscode engine to fix it.
