### ISSUE TITLE
Crash when joining world with AmbientSounds 5.2.7

### ISSUE THREAD

**Issue by pupnewfster** [CreativeMD/AmbientSounds#150]
Crash when joining world: https://gist.github.com/pupnewfster/52d680fea4397eae5e2103235dda43d6

Based on the log it seems to be using some method that either got removed or isn't in a released Creative Core version (but given creative core just updated that seems less likely). Downgrading to 5.2.5 seems to load just fine

Creative Core: 2.8.9
Forge: 43.1.47
AmbientSounds: 5.2.7

**Comment by CreativeMD** [comment]
Oh right. I messed up something. Thanks for reporting this issue. A new version is on the way to fix it. It should be available in a few minutes.

**Comment by pupnewfster** [comment]
Can confirm, appears to be working fine now. Thanks
