### ISSUE TITLE
Crash when generating a new world

### ISSUE THREAD

**Issue by zeid0ne** [CreativeMD/AmbientSounds#151]
How to reproduce => install all mods in the provided .zip (minecraft 1.19.2, forge 43.1.47). Open minecraft and create a new world with game mode = Creative (let other settings by default).

Full trace of the error here : https://paste.ee/p/OYmUN

Zip : https://drive.google.com/file/d/1K19fkmomurSqhzJiCMwBrIUFzKb6d2XV/view?usp=share_link

**Comment by CreativeMD** [comment]
A new version has already been released which fixes this issue. Thanks for reporting it anyway!
