### ISSUE TITLE
cave sound loop has a hard transition

### ISSUE THREAD

**Issue by coisle** [CreativeMD/AmbientSounds#152]
on Fabric, 1.19.2 every time the cave sound loops it plays "out of volume" for 1 second

**Comment by CreativeMD** [comment]
What does this mean? There is no "out of volume" sound effect. Could you explain it further?

**Comment by coisle** [comment]
[https://youtu.be/3yV1Hg9elnU](url)
I recorded it there, it happens every time the ambient loops, sometimes even multiple times

**Comment by CreativeMD** [comment]
I think I found the issue. Thanks for reporting this issue, in particular the video, which hinted at an exact problem. The new version will be available soon (it's already uploaded and needs to be approved).

**Comment by coisle** [comment]
unfortunately it is still happening after updating to the newest version. I tried deleting the config and let it generate again but it didn't fix it

**Comment by CreativeMD** [comment]
That is very weird. So you tried `AmbientSounds_FABRIC_v5.2.9_mc1.19.2.jar`? Does it happen every time or just once in a while?

**Comment by coisle** [comment]
Yes, I am running that exact version. It happens every time very consistently when the sound loops.
I also tried it in single and multiplayer, doesn't make a difference.
But I've recorded another instance, this time with the debug info, hopefully this will help
https://youtu.be/mchepwOlibA
as far as I can see it happens very noticable when deep2 starts playing, and less noticable when cave1 starts

**Comment by CreativeMD** [comment]
YES!!! I could finally figure out why. My last attempt to fix it was close, but I forgot one little detail. New versions are uploaded! Thank you soooo much! Your detailed description made it quite easy to reproduce. I have noticed this issue a long time ago, but never managed to pin it down to a transition. Super happy about.

**Comment by coisle** [comment]
thank you so much!
