### ISSUE TITLE
[1.19.2] Forest sounds continue to play during rain, rain silent

### ISSUE THREAD

**Issue by 0DeltaWaves** [CreativeMD/AmbientSounds#153]
[This issue](https://github.com/CreativeMD/AmbientSounds/issues/114) is still a thing in the latest version - though in my experience, the rain is inaudible which seems to be a bug. I also believe birds should be completely silent during rain, otherwise it's not very immersive.
This happens in any forest-type biome, modded or vanilla. Haven't tested other biome types.
![image](https://user-images.githubusercontent.com/82335536/202559103-0d427147-0f18-4245-8506-c957f842e336.png)

Also, the birds sing all throughout the night as well. I can provide another screenshot for that if necessary.

**Comment by CreativeMD** [comment]
AmbientSounds detects worldRain, but notice that `rain` is false. So somehow the player does not seem to stand in the rain. Are there any other mods installed?

**Comment by 0DeltaWaves** [comment]
Here's the mod list:
![image](https://user-images.githubusercontent.com/82335536/203392442-978a635e-8cb3-45f2-bda5-6d98ab31cbe4.png)

![image](https://user-images.githubusercontent.com/82335536/203394785-9abc1372-68f2-4cc7-82ab-2a4595d8bbba.png)

I thought it may be biomes you'll go messing with things, so I'm testing this on a world with no mods except for ambient sounds/creative core. 

Here, I am standing out in the open in a vanilla forest biome. Rain is audible, bird sound is reduced.
![image](https://user-images.githubusercontent.com/82335536/203396305-1870f2a3-d86e-42b4-ac33-acfce97434fc.png)

Now I'm standing under a tree and the ambient rain sound disappeared, and birds are at full volume. You can see it's raining, so it creates an inconsistency between the environment and the ambient sounds. The birds make it sound like a sunny day.
![image](https://user-images.githubusercontent.com/82335536/203396501-7fbe97aa-c3cd-4afa-bcf7-5ba6a46062b9.png)
The problem is that forest biomes are covered in trees of course, so this happens often.
Also tested this by building a dirt enclosure with an opening, and same thing happens - no ambient rain, birds at full volume. If I block off the entryway, making it a closed space, then birds stop, which is appropriate.

Other biomes I tested:
Jungle, taiga: no ambient rain and crickets/birds also play at full volume when under a tree. Problem is especially bad with the "bird ambience huge" tracks, as they're particularly loud.
BYG canadian shield (biome I was in for the initial issue post): no matter where you stand, there is no ambient rain sound and birds/crows/etc play at full volume. They also continue to play during night at full volume. So this seems to be a problem in vanilla *and* BYG, in different ways. 

To summarize, the main issue is that trees/blocks over your head causes environmental noises (birds, bugs, etc) to play at full volume during rain. I think much of this can be solved by having no birds/bugs at all when it is raining and/or night time. Even when the bird/bug volume is reduced as intended, it still sounds unrealistic to me. In cases where birds do sing during rain in real life, they tend to sing differently - the same sunny day bird chorus tracks being reduced in volume doesn't really give that effect in my opinion. And at night, the diurnal (daytime) birds being heard even at reduced volume sounds very out of place as well.
The only sounds at night should be crickets, owls, and specifically nocturnal creatures.
As with BYG, I'm not sure where the problem lies or whose end it's on.

Let me know if there's any other info I can provide.

**Comment by CreativeMD** [comment]
Sorry that it took me so long to respond. Thanks a lot for your detailed information. Could you try out the newest version and tell me what you think about it?
https://modrinth.com/mod/ambientsounds/version/3.1.5

**Comment by 0DeltaWaves** [comment]
No worries, I appreciate the update! Here are my thoughts:

**Vanilla biomes**
- No birds sing during rain while standing out in the open now, which is a huge improvement.
- Birds still start to sing while under trees/blocks during rain, seems like that part might have been missed in the revision.
- Chorus of daytime birds/insects still sing throughout the night during clear weather.

- Birds/rain stop being audible in some parts of closed buildings as expected, but can be heard in other areas of the same building, unclear why. In the images below, you can see that depending on where I am in this house, I can hear birds/rain as if I'm outside. Can do some more detailed testing if required.
![2022-11-28_16 34 50](https://user-images.githubusercontent.com/82335536/204402336-29db451e-879b-4914-b1a5-3049536b48fa.png)
![image](https://user-images.githubusercontent.com/82335536/204394868-afbdb0f0-81f2-4527-abed-e96c71da5e64.png)
Here's a video which better shows the strangeness. Loud and lively birdsong during storm at night, while indoors (unmute audio): https://imgur.com/a/CJ5vCIZ


**BYG biome**
- Issues mentioned in the original post still present (silent rain, birds full volume). I tested some other BYG biomes classified as "cool forest" but the problem seems to only occur with the "canadian shield" biome for some reason. If you think this is on BYG's end, I can I can open an issue with them rather than here.

**Comment by CreativeMD** [comment]
Ok. I fixed an issue with the rain detection. My last version still had an issue there. I hope this fixed all of the rain issues, even the the one in BYG biomes (I hope). Furthermore I have muted all bird sounds (except the crow) during the night.

The last issue described is a more complicated one. AmbientSounds scans the air around you. Somehow there is a gap in the wall. Maybe one of the blocks is not considered to be solid. Maybe you can do some testing by replacing some of the materials to see if they can actually block the scan or not.

Again thanks a lot for all of your feedback. Let me know if everything is working properly.

**Comment by 0DeltaWaves** [comment]
Awesome, the environmental noises are a lot more appropriate/immersive now. Thank you! This has been one of my staple mods for a long time (I have my partner/friends use it too, we all like it), so I'm glad to see these improvements.

Good news on the indoor sounds issue - after experimenting with replacing blocks by type, I've figured out the culprit: stairs. They're not treated as solid blocks apparently, even when placed so that there is no visible gap.

As for BYG, the Canadian Shield biome basically makes Ambient Sounds act as if the entire biome has no access to sky (specifically, it thinks you're always under a tree).
![image](https://user-images.githubusercontent.com/82335536/204946726-8e3ecc59-7e11-4156-b775-401912a79546.png)
Very interesting. I have no idea how coding works so I might be wrong, but this sounds like it might be something on their end. I will post the issue on their repository and see what they say.

**Comment by CreativeMD** [comment]
Stairs are now considered to be solid blocks in the newest version. Thanks a lot for all of your feedback! No idea about the other issue, but it seems like the method `level.isRainingAt(BlockPos)` will return false in this biome, probably because they wanted to add their own rain effects. Hope that is not a big issue. Will close this here as it is solved now. Hope you and your partner/friends are having a good time!
