### ISSUE TITLE
Silent Ice Spikes

### ISSUE THREAD

**Issue by NPlaysMC** [CreativeMD/AmbientSounds#155]
The Ice Spikes biome does not have any ambience. Whenever I walk in from another biome, the sound of the first fades away and there's no new sound playing.

I'm playing with Version 5.2.13 Forge, version 1.19.2 of Minecraft

**Comment by CreativeMD** [comment]
Can you go inside the biome, use the command /ambient-debug and send me a screenshot of it?

**Comment by NPlaysMC** [comment]
The screenshots are attached. It also doesn't seem to work with Mushroom Biomes either.
![2023-01-18_16 45 52](https://user-images.githubusercontent.com/122584385/213302280-79531358-903a-4a52-8039-90c522b1e898.png)
![2023-01-18_16 46 53](https://user-images.githubusercontent.com/122584385/213302284-f02840b0-1a0b-4bff-8677-f6bc9be82398.png)

**Comment by CreativeMD** [comment]
Released a new version which adds a wind sound to ice spikes. However I have no clue what sound would suit the mushroom. Do you have any suggestions?

Also sorry that it took me so long to actually respond.

**Comment by NPlaysMC** [comment]
I think I have an idea for the mushroom biome actually; how about a very subtle, melodic electrical pinging and humming? Mushrooms can actually send electrical signals to each other, and these can be detected by metal cables hooked up to soundboards; here's a video showing what that sounds like: [](https://www.youtube.com/watch?v=J-nIBA0V_No)

**Comment by CreativeMD** [comment]
Finally fixed in the newest version. Took me quite long. Hope you look the result. If not open a new issue and let me know what you think could be improved.
