### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by FranzJacobi2000** [CreativeMD/AmbientSounds#156]
Hi, Im playing on Forge 1.19.2, creative core and ambient sounds show up in the loaded mod menu, however no ambient sounds can be heard in-game. 
Do you have an idea why?

**Comment by FranzJacobi2000** [comment]
I got it to work, the problem seems VolumeFade and Pitch Fade not resetting to default. What is the default value you recommend?

**Comment by FranzJacobi2000** [comment]
Seems to be 0.005, however the value disappears after entering it. I would recommend to add a list of standard values and their use to the mod description.

**Comment by CreativeMD** [comment]
I don't know how this happens ... but sometimes the config resets to zero. Use the command /cmdclientconfig and reset fadeVolume and fadePitch. Seems like you figured it out before I could respond. If you have any way to reproduce this weird behavior in the config I would highly appreciate it.
