### ISSUE TITLE
Compatibility with vanilla resource packs

### ISSUE THREAD

**Issue by dranorter** [CreativeMD/AmbientSounds#157]
I have a resource pack which adds extra music to the game, using "minecraft:music.game". It works without the mod, but when I add AmbientSounds in, I just get the vanilla music. Should I be trying to add the extra music inside the sound engine instead?

Extra question: Is there a way within the sound engine to add music that only plays at night, in dark caves, in deserts/desolate biomes, etc? Ideally the extra music would be on top of the ambient sounds.

**Comment by dranorter** [comment]
Ah, sorry to be a bother, I have no idea what I was doing in my testing earlier but your mod works fine with the resource pack in question. And I'm pretty sure my 'extra question' is irrelevant since this mod apparently doesn't touch the music system.

**Comment by CreativeMD** [comment]
This mod does not have to do anything with music, so yeah there is unfortunately no way to add it. Might be worth a new mod AmbientMusic. Glad you could fix it.
