### ISSUE TITLE
Crash caused by tropical fish ambient sound

### ISSUE THREAD

**Issue by sherpascott** [CreativeMD/AmbientSounds#158]
The error that crashed the world read [04:00:57] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.tropical_fish.ambient
Here's the log:
[latest.log](https://github.com/CreativeMD/AmbientSounds/files/10540780/latest.log)

**Comment by CreativeMD** [comment]
This is not related to AmbientSounds, maybe not all game assets are properly downloaded or it might be the mod extrasounds.
