### ISSUE TITLE
Lag spikes upon seeing player

### ISSUE THREAD

**Issue by Permanently** [CreativeMD/AmbientSounds#159]
When AmbientSounds is enabled, everything works fine... until you see another player. Whenever a player is render, the game goes **unbelievably** laggy, dropping to about 5 FPS.

If needed:
Java 17 version: `17.0.5.8 64x`
Minecraft version: `1.19.3`
Fabric version: `0.14.13`
[Mod list](https://criminal.host/b0bdrnqq1xo4.png)

**Comment by CreativeMD** [comment]
And this does not happen without AmbientSounds installed?

**Comment by Permanently** [comment]
Correct.

**Comment by CreativeMD** [comment]
Does it happen with only AmbientSounds and CreativeCore installed? I need more information. What version of AmbientSounds are you using? Do you have enough RAM assigned? Maybe use /ambient-debug to see what is going (maybe a large number of sounds are playing for some reason)?

**Comment by Permanently** [comment]
As soon as I submitted this ticket, the issue stopped, hence why I've not responded as I've been waiting to see whether it'd happen again. It's just one of those classic TV moments where you show something to someone just as it stops.

I'll update this ticket if it happens again, and I'll make sure to clip it.
