### ISSUE TITLE
Throwing me off the server (NPE)

### ISSUE THREAD

**Issue by Raycoms** [CreativeMD/AmbientSounds#16]
Everytime I join our server I get this one here:

> [B#353]  Exception in thread "Thread-581" [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
> [B#353]  [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.jcraft.jorbis.Block.<init>(Block.java:55)
> [B#353]  [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:252)
> [B#353]  [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:687)
> [B#353]  [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at paulscode.sound.Source.stream(Source.java:928)
> [B#353]  [01:18:33] [Thread-581/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at paulscode.sound.StreamThread.run(StreamThread.java:129)

Besides that my log is full of:

> [B#353]  [01:26:15] [Thread-1067/ERROR]: Error in class 'LibraryLWJGLOpenAL'
> [B#353]  [01:26:15] [Thread-1067/ERROR]: Source '3fe6147b-39e9-49ba-bbea-8905e9a3b05b' not found in method 'play'

Not sure if that is related though.

Minecraft version 1.12.2

Newest forge, newest ambientSounds.

**Comment by CreativeMD** [comment]
Could try out this version and see if it fixed?
https://www.dropbox.com/s/byivvu6cdtsfj03/AmbientSounds%20v2.1.1%20mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
This issue will be closed due to inactivity.
