### ISSUE TITLE
Rough transition for bird sound 

### ISSUE THREAD

**Issue by panda-of-trash** [CreativeMD/AmbientSounds#160]
Hi,

Seems like bird-ambience-huge3.ogg in particular seems to have a very rough transition when switching to other sounds or none at all. It's a little jarring and changing the fade volume in the config doesn't seem to help.

Here's an example: https://youtu.be/cucVwYzonK0

**Comment by CreativeMD** [comment]
I cannot tell what version you are using due to the overlapping text. So what version of AmbientSounds are you using?

**Comment by panda-of-trash** [comment]
v5.2.13 for 1.19.2 for Fabric

**Comment by CreativeMD** [comment]
This issue has been fixed. I have uploaded a new version, but for 1.19.3. I do not support 1.19.2 anymore sorry. I hope you can update. Thank you so much for your high quality report. It was very easy for me to figure out the issue!
