### ISSUE TITLE
Biomes and dimensions settings are obsolete

### ISSUE THREAD

**Issue by 0Navis0** [CreativeMD/AmbientSounds#161]
I realized that the biome and dimension settings were completely obsolete, and hasn't changed much since the initial biomes list that I had made, causing some sound issues on recent Minecraft versions with modded biomes. 

The dimension list need a huge cleanup, so far only Twilight Forest updated to 1.19, all the others (AbyssalCraft, Betweenlands, Midnight, Galacticraft) should be removed. 

The biome list also need to be redone, most of the biomes have been changed or removed. I can remake a biome list ordered by type like I had done before. But a better and easier solution would be to use biome tags.

**Comment by CreativeMD** [comment]
Sorry that I did not respond earlier. Yes the list are outdated or let's say only changed to work with 1.19. There is probably a lot of unused stuff.

I did not know biomes tags were a thing. That is obviously a very good way to do things. But I'm not sure when I will have the time. If you want to help out I can add support for tags, so you can change the existing configuration to actually use it. Let me know what you think.

**Comment by CreativeMD** [comment]
I have looked into it. They have some benefits, but also plenty of downsides. I will stick to the naming scheme for now.
