### ISSUE TITLE
[1.19.3] Rain in desert

### ISSUE THREAD

**Issue by cjtganzon** [CreativeMD/AmbientSounds#162]
Hi! I have version 5.2.17 on 1.19.3 Quilt and I have rain in the desert.
![image](https://user-images.githubusercontent.com/62964779/218295332-cb1c7ad8-c2b6-4882-b11a-ff52e33d5817.png)

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. AmbientSounds will undergo some changes, not sure when I will get to it, but I will definitely fix this issue as well.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry that it took me so long.
