### ISSUE TITLE
Ambient Sounds 5 Fabric wont work with appropriate Creative Core version 

### ISSUE THREAD

**Issue by Muloom** [CreativeMD/AmbientSounds#163]
I was trying to set up some mods and I can't for the life of me figure out how to get around this if it's something on my end.
Forge tells me it keeps crashing because Creative Core is not installed for Ambient Sounds 5, but I have it installed.
This is all for 1.19.3 Fabric, and my Ambient Sounds 5 is V5.2.14 with Creative Core V2,10.4 both for Fabric and 1.19.3

**Comment by Muloom** [comment]
Tried it with Ambient Sounds 5 Fabric V5.2.14 to the same result

**Comment by CreativeMD** [comment]
Is it fixed now?
