### ISSUE TITLE
No AmbientSounds Sound

### ISSUE THREAD

**Issue by adiac** [CreativeMD/AmbientSounds#164]
+ Running Minecraft 1.19.3
+ I don't hear any of the mods sounds. The rest of the game sounds are fine.
+ `/ambient-debug` shows that sounds should be playing (see screenshot 1)
+ On world creation, the datapack selection shows that ambientsounds is incompatible. (see screenshot 2)
+ I also run the latest optifine version with shaders for 1.19.3

Please state if you need any additional information oder log files.

Screenshot 1:
![Screenshot 2023-03-18 223136](https://user-images.githubusercontent.com/4075780/226141374-94e46f51-f6c3-4191-ba57-30f9e53dfd84.png)

Screenshot 2:
![Screenshot 2023-03-18 223224](https://user-images.githubusercontent.com/4075780/226141380-9e8cc71e-4e51-4dfa-9d88-c399c1b79d66.png)

**Comment by CreativeMD** [comment]
Use the command /cmdclientconfig and reset the values for fadePitch and fadeVolume.

**Comment by adiac** [comment]
The `r` reset button in the cmdclientfonfig does nothing for these two option. (Tho for silent-dimensions it works)

I've set it to `1` and now I can hear sounds. Is `1` the default value? I wonder why it was set to `0` for me.

**Comment by CreativeMD** [comment]
Are you using Forge or Fabric? Default value is `0.005`.

**Comment by adiac** [comment]
Forge.

**Comment by CreativeMD** [comment]
What version of CreativeCore and AmbientSounds are you using then?

**Comment by adiac** [comment]
`CreativeCore_FORGE_v2.10.7_mc1.19.3`
`AmbientSounds_FORGE_v5.2.17_mc1.19.3`

**Comment by CreativeMD** [comment]
Can you send me your config file `ambientsounds-client.json`?

**Comment by adiac** [comment]
Sure. I noticed even tho the pitch seems to be correct in the file, the ingame menu for it still seems buggy.

`ambientsounds-client.json`
```
{
  "general": {
    "engines": 0,
    "volume": 1,
    "useSoundMasterSource": false,
    "scanStepAmount": 100
  },
  "dimensions": {
    "nether": 1,
    "end": 1,
    "abyssalcraft": 1,
    "void": 1,
    "twilightforest": 1,
    "betweenlands": 1,
    "cave": 1,
    "midnight": 1,
    "galacticraft": 1,
    "galacticraft.planets": 1,
    "surface": 1
  },
  "regions": {
    "suspense": {
      "overall": 1,
      "nether": 1
    },
    "unknown": {
      "overall": 1,
      "suspense": 1
    },
    "dark": {
      "overall": 1,
      "suspense": 1
    },
    "deep": {
      "overall": 1
    },
    "wind": {
      "overall": 1,
      "wind": 1
    },
    "underwater": {
      "overall": 1,
      "underwater": 1,
      "underwater-deep": 1
    },
    "rain": {
      "overall": 1,
      "rain": 1
    },
    "storm_close": {
      "overall": 1,
      "storm-close": 1,
      "wind": 1
    },
    "storm_away": {
      "overall": 1,
      "storm-away": 1,
      "howling-wind": 1
    },
    "underworld": {
      "overall": 1,
      "underworld": 1
    },
    "cave": {
      "overall": 1
    },
    "cave_ambience": {
      "overall": 1,
      "cave": 1,
      "cave-water": 1,
      "cave-deep": 1,
      "cave-large": 1
    },
    "cave_deep-dark": {
      "overall": 1,
      "deep-dark": 1,
      "water-droplets": 1
    },
    "cave_lush": {
      "overall": 1,
      "cave-lush": 1,
      "frog": 1
    },
    "surface": {
      "overall": 1
    },
    "sky": {
      "overall": 1,
      "light-wind": 1
    },
    "space": {
      "overall": 1
    },
    "forest": {
      "overall": 1,
      "bird-ambience": 1,
      "owl": 1
    },
    "forest_cold": {
      "overall": 1,
      "crow": 1
    },
    "taiga": {
      "overall": 1,
      "bird-ambience-huge": 1
    },
    "highland": {
      "overall": 1,
      "heavy-wind": 1,
      "wind-in-leaves": 1
    },
    "mesa": {
      "overall": 1,
      "wind-mesa": 1
    },
    "forest_roofed": {
      "overall": 1,
      "bird-ambience-spooky": 1
    },
    "grass": {
      "overall": 1,
      "cricket": 1,
      "cricket-night": 1,
      "cicadas-night": 1
    },
    "plains": {
      "overall": 1,
      "cricket": 1,
      "cricket-night": 1,
      "cicadas-night": 1
    },
    "savanna": {
      "overall": 1,
      "cricket": 1,
      "cicadas": 1,
      "cicadas-desert": 1,
      "cricket-warm-night": 1,
      "wolf": 1,
      "bird-warm": 1
    },
    "desert": {
      "overall": 1,
      "cicadas-desert": 1,
      "light-wind": 1
    },
    "swamp": {
      "overall": 1,
      "cricket-swamp": 1,
      "cricket-warm-night": 1,
      "frog": 1
    },
    "jungle": {
      "overall": 1,
      "cricket-jungle": 1,
      "cricket-jungle-night": 1,
      "bird-ambience-jungle": 1,
      "bird-ambience-jungle-night": 1
    },
    "cold": {
      "overall": 1,
      "light-wind": 1
    },
    "very_cold": {
      "overall": 1,
      "heavy-wind": 1
    },
    "beach": {
      "overall": 1,
      "beach": 1,
      "seagull": 1,
      "seagull-long": 1
    },
    "ocean": {
      "overall": 1,
      "ocean": 1,
      "light-wind": 1
    }
  },
  "fade-volume": 0.005,
  "fade-pitch": 0.005,
  "silent-dimensions": []
}
```

**Comment by CreativeMD** [comment]
The file has the right configuration, how is that even possible? Can you restart your computer and test it again?

Does the reset button not work?

**Comment by adiac** [comment]
What exactly should I test? The sounds are working fine. It's just the menu of the cmdclientfonfig  that's buggy.

**Comment by CreativeMD** [comment]
Yeah, but I do not know why, maybe you can send me your log file? I have seen this issue multiple times already, but I could never reproduce it.

**Comment by adiac** [comment]
Okay. I did the following:

- Restarted my computer
- Started Minecraft and Loaded into a world
- No Ambient Sound. The cmdclientconfig menu display both  `fadePitch` and `fadeVolume` with values of `0`
- Set a value of `0.005` manually in the config file. 
- Run '/ambient-reload`. Ambient Sound works. The cmdclientconfig menu entries are now just blank, no value shown.
- I press reset and save the settings. No Ambient Sound. 
- The config file is set to `0` again.
- Set a value of `0.005` in the cmdclientconfig menu. The reset button changes it's color. I hit save. Ambient Sound works.

So I would guess the entriy fields in the cmdclientconfig menu don't like the decimals and expects an int maybe?

[debug.log](https://github.com/CreativeMD/AmbientSounds/files/11027817/debug.log)
[latest.log](https://github.com/CreativeMD/AmbientSounds/files/11027818/latest.log)

**Comment by CreativeMD** [comment]
Still cannot reproduce this issue. Config works just fine for me. Is it possible for you to upload your entire .minecraft folder (except of the resourcepack, shaderpacks and saves obviously)? I could also send you a link where you can upload it if you have no place to upload it to.

**Comment by ObservantOskar** [comment]
I had the same problem, and the solution worked, so i am guessing it is the same problem causing it

**Comment by adiac** [comment]
Sorry for the late replay. I did catch a cold.

I can provide you with my .minecraft folder. Are there any other files which I should omit for security reasons?

**Comment by CreativeMD** [comment]
Not really, but you can skip resourcepacks, shaderpacks and saves.

**Comment by vico93** [comment]
I had a very similar issue when i tested this mod for the first time and them removed temporally to test other thing. Next time i installed again it basically refused to work anymore. I removed `ambientsounds-client.json` from config and it then worked. Strange.

EDIT: Ah, and seems like a resource reload (F3+T) seems to mute the sounds as well. Realized this because i was trying to make the mod change the ambience since i left a cave and went back to surface and the cave ambience sounds were still playing a minute after i left.

**Comment by CreativeMD** [comment]
@vico93 interesting 🤔. I have tested it in 1.19.4 for both forge and fabric and could not reproduce this behavior. The resource reload did not affect the settings at all. What version are you using?

**Comment by vico93** [comment]
> @vico93 interesting 🤔. I have tested it in 1.19.4 for both forge and fabric and could not reproduce this behavior. The resource reload did not affect the settings at all. What version are you using?

Got AmbientSounds v5.2.18 and CreativeCore v2.10.7, Fabric Loader 0.14.19 for 1.19.4 and Fabric API 0.79.0

**Comment by CreativeMD** [comment]
> Got AmbientSounds v5.2.18 and CreativeCore v2.10.7, Fabric Loader 0.14.19 for 1.19.4 and Fabric API 0.79.0

I have used the same versions and it worked just fine.
So every time you reload the resource (using F3 + T) the issue does appear?

**Comment by vico93** [comment]
Yep. Last time i used AmbientSounds doing F3+T shut the whole ambience off.

**Comment by CreativeMD** [comment]
No other mods installed? I'm so confused ... it works all fine for me. Can you try to repeat it once more (maybe record a video if possible)?

**Comment by vico93** [comment]
If you have interest, i can send to you my profile folder (the one with mods, configs, etc) to you test. I was using temporarily [Mambience](https://modrinth.com/mod/mambience) but removed that and switch back to AmbientSounds to reproduce the issue, and that still happens.

**Comment by CreativeMD** [comment]
Yeah would be great as well!

**Comment by vico93** [comment]
Did you have Discord? I can send the link from there

**Comment by CreativeMD** [comment]
Yes, you can our server and dm me directly: https://discord.gg/W9QM3fS

**Comment by vico93** [comment]
Just sent you a DM!

**Comment by CreativeMD** [comment]
Thanks to @vico93 this issue has been solved. It was cost by regional number formats, which caused the config to corrupt once the gui was opened once. The newest version of CreativeCore fixes. Thank you all for helping out to fix this annoying issue.
