### ISSUE TITLE
AmbientSounds crashing the client

### ISSUE THREAD

**Issue by HenrikoMagnifico** [CreativeMD/AmbientSounds#165]
AmbientSounds crashes the client for some reason whenever a terraformer is used on a large area. Crash log has been attached!
[crash-2023-03-20_10.51.14-client.txt](https://github.com/CreativeMD/AmbientSounds/files/11016409/crash-2023-03-20_10.51.14-client.txt)

**Comment by CreativeMD** [comment]
That is a weird issue. Can you try to install CreativeCore and AmbientSounds only and see if it still crashes? I also highly recommend to update to 1.19.4 if you can, because I have dropped support for 1.19.2 already.

**Comment by CreativeMD** [comment]
I will close this issue for now due to inactivity.
