### ISSUE TITLE
Null Crash with 1.18.2 Ambient Sounds

### ISSUE THREAD

**Issue by MelrikBirchJr** [CreativeMD/AmbientSounds#166]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because "this.f_10203_" is null
with
AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar
[1.18.2]+SecurityCraft+v1.9.6.jar
ChanceCubes-1.18.2-5.0.2.483.jar
ChunkAnimator-1.18.2-1.3.4.jar
illuminations-forge-1.18.2-1.10.2.19.jar
MorePlayerModels-1.18.2.20220801.jar
OptiFine_1.18.2_HD_U_H7.jar
physics-mod-2.11.10-mc-1.18.2-forge.jar

**Comment by CreativeMD** [comment]
You need to install CreativeCore as well.

**Comment by MelrikBirchJr** [comment]
I did have it afterwards and it was still crashing

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CreativeMD** [comment]
Then I need the new crash-report.
