### ISSUE TITLE
Ambient Sounds crashing fabric :(

### ISSUE THREAD

**Issue by power2220** [CreativeMD/AmbientSounds#167]
https://pastebin.com/jq3pZQGJ

**Comment by CreativeMD** [comment]
I cannot see anything obvious. Can you try to only install fabric and ambientsounds and see if it works. If yes add back in your installed mods to see which mod is causing the issue,

**Comment by okyooo** [comment]
Same issue with me, i've done the this exactly (removing all my mods except ambientsounds, CreativeCore and fabric) same issue. However, this only happens when joining servers, singleplayer does fine.

**Comment by CreativeMD** [comment]
I have released a potential fix. Can you download the newest version of AmbientSounds and see if the issue has been fixed?

**Comment by okyooo** [comment]
seems to have worked, no longer crashing when logging into servers, I can try to get it to happen again and send bug reports or something. I'll let you know.

**Comment by CreativeMD** [comment]
Ok, I will close the issue for now. If it occurs again post the necessary information here and I will reopen the issue.
