### ISSUE TITLE
Cannot Hear Sounds w/ Mod

### ISSUE THREAD

**Issue by jabitti** [CreativeMD/AmbientSounds#17]
When I load up the game without AmbientSounds, my sounds work just fine, but when I use either version that supports 1.12.2, there are absolutely no sounds. I checked the sound settings and they are definitely still on. Any fix?

**Comment by CreativeMD** [comment]
Ok? Could you solve it?

**Comment by jabitti** [comment]
Turns out it was a game of chance getting sounds to load. I'm still unsure of why it works only half of the time. Because it wouldn't work repeatedly with this mod, I made this. Sorry, it's not this mod!
