### ISSUE TITLE
Sounds for biomes don't play when no default trees are present

### ISSUE THREAD

**Issue by wackiestwow** [CreativeMD/AmbientSounds#170]
Hi, I really like using this mod, but there's one thing that bugs me, and that is the sounds normally played in the forest biomes do not play when in an area where there aren't any default Minecraft trees. This is a problem since using almost any maps with custom environments the mod thinks there's no trees where they should be and only block ambience is played.

Here's a photo of where the ambience doesn't work (note the absence of default mc trees in the area and the features menu):

![image](https://user-images.githubusercontent.com/95980287/236490092-0d38c56f-497b-48af-b7fe-481892edb5a8.png)

Here's a situation where it does work, when minecraft trees are present:

![image](https://user-images.githubusercontent.com/95980287/236490291-9343d522-8cbd-4b21-84a4-dd7845f314bb.png)

is there a setting I am unaware of that removes this sound condition?

**Comment by CreativeMD** [comment]
Can you send me your world file? That way I could figure out why it does not detect any trees.

**Comment by wackiestwow** [comment]
here it is:, it is a custom worldpainter map that uses custom trees for selected biomes. If you need to go in creative just open to LAN for a bit:
https://www.mediafire.com/file/ip091l7konyvt5a/redwood_island.zip/file

what could be a potential solution is that the sounds could be played if leaves are present in the player's surroundings instead of having to detect trees themselves

**Comment by CreativeMD** [comment]
[All_leaves_resourcepack_for_AS5.zip](https://github.com/CreativeMD/AmbientSounds/files/11429031/All_leaves_resourcepack_for_AS5.zip)
AmbientSounds is configured to only search for leaves which are not placed by a player. These custom tree models for WorldPainter do not work naturally, so the leaves are set to be persistent (as if they were placed by a player). Therefore AmbientSounds ignores them. I have created a simple resourcepack which changes this behavior. This should fix your issue.

**Comment by wackiestwow** [comment]
thank you very much!
