### ISSUE TITLE
When playing 1.19.2 it crashes fabric saying it causes issue

### ISSUE THREAD

**Issue by proboielite** [CreativeMD/AmbientSounds#171]

**Comment by CreativeMD** [comment]
I need the crash-report. Otherwise I cannot help out.

**Comment by totchi-lagawi** [comment]
Hi!
I have the same issue. Here is my crash-report (beware, I installed tons of mods).

[crash-2023-06-19_18.46.07-client.txt](https://github.com/CreativeMD/AmbientSounds/files/11790445/crash-2023-06-19_18.46.07-client.txt)

**Comment by CreativeMD** [comment]
This crash does not seem to be related to AmbientSounds but rather `Exordium`. So rather report it to them. I will close this issue for now due to inactivity of the original author.

**Comment by totchi-lagawi** [comment]
Yeah, but I tried without Exordium, and the issue is the same. Without AmbientSounds it works well. It means what it means.

[crash-2023-06-21_16.02.13-server.txt](https://github.com/CreativeMD/AmbientSounds/files/11818553/crash-2023-06-21_16.02.13-server.txt)

**Comment by CreativeMD** [comment]
Maybe try to install only fabric, CreativeCore and AmbientSounds and see if this works.

**Comment by totchi-lagawi** [comment]
Crashed :)

[crash-2023-06-21_16.24.05-client.txt](https://github.com/CreativeMD/AmbientSounds/files/11818753/crash-2023-06-21_16.24.05-client.txt)

**Comment by CreativeMD** [comment]
Can you tell me the exact filenames of CreativeCore and AmbientSounds?

**Comment by totchi-lagawi** [comment]
Oh.. Excuse me, I accidentally took the forge version 😅.
I downloaded it using Prism Launcher, I will report it to them!
Have a good day :)

**Comment by totchi-lagawi** [comment]
Problem already fixed, I got the correct version by updating it.
And excuse me for the disruption 😄.

**Comment by CreativeMD** [comment]
Glad it works now!
