### ISSUE TITLE
Ambience changes with escape menu

### ISSUE THREAD

**Issue by Murdock412k** [CreativeMD/AmbientSounds#172]
Anytime you hit escape and then exit the escape menu, ambient noises change entirely providing a less than natural experience.
Would be nice if sound remained persistent so when the ambient track pauses, it would also resume and not change to a different track.

**Comment by CreativeMD** [comment]
Hey sorry for not responding earlier. This took me way too long. Thanks for reporting this issue! It has been fixed in the newest version. Oh man ... it's been 3 months. Sorry ...
