### ISSUE TITLE
owolib stops sounds from playing[1.19.3]

### ISSUE THREAD

**Issue by Erik9996** [CreativeMD/AmbientSounds#174]
When using owolib in conjunction with this mod, none of the ambient sounds play even though it says they are playing in the debug screen.

**Comment by CreativeMD** [comment]
I think you are running into a known issue. In some regions the config gets corrupted as soon as you open up the config menu of ambientsounds. I highly recommend to update to 1.19.4, it is fixed there. You can also fix it for 1.19.3, by either deleting the config file `config/ambientsounds-client.json` or going to the config screen via the command `/cmdclientconfig` and type in `0.005` for both fade-volume and fade-pitch, but remember as soon as you open the config screen again it will get corrupted (unless if you type in the values manually).

**Comment by Erik9996** [comment]
Yes that was it, thank you
