### ISSUE TITLE
CreativeCore causes game to crash on startup (1.19.2)

### ISSUE THREAD

**Issue by GreenBeanGravy** [CreativeMD/AmbientSounds#176]
No explanation needed, my log is attached. I have already tried downgrading, downloaded from Modrinth.
[crash.txt](https://github.com/CreativeMD/AmbientSounds/files/11672163/crash.txt)

**Comment by GreenBeanGravy** [comment]
Meant to post this on the CreativeCore GitHub page, my bad!

**Comment by CreativeMD** [comment]
Seems like there is an issue with the library `sgui` (https://github.com/Patbox/sgui). It is used by the `Mod Viewer` mod. If you can remove this mod and see if it will work.

**Comment by GreenBeanGravy** [comment]
I got everything working. I removed Mod Viewer and still couldn't start Minecraft unless the Essentials mod was removed for some reason. Thank you!

**Comment by CreativeMD** [comment]
Good to know. Glad you got it working!
