### ISSUE TITLE
`pack.mcmeta` file has unfilled templates on fabric, making it invalid JSON

### ISSUE THREAD

**Issue by lukebemish** [CreativeMD/AmbientSounds#178]
The `pack.mcmeta` file shipped in the fabric versions of this mod has unfilled templates that make in invalid JSON:
```json
{
    "pack": {
        "description": "${mod_id} resources",
        "pack_format": ${resource_pack_format},
        "forge:resource_pack_format": ${resource_pack_format},
        "forge:data_pack_format": ${data_pack_format}
    }
}
```
This can cause side effects, as some tools expect `pack.mcmeta` files to be valid JSON if present.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry for the trouble. I changed it for forge totally forgot about fabric. Things should work now. Thanks for reporting this issue!
