### ISSUE TITLE
[Enhancement] Sea Lanterns

### ISSUE THREAD

**Issue by Pdam67** [CreativeMD/AmbientSounds#180]
Would you think it would be possible to make a client sided mode that makes sea lanterns have a fluorescent light hum and maybe you can toggle it in the modmenu,

The hum can be a sound sort of like this video:

https://www.youtube.com/watch?v=gTEn-Z-V1eI

I don't know it's up to you if you want to as it is your mod but would be appreciated for people like me who can't program java but I think it would be cool, also I don't expect it as i know your mod is mainly focused on the natural sound ambience, which btw sounds amazing.

**Comment by CreativeMD** [comment]
Sorry, but I don't think this is the scope of this mod. Also sorry for responding so late.
You can easily add it yourself using a resourcepack. There are ways to add sounds to ambientsounds. If you are interesting I could help you out. Just respond here. For now I will close this issue.
