### ISSUE TITLE
Wind sound always present, and way too strong, no option to toggle it off either

### ISSUE THREAD

**Issue by Firespecialstar** [CreativeMD/AmbientSounds#185]
Wind is always present, in deep caves too, it's also quite loud (compared to the sorroundings) to the point that it got quite annoying, i tried to find an option that was disabling this continuos wind sound, but because there is none made by the sounding engine, i don't have a way to toggle it off

here's also a video of what is happening, i tried to reduce or completely disable all the sounds in the various biomes and stuff like that.

using the latest version of the mod on fabric (AmbientSounds_FABRIC_v5.2.20_mc1.20.1.jar)

https://github.com/CreativeMD/AmbientSounds/assets/84784885/569acbdb-1b42-4a98-97f7-50caee8adaef

**Comment by CreativeMD** [comment]
Pretty sure the wind is not played by AmbientSounds. It's not listed in the debug view. Any other mods installed which could have something like that?

**Comment by CreativeMD** [comment]
I will close this issue for now as I do not see any connection to AmbientSounds. Feel free to respond here and prove me otherwise.
