### ISSUE TITLE
Patchouli encountered an error during the sided-setup event phase

### ISSUE THREAD

**Issue by HoDoHs** [CreativeMD/AmbientSounds#187]
Here the crash report :

[crash-2023-07-30_11.17.55-fml.txt](https://github.com/CreativeMD/AmbientSounds/files/12208831/crash-2023-07-30_11.17.55-fml.txt)

And logs : 

[latest.log](https://github.com/CreativeMD/AmbientSounds/files/12208833/latest.log)

**Comment by CreativeMD** [comment]
Seems to be an issue of patchouli rather than AmbientSounds. Sorry for responding that late!
