### ISSUE TITLE
i cant install the mod

### ISSUE THREAD

**Issue by jake96587** [CreativeMD/AmbientSounds#188]
i downloaded ambient sounds AND creative core and it still wont work 
![image](https://github.com/CreativeMD/AmbientSounds/assets/142698706/03d0cafc-4c64-4298-b705-cb44394720ff)

**Comment by CreativeMD** [comment]
I think you CreativeCore version is not for the right minecraft version. Make sure to download the right one. The one you are using is for 1.20 (I doubt that this is the minecraft version you are using).
