### ISSUE TITLE
[enhancement] Fabric season's compatability

### ISSUE THREAD

**Issue by netcore10** [CreativeMD/AmbientSounds#189]
Currently it sounds like its raining when its snowing, i think it'd add to the immersion if winter didn't sound like it was raining all the time due to it overwriting all biome weather.

**Comment by CreativeMD** [comment]
In theory this should work automatically if they change the method `Biome.getBaseTemperature()`. I have looked through the source I do not know why this does not work, maybe report the issue to them and link it here? I will join and we might be able to figure out a solution.

**Comment by netcore10** [comment]
i forgot to mention it's 1.19.2, did they fix it in newer versions? If so, that's a bummer.

**Comment by CreativeMD** [comment]
Actually I do not. Can you test it for 1.20? If it works we know what is going wrong, if it does not work we need to solve this problem in general.

**Comment by netcore10** [comment]
Yeah this doesn't happen in 1.20, so i assume it's just stuck on 1.19.2 - sadly i'm stuck on that version due to mod choices, so i suppose i'll just have to deal. I assume backporting isn't particularly an option.

**Comment by CreativeMD** [comment]
You could report it to them, maybe they still support 1.19.2. I do not support 1.19.2 anymore and I cannot fix it from my end either. Will close this issue. Sorry ... hope they can fix it or you can update eventually.
