### ISSUE TITLE
Sounds does not fade immediately when teleport to other place

### ISSUE THREAD

**Issue by uhloin** [CreativeMD/AmbientSounds#190]
For example if teleport with Waystones mod from overworld forest to nether or to end, there is some time when sound of birds mixed with sound of portal or end

**Comment by CreativeMD** [comment]
What version of Minecraft are you using?

**Comment by uhloin** [comment]
minecraft 1.20.1
neoforge 47.1.76
AmbientSounds_FORGE_v5.2.22_mc1.20.1.jar 
waystones-forge-1.20-14.0.2.jar

**Comment by CreativeMD** [comment]
Sorry, completely forgot to respond here. I think this behavior is pretty normal. AmbientSounds needs time to adapt. It only changes every 5 seconds (or something like that) for the surroundings. This is done to save performance. You can change it inside `engine.json` but I do not recommend it.
