### ISSUE TITLE
Add Fabric API dependency for Fabric releases on CF and MR 

### ISSUE THREAD

**Issue by Poopooracoocoo** [CreativeMD/AmbientSounds#194]
This matches your fabric.mod.json. This makes it so that any whenever the Fabric version of mod is installed in a launcher that supports downloading dependencies, such as the CurseForge App and Modrinth App, the Fabric API will be installed.

**Comment by CreativeMD** [comment]
I have automated the upload to curseforge and modrinth. From here on fabric dependency will be correctly defined. Thanks for reporting this issue!
