### ISSUE TITLE
Can't use SilentDimensions config

### ISSUE THREAD

**Issue by Crazydude323** [CreativeMD/AmbientSounds#197]
Trying to use the silent-dimensions config to silence AmbientSounds in AE2's spatial storage dimension, but after adding spatial_storage into the brackets in the config, I get the error below. Attempting to load into the dimension causes the game to crash.

![AmbientConfig Issue](https://github.com/CreativeMD/AmbientSounds/assets/60992786/4f5243b9-0d65-4c11-a9c3-265d2347450f)

**Comment by Crazydude323** [comment]
Scratch that, it appears to crash while having any config file at all? Very strange. This is on Fabric, for the record.

**Comment by CreativeMD** [comment]
Update CreativeCore this issue got fixed.
