### ISSUE TITLE
Sounds playing in incorrect locations

### ISSUE THREAD

**Issue by SireOfTheQuags** [CreativeMD/AmbientSounds#198]
If you're inside of a room with a bunch of cave vines around it will start playing cave sounds despite being nowhere near a cave.

**Comment by CreativeMD** [comment]
Use the command /ambient-debug. Make a few screenshots of the situation, then I might be able to figure out how the engine can be tweaked.

**Comment by SireOfTheQuags** [comment]
![2023-11-10_22 08 50](https://github.com/CreativeMD/AmbientSounds/assets/138568126/e68981b1-31c2-486c-91cc-fdf5d4429b54)
![2023-11-10_22 08 54](https://github.com/CreativeMD/AmbientSounds/assets/138568126/7e67f5b6-5ea2-4c58-9cc6-a6b77e9a2f03)
![2023-11-10_22 08 31](https://github.com/CreativeMD/AmbientSounds/assets/138568126/0bfb09c2-f302-4c3f-9afd-72529d8a0c68)

**Comment by CreativeMD** [comment]
Fixed in the newest version of AmbientSounds. If the issue still persists make sure to report it back here.

**Comment by SireOfTheQuags** [comment]
Issue persists. I'll give you a link to where you can download the map so you can test it out for yourself. https://jeracraft.gumroad.com/l/bxjows?layout=profile

Btw the map is made by a very big Minecraft youtuber so you can be sure it's virus free. The issue happens inside the house. near the bottom. The map is free btw. You just have to select 0 euro at the price.
