### ISSUE TITLE
MC 1.20.1 crash

### ISSUE THREAD

**Issue by OysterStew** [CreativeMD/AmbientSounds#199]
Using AmbientSounds_FORGE_v5.3.0_mc1.20.1 and CreativeCore_FORGE_v2.11.8_mc1.20.1 crashes right before menu load.

[crash-2023-11-09_20.46.11-client.txt](https://github.com/CreativeMD/AmbientSounds/files/13314449/crash-2023-11-09_20.46.11-client.txt)

[latest.log](https://github.com/CreativeMD/AmbientSounds/files/13314453/latest.log)

**Comment by PlayfulPiano** [comment]
[crash-2023-11-09_21.29.07-client.txt](https://github.com/CreativeMD/AmbientSounds/files/13314690/crash-2023-11-09_21.29.07-client.txt)

can also confirm i'm getting a similar crash on the new update, too.

**Comment by PlayfulPiano** [comment]
also just noticed that there's a new version of creativecore (v.9) but it still crashes with that as well
[crash-2023-11-09_21.40.10-client.txt](https://github.com/CreativeMD/AmbientSounds/files/13314734/crash-2023-11-09_21.40.10-client.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for reporting this issue! Hope everything works fine now.

**Comment by PlayfulPiano** [comment]
Yep it seems that the latest patch fixed it, thanks!
