### ISSUE TITLE
Unexpected error - Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#20]
My game is crashing when I put ambient sounds in the mods folder (it happens with latest version too).
Every piece of info should be contained in the following log:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
>   DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
>   SoundFixPatchingLoader (AmbientSounds v2.2.1 mc1.12.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // Oh - I know what I did wrong!
> 
> Time: 12/18/17 2:41 PM
> Description: Unexpected error
> 
> net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: java.lang.NullPointerException
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:144)
> 	at com.creativemd.ambientsounds.AmbientSoundEngine.tick(AmbientSoundEngine.java:78)
> 	at com.creativemd.ambientsounds.TickHandler.onTick(TickHandler.java:153)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_TickHandler_onTick_ClientTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.NullPointerException
> 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
> 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
> 	at java.lang.reflect.Field.get(Field.java:387)
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:140)
> 	... 16 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 482703584 bytes (460 MB) / 1023410176 bytes (976 MB) up to 2147483648 bytes (2048 MB)
> 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C6 16 mods loaded, 16 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State  | ID                | Version       | Source                                      | Signature                                |
> 	|:------ |:----------------- |:------------- |:------------------------------------------- |:---------------------------------------- |
> 	| UCHIJA | minecraft         | 1.12.2        | minecraft.jar                               | None                                     |
> 	| UCHIJA | mcp               | 9.42          | minecraft.jar                               | None                                     |
> 	| UCHIJA | FML               | 8.0.99.99     | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJA | forge             | 14.23.1.2555  | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJA | mercurius_updater | 1.0           | MercuriusUpdater-1.12.2.jar                 | None                                     |
> 	| UCHIJA | ambientsounds     | 2.0.0         | AmbientSounds v2.2.1 mc1.12.2.jar           | None                                     |
> 	| UCHIJA | appleskin         | 1.0.9         | AppleSkin-mc1.12-1.0.9.jar                  | None                                     |
> 	| UCHIJA | betterfoliage     | 2.1.10        | BetterFoliage-MC1.12-2.1.10.jar             | None                                     |
> 	| UCHIJA | dsurround         | 3.4.7.2       | DynamicSurroundings-1.12.2-3.4.7.2.jar      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
> 	| UCHIJA | presets           | 3.4.7.2       | DynamicSurroundings-1.12.2-3.4.7.2.jar      | None                                     |
> 	| UCHIJA | lunatriuscore     | 1.2.0.42      | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
> 	| UCHIJA | ingameinfoxml     | 2.8.2.94      | InGameInfoXML-1.12.2-2.8.2.94-universal.jar | None                                     |
> 	| UCHIJA | reauth            | 3.5.2         | ReAuth-3.5.2.jar                            | daba0ec4df71b6da841768c49fb873def208a1e3 |
> 	| UCHIJA | smarthud          | 1.0.4         | smarthud-1.12-1.0.4.jar                     | None                                     |
> 	| UCHIJA | soundfilters      | 0.10_for_1.12 | SoundFilters-0.10_for_1.12.jar              | None                                     |
> 	| UCHIJA | torohealthmod     | 1.12.2-11     | torohealth-1.12.2-11.jar                    | None                                     |
> 
> 	Loaded coremods (and transformers): 
> BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
>   mods.betterfoliage.loader.BetterFoliageTransformer
> DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
>   org.blockartistry.DynSurround.asm.Transformer
> SoundFixPatchingLoader (AmbientSounds v2.2.1 mc1.12.2.jar)
>   com.creativemd.ambientsounds.soundfix.SoundFixTransformer
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
> 	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
> 	LWJGL: 2.9.4
> 	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: custom
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
> 	OptiFine Version: OptiFine_1.12.2_HD_U_C6
> 	Render Distance Chunks: 16
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: Sildurs basic shaders v1.051.zip
> 	OpenGlVersion: 4.6.0 NVIDIA 388.13
> 	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 8

**Comment by CreativeMD** [comment]
Can you try to remove every other mod except of AmbientSounds and see if it crashes as well?
Sorry, I didn't have the time to respond earlier.

**Comment by ghost** [comment]
I can tell this is caused by any other sound-related mod. I'm trying to make this work with SoundPhysics on latest version and I get the same error. At first I thought it was due to the AmbientSounds files being stereo and SoundPhysics needs mono ones so I tried converting them to mono. Still, I couldn't make it work. If I play with AmbientSounds withouht SoundPhysics or vice versa, it works.
EDIT: I attach the crash-report: [crash-2018-01-06_19.47.50-client.txt](https://github.com/CreativeMD/AmbientSounds/files/1609103/crash-2018-01-06_19.47.50-client.txt)

**Comment by CreativeMD** [comment]
I don't think there is anything i can do about it :(
Sorry for not responding earlier.

**Comment by TechnicJelle** [comment]
For me it does work.
I have both mods installed and it works perfectly fine.
For my friend who has the _exact_ same modpack as I do, it doesn't work.

**Comment by Davoleo** [comment]
So did anyone got if this is a low-dedicated-RAM issue or another kind of issue?

**Comment by Davoleo** [comment]
Ok, so I found out this is not a RAM problem, did anyone find out anything here?
tag @CreativeMD 
just because in my modpack someone is having this exact issue... 
[link](https://minecraft.curseforge.com/projects/immersivecraft-mk/issues/5)

**Comment by CreativeMD** [comment]
I could not reproduce it, everything works fine for me (using SoundPhysics alongside AmbientSounds). If somebody has this issue, please send a crash-report, because otherwise it's impossible for me to find out what is causing the issue. So just reopen the issue if it still persists.

**Comment by TechnicJelle** [comment]
[My Skype Received Files.zip](https://github.com/CreativeMD/AmbientSounds/files/2014419/My.Skype.Received.Files.zip)
These are the logs my friend sent me, which include the crash I talked about earlier.

**Comment by CreativeMD** [comment]
Update AmbientSounds and Forge, maybe that fixes the issue?

**Comment by Davoleo** [comment]
mmh so I suppose that has been fixed in the latest version... ?

**Comment by CreativeMD** [comment]
AmbientSounds engine fix has been merged into forge and removed from AmbientSounds itself.

**Comment by Davoleo** [comment]
I see, thanks
