### ISSUE TITLE
Crash before main menu [MC 1.20.1] [Forge 47.2.4]

### ISSUE THREAD

**Issue by Benoxiid** [CreativeMD/AmbientSounds#200]
### Issue
The mod (or CreativeCore) makes the game crash right before main menu, after the forge loading screen completes.

### Steps to reproduce
(Installation done vie curseforge launcher)
1. Create a new custom profile:
   - Minecraft 1.20.1
   - Forge 47.2.4
2. Via "Add content", install AmbientSounds 5
3. Click play, connect and launch
4. The game crashes right before main menu

### Versions used
Minecraft **1.20.1**
Forge **47.2.4** (Also tested, with same issue with **47.2.1**)
AmbientSounds 5 version **5.3.1**
CreativeCore version **2.11.8**

### Logs
- [crash-2023-11-10_15.48.44-client.txt](https://github.com/CreativeMD/AmbientSounds/files/13320640/crash-2023-11-10_15.48.44-client.txt)
- [latest.log](https://github.com/CreativeMD/AmbientSounds/files/13320641/latest.log)

Feel free to contact me for more info
Thank you for your work !

**Comment by Benoxiid** [comment]
### Update
With the same profile, rolling back to AmbientSounds **5.2.24** seems to resolve the issue

**Comment by CreativeMD** [comment]
Update CreativeCore, this will fix your issue.

**Comment by CreativeMD** [comment]
Seems like curseforge is holding back the files. Use modrinth to get the newest version: https://modrinth.com/mod/creativecore
