### ISSUE TITLE
[1.20.2] Is future NeoForge support planned?

### ISSUE THREAD

**Issue by SanteriLoitomaa** [CreativeMD/AmbientSounds#201]
From 1.20.2 onwards NeoForge is no longer the same as Forge and is going to need its own version. This mod will crash Minecraft 1.20.2 immediately if you try to start it with NeoForge.

Failure message: Mod File AmbientSounds_FORGE_v5.2.22_mc1.20.1.jar needs language provider javafml:46 or above to load
		We have found 1.0

Please remove the NeoForge label from your Modrinth/Curse Forge 1.20.2 releases until NeoForge is actually supported.

**Comment by CreativeMD** [comment]
Yeah I will definitely switch to NeoForge, but not at the moment. I might wait for 1.20.3. Not sure when I will get to it. There is a lot of other stuff to do.

The release for 1.20.1 are not compatible with 1.20.2, but there are a few release (outdated once).
