### ISSUE TITLE
Wind sound

### ISSUE THREAD

**Issue by Starlightll** [CreativeMD/AmbientSounds#203]
The loudness of the wind sound becomes unstable when walking up and down the Wooden Slabs in thunder weather
testing in Minecraft fabric 1.20.1 AmbientSounds 5 ver 5.3.5

**Comment by CreativeMD** [comment]
Is it possible for you to record a short video explaining the issue? Or maybe a few screenshots. There is also a debug command which would be quite helpful to have to it enabled for the video or screenshots. Just use the command /ambient-debug. There you can see what sounds are playing.

**Comment by Starlightll** [comment]
Sorry for the delay
I don't understand the values ​​in the debug section, but the sound change is recognizable through the video, here is the video
https://github.com/CreativeMD/AmbientSounds/assets/145125551/093852c8-18d0-466b-9003-3ef6550a6ab2

**Comment by CreativeMD** [comment]
Fixed in the newest version! Thanks for reporting this issue and making it really easy for me to figure out what is going wrong.
