### ISSUE TITLE
Mod causes the internal server to no longer work

### ISSUE THREAD

**Issue by FluffyPuppyKasey** [CreativeMD/AmbientSounds#204]
As stated in the title, AmbientSounds causes Minecraft 1.20.1 (using my Better Adventures++ modpack on Modrinth) to no longer generate chunks and it seems as if the internal server stops working as I cannot pick up blocks, nor do mobs pathfind.

This seems like a very critical bug in the mod, and should be fixed as soon as possible because it has existed for multiple versions now.

It only happens with AmbientSounds enabled and active.

https://mclo.gs/obWf4VG

**Comment by FluffyPuppyKasey** [comment]
Doing some additional testing it seems like it's an incompatibility of sorts with another mod as it doesn't happen with only AmbientSounds (and CreativeCore obviously!), Sodium, and Iris installed

**Comment by FluffyPuppyKasey** [comment]
It appears that Immersive Portals is causing the issue when Ambient Sounds is loaded. The weird part is that it works perfectly fine a good amount of the time. When I first tested Immersive Portals with my pack it worked just fine for hours and hours

**Comment by CreativeMD** [comment]
AmbientSounds and CreativeCore have been developed for fabric and not Quilt. Apparentely Quilt has a few issues, I can only recommend to go back to fabric. I will not provide support for another platform at the moment. Sorry, that I cannot really help you there. Hope you can switch to fabric without any issues.

**Comment by FluffyPuppyKasey** [comment]
It looks like it may have been an issue with Quilt causing the incompatibility between C2ME and AmbientSounds. I switched back to Fabric. I was only using Quilt because of the enhanced crash reports it has (it tells you exactly what mods are causing issues)
