### ISSUE TITLE
Playing seagull sounds should depend on time and weather conditions

### ISSUE THREAD

**Issue by NikolasPpd** [CreativeMD/AmbientSounds#207]
Seagulls are birds that sleep at night so hearing the sound effect in-game during night time is a bit unusual. Where it gets even more unusual is hearing those same SFX during thunderstorms (and maybe just rainy weather).

So maybe playing those sounds only during the day and when the weather is clear would make more sense.

Edit: same thing should apply to any other birds present in other biomes (unless they are nocturnal like owls for example).

**Comment by CreativeMD** [comment]
Fixed in the newest version. It was missing the night property. I will rework when birds can be heard in the next rework. Thanks for bringing this to my attention.
