### ISSUE TITLE
Blacklisting Dimensions

### ISSUE THREAD

**Issue by mahjerion** [CreativeMD/AmbientSounds#208]
MC: 1.20.1
Forge: 47.2.18
AmbientSounds5: 5.3.5

Hi, would it be possible to add a blacklist for mmorpg:dungeon?

I understand this issue was raised before for other dims. Would it be possible to make the list configurable? I guess currently, you need to add these dimensions to your config manually for us to enable/disable.

**Comment by CreativeMD** [comment]
Yes you can. Use the command /cmdclientconfig. There is a option silent dimension, add yours there and it should disable all sounds in that dimension.

**Comment by mahjerion** [comment]
Just to clarify this won't disable ALL sounds but only the ambient sound sounds right?

**Comment by CreativeMD** [comment]
Yes, only sounds from ambientsounds.
