### ISSUE TITLE
Biomes and dimensions settings are obsolete 

### ISSUE THREAD

**Issue by 0Navis0** [CreativeMD/AmbientSounds#209]
This a follow up to this issue: https://github.com/CreativeMD/AmbientSounds/issues/161

The biome and dimension settings are still obsolete, and hasn't changed much since the initial biomes list that I had made, causing some sound issues on recent Minecraft versions with modded biomes.

The dimension list need a huge cleanup, so far only Twilight Forest and the Aether updated to 1.20, all the others (AbyssalCraft, Betweenlands, Midnight...) should be removed.

The biome list also need to be redone, most of the biomes have been changed or removed. I can remake a biome list ordered by type like I had done before.

**Comment by CreativeMD** [comment]
Sure thing. Sorry for not responding earlier. I tend to leave things as they are because most mods update eventually. Would be done for a real cleanup, I will also try to make use of the new biome tags.

**Comment by CreativeMD** [comment]
Added support for biome tags in the newest version. Made use of all biome tags from minecraft. Thanks for suggesting it!
