### ISSUE TITLE
[1.12.2] [Suggestion] Add Matmos Sounds

### ISSUE THREAD

**Issue by Draskh** [CreativeMD/AmbientSounds#21]
Matmos was a similar mod that added sounds to Minecraft. But it was discontinued. The official updates have stopped. You can find information [here](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1274487-matmos-environmental-sound-atmosphere-simulator) and its [Github](https://github.com/Sollace/MAtmos). 
So there are unofficial builds available but not for actual Minecraft versions. I wonder if the some sounds can be used now for AmbientSounds expanding the mod if this is possible.

**Comment by CreativeMD** [comment]
Dynamic Surroundings does it already, might be a good idea to take a look at that mod:
https://minecraft.curseforge.com/projects/dynamic-surroundings

**Comment by Draskh** [comment]
Does it work with AmbientSounds or does it replace it?

**Comment by CreativeMD** [comment]
These mods work fine together since Dynamic Surroundings plays sounds from time to time only.
