### ISSUE TITLE
terralith biomes

### ISSUE THREAD

**Issue by Thefatsparrow** [CreativeMD/AmbientSounds#210]
some biomes in terralith like gravel_desert produce no noise whatsoever 

![image](https://github.com/CreativeMD/AmbientSounds/assets/86117177/5426166b-e1f5-4ee5-98b2-14c9fdf62aed)

**Comment by Thefatsparrow** [comment]
this is the only biome ive noticed no noise in but im sure there are more

**Comment by Thefatsparrow** [comment]
![image](https://github.com/CreativeMD/AmbientSounds/assets/86117177/f0342279-28c8-4bfe-b9fa-2ff6b289e62d)
thats with the debug menu

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue. It was caused by this desert having no sand.
