### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by LunarDev-git** [CreativeMD/AmbientSounds#211]
### Client Details

Modloader: Forge
Forge Version: 47.2.19
MC Version: 1.20.1

### How to reproduce

This is where i'm stumped. Honestly I don't know how it happens, seems random. I tried looking at the crash log to see which mod is responsible and I have no idea. I saw sound engine so thought that it was either this mod or extreme sound muffler but I didn't spot any crash issues on their github nor CF comments 

### Crash Log

[message.txt](https://github.com/CreativeMD/AmbientSounds/files/13927773/message.txt)

**Comment by CreativeMD** [comment]
I doubt that this is related to AmbientSounds. You might get more information if you take a look the log file of this crash.
