### ISSUE TITLE
Twitch copyright strike muted audio with this track

### ISSUE THREAD

**Issue by mcdodge34** [CreativeMD/AmbientSounds#215]
I never expected something like that to happen, since its not music, I didn't see there was a problem with ambientsounds, but apparently twitch think this track was used in your mod, is this something you did, can I appeal to them with any information where your sounds are took from maybe 
They identified this : Deep Sleepy Water Lake Sounds - Sounds of Planet Earth

**Comment by CreativeMD** [comment]
That is weird. I listened to the sound on spotify. It seems like a combination of a few sounds AmbientSound uses. I don't see a way to fix it ... maybe report it to twitch, because this should not be a thing.

**Comment by mcdodge34** [comment]
Yeah did a report and now its fixed, I was like, someone did manage to claim a copyright on some nature sounds. But I'm not surprised, my cousin is a musician (guitar player) basically if you play a suite of random notes, its probably copyrighted, one of his close friend was banned from youtube, and he plays his own compositions, but a big company copyrighted so many notes together that he got too many claims, he had almost 17000k followers and he tried to appeal, but was unsuccessful, it was like David against Goliath.

**Comment by CreativeMD** [comment]
That sounds awful. Glad you could solve it. Hope you will not run into this again! God bless you!
