### ISSUE TITLE
Snowy Area Problem [FABRIC 1.20.6] - UPDATED!

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#223]
In snowy area the mod doesn't work. Other places and caves are working. ↓↓↓
![2024-05-18_20 18 21](https://github.com/CreativeMD/AmbientSounds/assets/75926506/a8c24b87-ed48-4af5-9140-71ae11121e46)
![2024-05-18_20 23 48](https://github.com/CreativeMD/AmbientSounds/assets/75926506/f725b842-0ca5-4e0c-9f1a-3227d93a6d63)

Strangely, it immediately works on the river that is between those two area above in the screenshots, ↓↓↓
![2024-05-18_20 24 32](https://github.com/CreativeMD/AmbientSounds/assets/75926506/2f0f18e5-0091-4751-974b-924593c7c9a0)

Note: On curseforge, there is a version that does not exist on modrinth. That version is,
-AmbientSounds_FABRIC_v6.0.1_mc1.20.6.jar
→with a note "Fixed wind sound collection not working properly"

But when I use that version, mod completely stops working this time. So I use currently this version from modrinth,
-AmbientSounds_FABRIC_v6.0.0_mc1.20.6.jar
 
While testing I only used these mods:
-fabric-loader-0.15.11-1.20.6
-fabric-api-0.97.8+1.20.6
-AmbientSounds_FABRIC_v6.0.0_mc1.20.6
-CreativeCore_FABRIC_v2.11.31_mc1.20.6

My specs (Just a Poor HP Laptop):
-Windows 10 Home (22H2)
-Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (With, Intel HD Graphics 4400)
-8 GB Ram

By the way, I am a lover of your mod. Thank you for everything.

→UPDATE - 26.05.2024 01:01 (UTC/GMT +3)
As you wanted, I screenshoted same positions with  "/ambient-debug" informations, ↓↓↓

Position 1: The mod not works on here.
![2024-05-26_00 56 00](https://github.com/CreativeMD/AmbientSounds/assets/75926506/43abba8b-a359-4f65-b07d-9d17d048be15)

Position 2: The mod not works here too.
![2024-05-26_00 56 35](https://github.com/CreativeMD/AmbientSounds/assets/75926506/fa67f140-8762-4fae-9011-deb1e65c3df8)

Position 3: The mod "immediately" starts working on the river for some reason (wind sound).
![2024-05-26_00 56 21](https://github.com/CreativeMD/AmbientSounds/assets/75926506/e147cd82-5eb6-48c8-9a3e-42b3b2b0c6d0)

Hope this helps, thank you so much for this beautiful mod :)!

**Comment by CreativeMD** [comment]
Can you repeat the screenshots but this time with the debug information from AmbientSound? You can show it using /ambient-debug. This will show me everything I need to know to figure out what is going wrong.

**Comment by ghost** [comment]
> Can you repeat the screenshots but this time with the debug information from AmbientSound? You can show it using /ambient-debug. This will show me everything I need to know to figure out what is going wrong.

Ofcourse, updated the issue with "/ambient-debug" informations. Hope it helps you, :)!

**Comment by CreativeMD** [comment]
Uploaded 6.0.1 to modrinth. Somehow that got lost. The question is why does 6.0.1 not work. I need more information about that. Otherwise I cannot release a fix and i'm not sure if the fix in 6.0.1 already fixes your issue anyway.

**Comment by ghost** [comment]
> Uploaded 6.0.1 to modrinth. Somehow that got lost. The question is why does 6.0.1 not work. I need more information about that. Otherwise I cannot release a fix and i'm not sure if the fix in 6.0.1 already fixes your issue anyway.

Okay, I used recent AmbientSounds v6.0.1 and tested it a little. Opened new Issue for you to check. I'm closing this one.
