### ISSUE TITLE
Suggestion: Allow Customization for Ambiance Triggers

### ISSUE THREAD

**Issue by Scyfinn** [CreativeMD/AmbientSounds#224]
This mod works alright in Spectrum's Deeper Down, but because it doesn't recognize the Crystal Gardens as a lush caves-type biome, the ambiance sounds really dead in the mod's liveliest biome.

I would love to fix it myself, but there is no config option to change what is recognized as a lush caves. My only customization option is to silence all ambiance in the Deeper Down.

Being able to manually assign modded biomes and blocks as triggers for pre-existing ambiance would allow for quicker and easier fixes for issues like these.

**Comment by CreativeMD** [comment]
The engine can be modified via a resourcepack, but if you tell me what blocks should count as being part of a lush caves I can add them by default.

**Comment by CreativeMD** [comment]
Will close this issue due to inactivity. Feel free to respond here anyway.
