### ISSUE TITLE
Sound are not playing in 1.20.1 Forge

### ISSUE THREAD

**Issue by iSeeEthan** [CreativeMD/AmbientSounds#226]
Basically it says they are playing but i cant hear them and my audio is set to 100%. 

https://streamable.com/ttjj4i

**Comment by iSeeEthan** [comment]
Found the mod that was breaking it, only took like 2 hours.


NoCube's Villagers Sell Animals
https://www.curseforge.com/minecraft/mc-mods/villagers-sell-animals

Any idea why it messes with it?

**Comment by CreativeMD** [comment]
Can you use the command /ambient-debug make a screenshot and send it here? That way I can tell if any sounds should be playing. I don't see how AmbientSounds should have any trouble with this mod, but maybe report the issue to them as well. (I also cannot view your video because it is not available anymore).

**Comment by redpanda608** [comment]
Hello, I am having the same issue as iSeeEthan. I do not have the mod they mentioned installed. I do see Ambient Sounds is active with /ambient-debug but I do not hear any sounds. Please see screenshots. One in a cage and another in a forest. Some sounds do work. Like close to the beach I hear sea gulls. But in the cave or in the forest I don't hear any additional sounds like I hear in the Trailor video. https://youtu.be/2Z1QIyxFUas?si=dAbLM6Vl4Oww45Fc
![2024-06-14_11 14 16](https://github.com/CreativeMD/AmbientSounds/assets/10014227/3500c934-61ce-4a7d-b09d-317fb7c39634)
![2024-06-14_11 15 04](https://github.com/CreativeMD/AmbientSounds/assets/10014227/5843a3cf-c69a-432b-8fcd-e32c638516b5)

**Comment by redpanda608** [comment]
{Update} - I have narrowed my issue down to something with my Bluetooth headset. On first boot of the game ambient sounds works, then the first time I open the menu with ESC then close the menu ambient sounds stops. Then if I disconnect my Bluetooth headphones and reconnect them ambient sounds works again until I open the menu with ESC and close it again. I can repeat this process to get ambient sounds working again in a loop. If I turn off my bluetooth ambient sounds works as normal with my laptop speakers.

**Comment by CreativeMD** [comment]
Ok, if I understand it correctly. Every time you pause and then unpause the game the sound is gone?

**Comment by CreativeMD** [comment]
Fixed in the newest version version. Sorry for all the trouble. Thanks for reporting this issue!

**Comment by redpanda608** [comment]
Yes it is fixed in 6.0.2. Thank you!

**Comment by iSeeEthan** [comment]
> Fixed in the newest version version. Sorry for all the trouble. Thanks for reporting this issue!

This also fixed NoCube's Villagers Sell Animals Mod somehow! Thanks!
