### ISSUE TITLE
AmbientSounds v6.0.1 Not Working Properly [FABRIC 1.20.6]

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#228]
The mod is completely not working until you change "environmental sound level" from the game options menu. When you you change the level of the sound and return to the game, the mod starts working immediately. But when you walk and change your region/biome/location, the mod stops working again and not work even if you return to the same place. For it to start again, you need to change volume level again... And another note is, while I'm in snowy area, the mod sometimes picks up sound sometimes not (You can see it on the last 2 screenshots)... "/ambient-debug" informations ↓↓↓

![2024-05-29_02 06 32](https://github.com/CreativeMD/AmbientSounds/assets/75926506/ce499221-80ad-40f4-aa1c-e3a8741ab752)

![2024-05-29_02 06 54](https://github.com/CreativeMD/AmbientSounds/assets/75926506/46bf46b0-3f54-4d54-82df-53f2f7219272)

![2024-05-29_02 07 12](https://github.com/CreativeMD/AmbientSounds/assets/75926506/0ff1c9c5-1d3e-416d-b21d-7256b5be07bf)

![2024-05-29_02 07 28](https://github.com/CreativeMD/AmbientSounds/assets/75926506/4138f12b-177e-4b4c-b097-6d150ffca97c)

![2024-05-29_02 08 16](https://github.com/CreativeMD/AmbientSounds/assets/75926506/812ffe81-8cbc-458a-a259-f7f4bf8fa09c)

While testing I used these mods:
-fabric-loader-0.15.11-1.20.6
-fabric-api-0.97.8+1.20.6
-AmbientSounds_FABRIC_v6.0.1_mc1.20.6
-CreativeCore_FABRIC_v2.11.32_mc1.20.6

**Comment by ghost** [comment]
I'm now currently using "AmbientSounds_FABRIC_v5.3.9_mc1.20.6" and everything works fine for now (Idk, maybe this can be a useful information :D)... I hope, you can fix your updated version of the mod and we can play it :) This mod is amazing.

**Comment by iprefermids** [comment]
I'm also still having this issue on v6.0.1. Have noticed while ambient sounds are broken, music also does not play. I have the same "feature" as you did where adjusting the game sound levels - either ambient or music - fixes the issue temporarily.

Using v5.3.9 now as it fixes the problem.

**Comment by CreativeMD** [comment]
Sorry for responding so late. Can you send me your log file (which contains the session which had this issue)? I currently have no idea what could cause a weird issue like this.

**Comment by ghost** [comment]
> Sorry for responding so late. Can you send me your log file (which contains the session which had this issue)? I currently have no idea what could cause a weird issue like this.

~~I uploaded the log file~~, hope it helps. But, I think it won't help you :D... Really a weird problem. Don't forget ↓
v5.3.9 → Completely works.
v6.0.0 → Only snowy area (wind) sounds are not working.
v6.0.1 → Nothing works, until you touch any sound level (Even a tiny bit.) from the game options menu. And, while on snowy area, the mod is unstable about picking sound or not. So much mess :'D

Good luck my friend! :D

Edit: I tried this, but console says there is no such command... maybe it is because you suggested it for "Forge" Idk... ↓
"Can you use the command /cmdclientconfig and set playSoundWithOffset to false and see if the issue still occurs?"

New Edit: I created new world (default settings) and start playing. Unlike my older saved worlds, the new world start with ambient sounds working. I started on a snow area. I played a little, when I changed my biome, ambient sound stopped. I was on green area. Then I touched sound volume settings and ambient sounds start working again. Then I continue to run, and I come across a "taiga" biome. For some interesting reason, some ambient sounds (Bird and bug noise) continued to work, but some sounds like wind or athmosperic sounds stopped working?... I have tried so many things, but couldn't find any solution... But, 5.3.9 still work like charm! :'D

**Comment by CreativeMD** [comment]
The command should work. That is very weird. The command should work. Can you update CreativeCore and see if that helps. I still have no idea how there can be any difference from 6.0.0 to 6.0.1. For me everything works just fine.

**Comment by Fyoncle** [comment]
> The command should work. That is very weird. The command should work. Can you update CreativeCore and see if that helps. I still have no idea how there can be any difference from 6.0.0 to 6.0.1. For me everything works just fine.

Same issue here, thats just not works at all.

**Comment by CreativeMD** [comment]
Can you try to pause and then unpause the game to see if that causes the sounds to be gone?

**Comment by Fyoncle** [comment]
> Can you try to pause and then unpause the game to see if that causes the sounds to be gone?

I tried many times, it doesn't help, you need to move the slider. (atleast for jukeboxes, i didnt experience a biome sound gone.)

**Comment by CreativeMD** [comment]
Finally figured out the cause of this issue. Fixed it. Thanks a lot of for all your help! Newest version is out and should fix it.

**Comment by Fyoncle** [comment]
> Finally figured out the cause of this issue. Fixed it. Thanks a lot of for all your help! Newest version is out and should fix it.

Thanks!!! ❤️

**Comment by iprefermids** [comment]
> Finally figured out the cause of this issue. Fixed it. Thanks a lot of for all your help! Newest version is out and should fix it.

Appreciate the effort!

**Comment by ghost** [comment]
> Finally figured out the cause of this issue. Fixed it. Thanks a lot of for all your help! Newest version is out and should fix it.

What was the problem? I'm curious terribly :'D

**Comment by Fyoncle** [comment]
> > Finally figured out the cause of this issue. Fixed it. Thanks a lot of for all your help! Newest version is out and should fix it.
> 
> What was the problem? I'm curious terribly :'D

Oh lol, im also curious

Bu arada selamlar :)

**Comment by ghost** [comment]
> > > Finally figured out the cause of this issue. Fixed it. Thanks a lot of for all your help! Newest version is out and should fix it.
> > 
> > 
> > What was the problem? I'm curious terribly :'D
> 
> Oh lol, im also curious
> 
> Bu arada selamlar :)

Selam lar dostum :D, çok uğraştım bu sorunu çözmek için. O yüzden çok merak ediyorum :'D

**Comment by Fyoncle** [comment]
> > > > Finally figured out the cause of this issue. Fixed it. Thanks a lot of for all your help! Newest version is out and should fix it.
> > > 
> > > 
> > > What was the problem? I'm curious terribly :'D
> > 
> > 
> > Oh lol, im also curious
> > Bu arada selamlar :)
> 
> Selam lar dostum :D, çok uğraştım bu sorunu çözmek için. O yüzden çok merak ediyorum :'D

Benimde müzik kutuları çalışmıyordu ondan dolayı bende buradayım, çözümünü öğrenmeyi bende isterim çünkü neden olmasın, GitHub'da release paylaşmadığı için kod değişiklerini göremiyoruz :(

**Comment by CreativeMD** [comment]
I introduced so called sound collections. These collections can be used by various different regions. For example there are a few regions which have the light wind sound. So instead of defining the same set of wind sound for each region, they all use the sound collection. Unfortunately due to an error all of them used the same sound instance. While the sound was active in one region, it was inactive in another. This caused the sound to be queued to play and then immediately being stopped again. The sound engine got spammed with new sounds until it cracked. Only a reset helped. The reason why v6.0.0 worked was that the sound collection for wind had a syntax error. This got fixed in v6.0.1 which made this issue appear more often as for example the desert uses this wind sound.

Hope that explains it for you.

**Comment by Fyoncle** [comment]
> I introduced so called sound collections. These collections can be used by various different regions. For example there are a few regions which have the light wind sound. So instead of defining the same set of wind sound for each region, they all use the sound collection. Unfortunately due to an error all of them used the same sound instance. While the sound was active in one region, it was inactive in another. This caused the sound to be queued to play and then immediately being stopped again. The sound engine got spammed with new sounds until it cracked. Only a reset helped. The reason why v6.0.0 worked was that the sound collection for wind had a syntax error. This got fixed in v6.0.1 which made this issue appear more often as for example the desert uses this wind sound.
> 
> Hope that explains it for you.

This explanation is far from crazy, i like it lol

Thanks for your answer about this, keep up the insane work on your mods ❤️ ❤️
