### ISSUE TITLE
Music Discs do not play until sounds settings touched

### ISSUE THREAD

**Issue by Fiopon** [CreativeMD/AmbientSounds#229]
https://github.com/CreativeMD/AmbientSounds/assets/56209751/845fefdd-0164-4b55-83df-4c9c4d226d1a

**Comment by CreativeMD** [comment]
Thanks for reporting. Seems like a duplicate of: https://github.com/CreativeMD/AmbientSounds/issues/227 

Will the close the issue here and respond in the author issue.
