### ISSUE TITLE
Galacticraft Support/Bug (1.12.2)

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#23]
i hear birds in moon...i hear grasshoppers in mars... xD
can you make a dimension check? it should play only if im in overworld. thanks..
latest GC builds if needed.. https://ci.micdoodle8.com/job/Galacticraft-1.12/?auto_refresh=true

**Comment by ghost** [comment]
actually im asking for a dimension whitelist in configs. it would be very good.

**Comment by CreativeMD** [comment]
Does this resourcepack fix it: https://www.dropbox.com/s/mxyo1022nkd2c6p/Overworld%20only%20-%20AmbientSound%20Addon.zip?dl=1

**Comment by ghost** [comment]
YEAH it does.

**Comment by CreativeMD** [comment]
Nice. Added it to the curseforge page. Thanks for reporting this issue.

**Comment by ghost** [comment]
uhm, can't you make it as a config (dim whitelist in config) instead of a resource pack? it would be more player friendly

**Comment by CreativeMD** [comment]
There are no configuration options for the engine, because you can configure the engine itself. I will add it to my todo list, but can't promise anything soon.
