### ISSUE TITLE
Crash Involving Mod Menu in 1.20.6

### ISSUE THREAD

**Issue by PhoebeJones** [CreativeMD/AmbientSounds#230]
Hi!

I attempted to use AmbientSounds with Mod Menu in 1.20.6 in MultiMC and found a crash. 

The Crash:
Clicking any back button in the AmbientSounds config menu in the Mod menu will cause a crash whether the config was changed or not. This includes the back button to, say, go back from viewing a particular region to the general AmbientSounds config menu or the save button to return to the main Mod menu list. 

The crash report mentions this: Cannot invoke "net.minecraft.class_1657.method_56673()" because the return value of "team.creative.creativecore.common.gui.GuiControl.getPlayer()" is null.

The full crash report is provided.

![Screenshot 2024-06-05 132231](https://github.com/CreativeMD/AmbientSounds/assets/55931760/4e0e502d-56bf-45f7-92f3-efc14596c07a)
![Screenshot 2024-06-05 132217](https://github.com/CreativeMD/AmbientSounds/assets/55931760/7276e4a6-1c6e-4b79-8d01-e19b3dbd21e3)
[Crash Report.txt](https://github.com/user-attachments/files/15596182/Crash.Report.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry for the trouble and thanks a lot for reporting this issue!

**Comment by PhoebeJones** [comment]
Okay. Thank you!
