### ISSUE TITLE
[Bug] Jukeboxes Not Working

### ISSUE THREAD

**Issue by Fyoncle** [CreativeMD/AmbientSounds#233]
Unless you play with volume slider and then come back to game again, music discs will never work on 1.20.1 Fabric

I use Ambient Sounds 6.0.1

Heres how the glitch and fix looks like;

https://github.com/CreativeMD/AmbientSounds/assets/63975256/8c8a59bf-3c3a-4ce6-a505-c46c59060726

**Comment by Fyoncle** [comment]
# Quick note that Ambient Sounds 6.0.0 Works Without Problems.

**Comment by CreativeMD** [comment]
This is a known issue. Discussion is over here: https://github.com/CreativeMD/AmbientSounds/issues/233. I will close this issue as it is a duplicate.

**Comment by Fyoncle** [comment]
> This is a known issue. Discussion is over here: #233. I will close this issue as it is a duplicate.

#233 is my issue lol, what?

**Comment by CreativeMD** [comment]
Oh sorry, linked the wrong one. It is this one here: https://github.com/CreativeMD/AmbientSounds/issues/228
