### ISSUE TITLE
The mod’s jar file contains both `fabric.mod.json` and `neoforge.mods.toml`/`mods.toml`

### ISSUE THREAD

**Issue by 3gf8jv4dv** [CreativeMD/AmbientSounds#236]
As the title says, both Fabric and Neo/Lex variants contain metadata files for the above modloaders inside the jar file. This mod’s dependencies do not have this problem.

On some launchers, this causes the included check mod update functionality to match the wrong variant. For example, in a 1.21 Fabric instance in one launcher, the launcher’s check mod update functionality should match it to the Fabric variant, however, it may actually match it to the NeoForge variant, causing users to be unable to launch the game after updating. One of the reasons for this problem is that the jar file contains metadata files for both Fabric and NeoForge.

Could it be done for this mod since its dependencies only include the corresponding modloader’s metadata files in the corresponding variants?

**Comment by CreativeMD** [comment]
Sorry, but AmbientSound has one codebase for both versions. CreativeCore deals with the loading on different sides. All I could is to delete the files inside the jar when compiling them. But i also do not understand why the launcher needs to the stuff in that way anyway. I mean the launcher should know if a given instance is forge or fabric, right?

**Comment by 3gf8jv4dv** [comment]
Thanks for your reply!

> Sorry, but AmbientSound has one codebase for both versions. CreativeCore deals with the loading on different sides. All I could is to delete the files inside the jar when compiling them.

OK, I understand.

> But i also do not understand why the launcher needs to the stuff in that way anyway. I mean the launcher should know if a given instance is forge or fabric, right?

You are right. I am discussing this with the launcher’s maintainers.

**Comment by CreativeMD** [comment]
Ok, hope this is solved now. If there are any further issues let me know. I will close this issue for now (you can still reply here).
