### ISSUE TITLE
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ambientsounds'!

### ISSUE THREAD

**Issue by 7Peter-bit** [CreativeMD/AmbientSounds#237]
![Screenshot 2024-06-19 200311](https://github.com/CreativeMD/AmbientSounds/assets/173324465/55056ef0-0e85-41bd-b0fe-089ff27112ce)

**Comment by Dinosaurstick** [comment]
what was the solution

**Comment by gagulab** [comment]
what was the solution
