### ISSUE TITLE
Rendering ingredient  java.lang.NullPointerException: Rendering ingredient

### ISSUE THREAD

**Issue by mdatoo** [CreativeMD/AmbientSounds#24]
The game does load into the world successfully, however when I search for the letter 'f' in JEI (survival mode, cheats enabled), it freezes and then crashes. I have tried with a few other letters and it seems fine, however this behaviour may not be limited to just the letter f.
[crash-2018-03-19_21.55.42-client.txt](https://github.com/CreativeMD/AmbientSounds/files/1827120/crash-2018-03-19_21.55.42-client.txt)

EDIT: I have also tested this without AmbientSounds in the mods file (in a newly generated world), and it does not crash. Interestingly, if I load up the world that was generated when AmbientSounds was enabled (despite AmbientSounds not being in the mods folder) this crash still occurs.

**Comment by CreativeMD** [comment]
This doesn't look like an issue of AmbientSounds. You should report the author of Bibliocraft instead, as one of his items crash during rendering. He might be able to fix it.
