### ISSUE TITLE
Port the 1.20.1 version of Ambient Sounds (6.0.3) to 1.20.4 please.

### ISSUE THREAD

**Issue by GroxDots** [CreativeMD/AmbientSounds#240]
If it is possible, could you please port the 1.20.1 version of Ambient Sounds (6.0.3) to 1.20.4 please? A lot of the mods I use (like Better Combat and Leawind's Third Person) do not support any version beyond 1.20.4

**Comment by CreativeMD** [comment]
Sorry but I do not support 1.20.4 anymore. I do not have the time to support all this versions. I can barely respond to all the issues.
