### ISSUE TITLE
Make nighttime sounds play during a solar eclipse in Astrocraft

### ISSUE THREAD

**Issue by vinnyg0621** [CreativeMD/AmbientSounds#241]
mod link here - https://www.curseforge.com/minecraft/mc-mods/astrocraft-mod

**Comment by CreativeMD** [comment]
Problem is that it is not easy. AmbientSounds uses the angle of the sun to detect whether it is day or night. This would need an explicit check whether a solar eclipse is going on. Or maybe I could check for the brightness of the sun? Not sure how this mod works.

**Comment by CreativeMD** [comment]
Sorry, but I will close this issue for now. I don't think this is worth the effort at the moment. Furthermore I am not sure how animals behave during a solar eclipse (no reason to assume that this changes night and day activity).
