### ISSUE TITLE
Cricket sound effect volume slider not working

### ISSUE THREAD

**Issue by TaahDev** [CreativeMD/AmbientSounds#242]
I tried changing the "/ambientsounds/categories/animal" volumes (All Sliders) using the Mod Menu mod, however nothing has changed and the crickets were still chriping. It gets so annoying after a certain amount of time. 
![2024-08-10_14 04 49](https://github.com/user-attachments/assets/08f4952e-307c-4aa3-b5ce-bb626f4b0356)

**Comment by Isakk00** [comment]
I have the same issue. Changing the ini file itself does not work either. on 1.20.1

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
