### ISSUE TITLE
1.20.1 NeoForge Crash with Memory Leak Fix + Cold Sweat

### ISSUE THREAD

**Issue by Astral-Haze** [CreativeMD/AmbientSounds#243]
After updating this mod and cold sweat, the combination of mods causes a crash on entering/creating a world
https://modrinth.com/mod/memoryleakfix
https://modrinth.com/mod/cold-sweat

**Comment by CreativeMD** [comment]
Please don't use NeoForge in 1.20.1, rather use Forge, because the support for NeoForge is untested and sometimes there are issues.
