### ISSUE TITLE
Add Biomes to Ambient Sounds (1.16.5-v3.1.11)

### ISSUE THREAD

**Issue by V-Jupiter** [CreativeMD/AmbientSounds#245]
Heya, i have a small question,
i have been using the AmbientSound mod for a while but have only recently noticed something. I am playing on 1.16.5 using forge with v3.1.11 of AmbientSounds and BiomesOPlenty-1.16.4-13.0.0.431-universal. The issue I am having is that while Ambient Sounds does recognize some BoP Biomes it does not recognize all of them. For example biomesoplenty:tropic_plains. Is there a way to add support for yet unrecognized Biomes added by other mods?

Thank you in advance!
![2024-08-26_23 17 47](https://github.com/user-attachments/assets/4f9a14a5-c728-4f31-b78c-e255a0720059)

**Comment by CreativeMD** [comment]
I do not support 1.16.5 anymore. Seems like proper BoP support is lacking for that version. You could modify the engine to make it work. I personally recommend to update to newer minecraft versions if you can.
