### ISSUE TITLE
Crashes on launch Forge 1.19.2 The mods that I have are listed

### ISSUE THREAD

**Issue by Gratdee** [CreativeMD/AmbientSounds#247]
Whenever I start the game, it closes, then reappears saying "Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance"

The mods I have installed are Embeddium, Rubidium Extra, Embeddium++, TexTrue's Embeddium Options, Oculus, Distant Horizons (as well as the API), CreativeCore, and AmbiantSounds.

**Comment by CreativeMD** [comment]
Seems to be an issue of Oculus. I don't think this has anything to do with AmbientSounds.
