### ISSUE TITLE
Thinks im outside but there is glass

### ISSUE THREAD

**Issue by MineTheCube** [CreativeMD/AmbientSounds#248]
Hi!

I love your mod, it really add something to the game, thanks for creating it!

I maybe have a bug though, not a big one but still: in my cave under my house, it thinks that im outside but there is glass between me and the outside world.

So when im in the cave, I hear the wind:
![image](https://github.com/user-attachments/assets/683e6730-eb41-4faf-91ec-6dc1ed50aa5a)

From outside:
![image](https://github.com/user-attachments/assets/95bda2db-5174-4076-adb3-9b1843eef923)

But as soon as I put some opaque block, i dont hear the wind anymore:
![image](https://github.com/user-attachments/assets/2e8f28a2-163d-4ad0-9d44-a81765aaba45)

Is it possible to do something to fix that? If thats possible :)

Thanks!

**Comment by CreativeMD** [comment]
What version of Minecraft and AmbientSounds are you using? Is this vanilla glass?

**Comment by MineTheCube** [comment]
Minecraft 1.21 (not 1.21.1)
AmbientSounds 6.0.5

And yes this is vanilla glass, everything is pretty vanilla (i play on a non-modded server), I just use Continuity mod to have connected textures with Faithful pack, as well as some QoL/performance mods.

**Comment by CreativeMD** [comment]
Would it be possible for you to send me your world. That would make it a little easier to test. In theory glass should block sound, but something is going wrong there. If you cannot send me your world that is also fine, I can then try to replicate the situation (just takes a little longer).

**Comment by MineTheCube** [comment]
oops, sorry for the delay, as it is a huge server map i didnt know how to get only this part

so anyway, i downloaded surrounding chunks with a mod so here is the map:
https://we.tl/t-ZruuFP9zyy

if you need to get to the place i screenshoted you can do:
`/execute in minecraft:overworld run tp @s -42.91 89.00 -54.54 -721.19 14.21`

thanks for looking into the issue!

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for your fast and good help! It made it really easy to figure out why things do not work out as they should. New version is out! God bless you!
