### ISSUE TITLE
Sound muffling underwater activates too late

### ISSUE THREAD

**Issue by catreplicators** [CreativeMD/AmbientSounds#249]
Going in two-block-tall water does not muffle rain noises, despite the player being fully submerged. Three block tall water does muffle sound (not enough imo, but that's a different issue).

**Comment by CreativeMD** [comment]
I could not reproduce this behavior. I stand in two deep water and the other sounds fade out almost entirely. What version of Minecraft and AmbientSounds are you using?

**Comment by CreativeMD** [comment]
Will close this due to inactivity.
