### ISSUE TITLE
Need to update AmbientSounds to deal with the sound fix in forge-1.12.2-14.23.2.2635

### ISSUE THREAD

**Issue by Tsoccerguy3** [CreativeMD/AmbientSounds#25]
Issue with DS https://github.com/OreCruncher/DynamicSurroundings/issues/296
AmbientSounds needs to be patched to deal with the sound fix in forge-1.12.2-14.23.2.2635

**Comment by CreativeMD** [comment]
v2.2.5 fixes this issue and should be approved soon.
