### ISSUE TITLE
Doesn't work with moonrise

### ISSUE THREAD

**Issue by vroooooooooo** [CreativeMD/AmbientSounds#251]
logs 
https://mclo.gs/5nqCH1A

**Comment by CreativeMD** [comment]
The collision optimization collide with CreativeCore. Sorry but I doubt this can be fixed on my end. Either remove my mods or moonrise. Feel free to report this to the author of moonrise and link the issue here. Maybe a solution can be figured out.

**Comment by vroooooooooo** [comment]
Thanks for the reply.
