### ISSUE TITLE
Is this a mod feature or a bug?

### ISSUE THREAD

**Issue by kcc128398** [CreativeMD/AmbientSounds#252]
I really like this mod, but there is an unpleasant moment _(Minecraft: 1.21, Neoforge 21.1.51, Mod: 6.0.4)_.

When I open a menu of some mode, for example a map in "_Xaero's world map_" or the history of deaths in "_corpse_" (I can't say exactly where. It's always different) and the sounds are paused, and then when I close the menu, the sounds don't return. Only the bird sometimes continues to sing, but wind and cicadas disappears. Rebooting the world doesn't help. I need to reboot the **entire** Minecraft. But this doesn't happen every time, so I can't describe the problem 100 percent accurately.

So, no matter what I do, for example, in a **snowy biome** and a **dark forest**, there is a deathly silence like in vanilla. It looks like a mistake, because there should definitely be a sound of wind in the snow biome, but it stops. I don't know about the dark forest, but it's unpleasant to immediately plunge into silence after a lot of time spent in sounds... UPD: (when I exited from game and entered at the same place, there were sounds of wind and water)

**There are no** Error warnings. All I understood from Debug is that the sounds seem to be playing, you just can't hear them?..

![123123](https://github.com/user-attachments/assets/9258bbfd-0b6e-491e-ac05-13830badb59c)

I used to play on 1.19.2 Forge. I didn't notice this or it wasn't there.

**Comment by CreativeMD** [comment]
Please update to the newest version a critical bug in that regard has been fixed and should prevent this issue.
