### ISSUE TITLE
No sounds when not near any blocks (in the sky)

### ISSUE THREAD

**Issue by UmbralCosmos** [CreativeMD/AmbientSounds#253]
Minecraft 1.20.1
Ambient Sounds 6.0.6

I noticed this when I was high in the sky with a hot air balloon (breezy).

Ambient sounds only seem to play when the player is within 15 blocks of a block.

Honestly wish there were wind sounds at high altitudes instead of dead silence.

Would be overjoyed if this great mod were to become even greater by addressing this issue!

**Comment by CreativeMD** [comment]
At least a wind sound should play, right? Can you send a few screenshots of situations where you feel like sounds should be audible? Please also enabled /ambient-debug for that.

**Comment by UmbralCosmos** [comment]
![1](https://github.com/user-attachments/assets/b08d4a88-2609-49d2-8471-2363b727bc3a)
![2](https://github.com/user-attachments/assets/b3e1079a-cbd0-4263-80b4-2cd5e78401f8)
![3](https://github.com/user-attachments/assets/9dc91565-35c3-42a3-8626-79c30d65423b)

There are absolutely no sounds at all when I'm not within 15 blocks of a block.
They slowly fade out when I'm out of range.

Edit: Noticed this just now, but cicada and cricket sounds play when I'm really high?

**Comment by CreativeMD** [comment]
There should be a sky sound, which was not working. It is fixed in the newest version. Also fixed a few other things. Thanks for reporting this issue.
