### ISSUE TITLE
Make the same sound level for the sounds (some sounds are too loud)

### ISSUE THREAD

**Issue by Redls07** [CreativeMD/AmbientSounds#255]
Some sounds like bird-ambience5, bird-ambience7, bird-ambience10, bird-ambience-huge3, cave-deep2, cave-large1, cave-large2, cave1, heavy-wind, light-wind3, wind-in-leaves and others (I didn't check all the sounds, just I gave some examples) have a much higher volume compared to other audio files in fashion. Even if you try to lower the volume of those regions where these sounds are played, other sounds that were quieter become even quieter after that, becoming hard to hear. Even if it were possible to edit the volume of each sound separately, it would be very long and difficult to check each sound and change its volume. It would be much more convenient if the sound level between audio files in the mod was averaged initially.

**Comment by Redls07** [comment]
Sorry for the inaccuracies in the sentences, I used a translator

**Comment by CreativeMD** [comment]
Thanks for bringing this to my attention. Brought a lot of sounds to the same sound level in the newest version.
