### ISSUE TITLE
cicada-night is playing even when it's not night in region:grass

### ISSUE THREAD

**Issue by Chuzume** [CreativeMD/AmbientSounds#256]
This seems like a bug, judging from the fact that the similarly named Cricket-night only plays at night. Also, even though it's adjustable, the volume is louder than other sounds, and it seems to play too frequently.
![2024-09-27_11 05 45](https://github.com/user-attachments/assets/947d119c-ef1f-4133-b544-8ed622021660)

**Comment by CreativeMD** [comment]
That's actually intentional. These sounds can be heard during the day as well.
