### ISSUE TITLE
Glass Panes don't block wind noise

### ISSUE THREAD

**Issue by jansteffen** [CreativeMD/AmbientSounds#258]
Hello, I built a house using glass panes for windows, but I'm still hearing wind sounds at full volume while inside the house. There are no open holes anywhere, and when I cover up the glass pane windows with solid blocks the wind stops (however bird sounds are still present), see these screenshots:

Normal with glass panes exposed:
![Normal with glass panes](https://github.com/user-attachments/assets/0e9678a1-5c9a-4ae5-978a-966a6b26cd12)

Glass panes blocked with dirt:
![Glass blocked with dirt](https://github.com/user-attachments/assets/5840bcaa-4b5b-4990-b4ea-98f4fc6ba7a7)

(Note the trapdoors seem to correctly block outside noise and covering them doesn't affect anything)

Minecraft Version 1.21.1
Ambient Sounds Version 6.1.2
Creative Corse Version 2.12.16

If needed I could also send you my world file. In case it matters I'm using Terralith for custom biomes, but there are no non-vanilla blocks anywhere in my world.

I saw that there was recently a similiar issue ( #248 ), however that was full glass blocks and not glass panes.

Not a huge issue but I would definitely appreciate a solution to this, love this mod!

**Comment by CreativeMD** [comment]
That's an issue on fabric. If you use NeoForge it will work fine. Problem is that fabric does not have the necessary block tags. You could add them yourself or switch to NeoForge. Sorry, but there is no good way to fix it at the moment.
