### ISSUE TITLE
No ambient sounds in certain aether mod biomes (forge)

### ISSUE THREAD

**Issue by slovinsqui** [CreativeMD/AmbientSounds#259]
Most of times this happens in ancient aether biomes so far, haven´t tried exploring the other biomes just to check, but there for some reason no music or ambient from this mod plays when inside biomes from the ancient aether addon, most of times the ambient sounds only play when its nighttime in very few locations

**Comment by CreativeMD** [comment]
Can you use the command /ambient-debug and make a few screenshots when no sound is playing and tell me what you think should be audible?

**Comment by slovinsqui** [comment]
sure, probably not soon, but i´ll leave an answer here so you know I will do it when I have the time to do so c:

**Comment by CreativeMD** [comment]
I will close this issue for now. Once you have time feel free to post it here and I will reopen the issue.
