### ISSUE TITLE
Modded biomes compatibility

### ISSUE THREAD

**Issue by Fedraik** [CreativeMD/AmbientSounds#260]
Hi, love this mod but i was wondering if there was the possibility to add ambient sounds to modded biomes that are not currently compatible through data/resource pack, and if it is possible how can i do that? i tried to give a look at the mod folder but i wasn't able to find any clue. Fabric 1.20.1

**Comment by CreativeMD** [comment]
Yeah, through a resourcepack it can be done. What mods are you talking about btw? I try to keep support for the most common mods included.

**Comment by MottiDowerro** [comment]
> Yeah, through a resourcepack it can be done. What mods are you talking about btw? I try to keep support for the most common mods included.

Hi, Mod called Big Globe

**Comment by Fedraik** [comment]
> Yeah, through a resourcepack it can be done. What mods are you talking about btw? I try to keep support for the most common mods included.

Mainly Nature's Spirit, YUNG's Cave Biomes and Profundis, but in general alot of like cave biomes mods. On surface you don't notice the difference that much, but in the caves when you enter a modded biome it becomes totally silent and it's difficult not to notice

**Comment by CreativeMD** [comment]
Would help a lot of you can use the command /ambient-debug, make a few screenshots of situations where you feel like the sound is off (or not there at all), post them here and tell me what you think should be playing. That would be make it quite easy for me.

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. Still feel free to respond here.

**Comment by Fedraik** [comment]
hi, sorry for the inactivity, but i didn't have much time to spend on mc in the last weeks but i definetely will update this issue with all the info you asked once ill have some time to dedicate to that
