### ISSUE TITLE
Effort required for better indoor/outdoor detection?

### ISSUE THREAD

**Issue by ac101m** [CreativeMD/AmbientSounds#261]
First off, thank you for creating this mod!
I've used it for years now and I enjoy the additional ambiance it brings to the game.
One thing I've always thought could be improved however, is that interiors of buildings often sound very similar to exteriors.
I currently have no knowledge of how the mod works, but would be happy to contribute with a little guidance. Is this something that you feel is achievable?

**Comment by CreativeMD** [comment]
Best way is to provide situations of the engine not detecting things as it should. Use the command /ambient-debug and make a few screenshots of the surroundings. This helps a lot to see when things are going wrong.

**Comment by CreativeMD** [comment]
I will close this due to inactivity. Feel free to respond here anyway.

**Comment by ac101m** [comment]
> I will close this due to inactivity. Feel free to respond here anyway.

Apologies for not getting back to you.

I played around with the debug command as you suggested, and also spent some time looking at the documentation for creating engines, so I understand the mod a little better now. I don't necessarily think the issue is with the capacity of the mod to detect the surroundings, the flood-fill system you've got going on seems to me like it ought to be able to detect most situations.

I think what the mod may be missing is "indoors-ified" versions of outdoor soundscapes to be played in situations where the outdoors ought to be audible, but maybe not directly. There's probably some science involved with how to process audio to make it sound as though it's an outdoor sound being heard from inside, but I haven't looked into that.

I've been meaning to spend some time tinkering with this but haven't gotten round to it yet.

If I come up with anything substantial I'll post it here :+1:
