### ISSUE TITLE
list of biomes and dimensions to support

### ISSUE THREAD

**Issue by 0Navis0** [CreativeMD/AmbientSounds#27]
I noticed some mods hadn't the good sounds, and the support for modded dimensions weren't really good. So I made a list of all the biomes ordered by type and dimensions. 

It includes Minecraft, BiomesOPlenty, Traverse, Thaumcraft, BuildCraft, IntegratedDynamics, DefiledLands, TwilightForest, Erebus, Betweenlands, Aether, FuturePack, Tropicraft.

Don't even ask me how much time I toke for making this list, I must really like your mod for doing it. I hope it will help you for supporting all the modded biomes and dimensions.

There are some special biomes like the Tainted Lands, Eerie from Thaumcraft and Degraded from Evilcraft I didn't know where to place. They take over the other biomes and replace them slowly, corrupting all the life around. I suppose they would be desert/wasteland

- Overworld
    - Desert / Wasteland
        - Arid Highland (desert and savanna)
        - Defiled Desert
        - Desert
        - Desert Hills
        - Lush Desert (desert and savanna)
        - Mesa
        - Mesa Plateau
        - Moutainous Desert
        - Oil Desert
        - Outback (desert and savanna)
        - Red Desert
        - Wasteland
        - Xeric Shrubland (desert and savanna)

    - Forest
        - Birch Forest
        - Birch Forest Hills
        - Birch Forested Hills
        - Cherry Blossom Grove
        - Crystal Forest
        - Darklands Forest
        - Flatland Thicket
        - Forest
        - Forest Hills
        - Forested Hills
        - Grove
        - Lush Hills
        - Magical Forest
        - Mystic Grove
        - Orchad
        - Origin Island
        - Origin Valley
        - Rainforest
        - Roofed Forest
        - Sacred Springs
        - Tenebra Forest
        - Thicket
        - Vilespine Forest
        - Woodland

    - Highland
        - Alps
        - Alps Foothills
        - Cliffs
        - Defiled Hills
        - Darklands Highland
        - Darklands Mountains
        - Extreme Hills
        - Extreme Hills+
        - Extreme Hills Edge
        - Highland
        - Mountain Foothills
        - Mountain Peaks
        - Volcanic Island

    - Jungle
        - Bamboo Forest
        - Encalyptus Forest
        - Jungle
        - Jungle Edge
        - Mini Jungle
        - Oasis
        - Overgrown Cliffs
        - Tropical Island
        - Tropical Rainforest

    - Plain
        - Chaparral
        - Darklands
        - Darklands Plains
        - Defiled Plains
        - Desert Shrubland
        - Flower Field
        - Flower Island
        - Grassland
        - Lavender Fields
        - Mushroom Island
        - Pasture
        - Plains
        - Prairie
        - Rocky Plains
        - Rocky Plateau
        - Shrubland

    - Savanna
        - Arid Highland (desert and savanna)
        - Badlands
        - Brushland
        - Lush Desert (desert and savanna)
        - Outback (desert and savanna)
        - Savanna
        - Savanna Plateau
        - Spiny Forest (desert and savanna)
        - Steppe
        - Xeric Shrubland (desert and savanna)

    - Swamp
        - Bayou
        - Bog
        - Coralium Infested Swamp
        - Dead Swamp
        - Defiled Swamp
        - Fen (swamp and taiga)
        - Lands Of Lakes (swamp and taiga)
        - Lush Swamp
        - Mangrove
        - Marsh
        - Moor
        - Quagmire
        - Swampland

    - Taiga
        - Autumnal Forest
        - Autumnal Woods
        - Autumnal Wooded Hills
        - Boreal Forest
        - Cold Taiga
        - Cold Taiga Hills
        - Coniferous Forest
        - Dead Forest
        - Fen (swamp and taiga)
        - Heathland
        - Land Of Lakes (swamp and taiga)
        - Maple Wood
        - Meadow
        - Meadow Forest
        - Mega Taiga
        - Mega Taiga Hills
        - Meneglin
        - Ominous Woods
        - Redwood Forest
        - Seasonal Forest
        - Shield
        - Snowy Coniferous Forest
        - Snowy Forest
        - Taiga
        - Taiga Hills
        - Temperate Rainforest

    - Tundra
        - Cold Desert
        - Defiled Ice Plains
        - Glacier
        - Glacier Spikes
        - Ice Plains
        - Ice Mountains 
        - Tundra

    - Beach
        - Beach
        - Cold beach
        - Gravel beach
        - Mushroom island shore
        - Stone beach
        - White beach

    - Ocean
        - Coral Reef
        - Deep Ocean
        - Frozen Ocean
        - Kelp Forest
        - Ocean
        - Oil Ocean

    - River
        - Frozen River
        - River

- Ender
    - Ender
        - The End

- Nether
    - Nether
        - Arctic Abyss
        - Corrupted Sands
        - Fungi Forest
        - Hell
        - Phantasmagoric Inferno
        - Polar Chasm
        - Ruthless Sands
        - Torrid Wasteland
        - Undergarden
        - Visceral Heap

- Twilight Forest
    - Forest
        - Dark Forest
        - Dark Forest Center
        - Deep Mushroom Forest
        - Dense Twilight Forest
        - Enchanted Forest
        - Firefly Forest
        - Mushroom Forest
        - Twilight Clearing
        - Twilight Forest

    - Highland
        - Highlands Center / Final Plateau
        - Twilight Glaciers

    - Savanna
        - Oak Savanna

    - Swamp
        - Fire Swamp
        - Twilight Swamp

    - Taiga
        - Snowy Forest
        - Thornlands
        - Twilight Highlands

    - River
        - Lake
        - Streams

- Betweenlands
    - Swamp
        - Patchy Islands
        - Swamplands
        - Deep Waters
        - Coarse Islands
        - Sludge Plains
        - Marsh 0
        - Marsh 1

- Erebus
    - Desert / Wasteland
        - Ulterior Outback
        - Volcanic Desert
        - Petrified Forest

    - Forest
        - Elysian Forest

    - Jungle
        - Underground Jungle

    - Savanna
        - Subterranean Savannah

    - Swamp
        - Fungal Forest
        - Submerged Swamp

    - Plain
        - Elysian Fields

- Abyssal Wasteland / Dreadlands / Omothol (AbyssalCraft)
    - End
        - Abyssal Wastelands
        - Dreadlands
        - Purified Dreadlands
        - Dreadlands Forest
        - Dreadlands Mountains
        - Omothol
        - Dark Realm

- Menelaus / Tyros (FuturePacks)
    - Desert
        - Menelaus
        - Menelaus Flat

    - Highlands
        - Tyros Mountain
        - Tyros Rock Desert
        - Tyros Rock Plateau

    - Jungle
        - Tyros

    - Swamp
        - Tyros Swamp

    - Ocean
        - Menelaus Sea
        - Tyros Sea

- Tropics (Tropicraft)
    - Jungle
        - Tropics

    - Highland
        - Tropics Rainforest Hills
        - Tropics Rainforest Island Moutains
        - Tropics Rainforest Moutains

    - Plain
        - Tropics Plains

    - Beach
        - Tropics Beach

    - River
        - Tropics Lake
        - Tropics River

    - Ocean
        - Kelp Forest
        - Tropics Ocean

- Aether
    - Forest (or Plains ?)
        - Highlands
        - Forgotten Highlands
        - Magnetic Hills
        - Irradiated Forests
    - Taiga (or Tundra ?)
        - Arctic Peaks

**Comment by CreativeMD** [comment]
Ok ... finally found some time for it. Some of your hints are a little bit confusing, I tried to do my best to figure out what to do (some duplicates).

I don't want to release it yet, because it's not tested. So if you have some time I would be really happy if you could give it a try:
https://www.dropbox.com/s/cak2dxh35w0erkv/AmbientSounds_v2.3_mc1.12.2.jar?dl=1

**Comment by 0Navis0** [comment]
Aw thanks for the update, I will try it later. I will add Aether 2 biome list later. So tells me what is confusing ?

**Comment by CreativeMD** [comment]
Most of the biomes where already supported by AmbientSounds (thanks to your previous lists), but many of them were associated with different biomes than you specified now.

**Comment by 0Navis0** [comment]
Oh I maybe made some errors with the precedent list, it's hard to not do with so many biomes.

**Comment by CreativeMD** [comment]
No problem :D
It would be very cool if you could test it, because there might be a couple of mistakes from my end?

**Comment by Hypsellis** [comment]
I didn't try everything, but from what I tested, it works fine. ;)

**Comment by CreativeMD** [comment]
Good to hear that! Have you tested a few dimensions as well, because that's the one I'm afraid about?

**Comment by 0Navis0** [comment]
No I didn't try yet, I have few issues with my modpack now, some mods crash, I wait the fixes.

**Comment by CreativeMD** [comment]
Ok, just let me know when you test it.

**Comment by 0Navis0** [comment]
Ok I tried, and the mod just doesn't work, there are no sounds which play.

**Comment by CreativeMD** [comment]
Talking about the dimensions or everything?

**Comment by 0Navis0** [comment]
Nah everything.

**Comment by CreativeMD** [comment]
Have you updated your Forge version?

**Comment by 0Navis0** [comment]
Yeah last one 14.23.3.2698

**Comment by CreativeMD** [comment]
Can you send me your modpack? Did it work before? Maybe it's an issue with another mod (a log would be helpful).

**Comment by 0Navis0** [comment]
My modpack isn't on Curse, it's still on test. There are so many mods on it, good luck for finding it.

**Comment by CreativeMD** [comment]
But it did work before? Can you send me your log file?

**Comment by CreativeMD** [comment]
Still there?

**Comment by 0Navis0** [comment]
Yeah sorry I forgot about it, I'm a bit busy these days with work. Anyway good luck for finding what you research in the mess of my modpack log. 
[latest.log](https://github.com/CreativeMD/AmbientSounds/files/2070717/latest.log)

**Comment by CreativeMD** [comment]
`[22:55:54] [main/ERROR]: Sound engine crashed, no sounds will be played!`
Looks like the sound engine crashed during startup, this can happen if there is not enough ram (not sure about it).

I will test it myself and see if the dimension support works.

**Comment by CreativeMD** [comment]
Ok, looked like this was my mistake, I fixed it, can you give it another try?
I tried the underground dimension of lightningcraft, which works as it should.

https://www.dropbox.com/s/cak2dxh35w0erkv/AmbientSounds_v2.3_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
Uploaded it to curseforge. Thank you very very much for your help!!! I would never have the patience and the time to look up all these biomes.

**Comment by 0Navis0** [comment]
I should try Aether too, I didn't look at it now, I will look it later. Anyway thanks for all the supports, it's awesome. <3

**Comment by CreativeMD** [comment]
Just open another issue if you have collected something new :D
