### ISSUE TITLE
Merge with Dynamic Surroundings?

### ISSUE THREAD

**Issue by xhatz** [CreativeMD/AmbientSounds#28]
Hello!

I really really like **AmbientSounds**, but I also love **Dynamic Surroudings**... would it be possible that you ever merge your work or allow DS to include it please :/? It would be less work for your team as you already have a lot of mods, and one less mod in our modpacks haha, I always use both, can't do without one only :P It'd be really cool ^^' (and also maybe reduce the channel problems x/ ?)

Thank you and keep your awesome work, I love all of your mods :P

**Comment by CreativeMD** [comment]
Sorry, but I don't want to do so. Just use both :D there is no issue, you can configure the channels as you want to. Just keep in mind, that I worked on AmbientSounds for a long time (2 years), I won't just give it to someone else (even though the author of Dynamic Surroundings is a cool guy).

**Comment by xhatz** [comment]
It is understandable, thank you for your time ^^
