### ISSUE TITLE
Make a 1.7.10 legacy version with Biomes O Plenty support?

### ISSUE THREAD

**Issue by KKZiomek** [CreativeMD/AmbientSounds#29]
Is it possible to make a legacy 1.7.10 version with Biomes O Plenty support, as a large portion of mod-playing community still sits on 1.7.10 since it has seen the biggest selection of mods? Thank you :)

I saw that version with Biomes O Plenty support is coming for 1.12, but will it be possible to make an update for 1.7.10 too?

**Comment by CreativeMD** [comment]
There used to be a bug in the sound engine, which got fixed after 1.7.10. Basically means that AmbientSounds doesn't work for 1.7.10 or at least not in a good way, so I can't recommend using it.

Here is the latest version for 1.7.10 (if you want to see it yourself): https://www.dropbox.com/s/yi7mnulhszq0edp/AmbientSounds%20Alpha%20v0.1%20mc1.7.10.zip?dl=1
