### ISSUE TITLE
ATM2

### ISSUE THREAD

**Issue by whatthedrunk** [CreativeMD/AmbientSounds#3]
I want to keep this mod in ATM2 but I have a couple issues. 

1. When trying to load on a server the mod crashes the server. From what I am told there is a line of code that needs to be added to not load. Before this was fine because I just left the files off the server files download but not curse says I cannot upload server files anyone.
2. The crickets get a lot of hate on the discord for being too loud.

**Comment by CreativeMD** [comment]
You can't install this mod on a server, so this is not an issue. This mod is client side only.

You can change the volume of each biome sound inside the config file.

**Comment by whatthedrunk** [comment]
It's not about wanting it on a server it's about making it easier for users to setup server files. Forge has a way for you to mark the mod as client only for this reason.

**Comment by CreativeMD** [comment]
I don't get it to be honest, what is the problem in deleting a mod file, but whatever i will try to fix it. Update should be available soon.

**Comment by whatthedrunk** [comment]
It's not hard at all for me but the users that play ATM don't always understand crashes or wonder why only this client mod needs to be removed but the other ones are fine.

**Comment by CreativeMD** [comment]
yeah, but still aren't there two different types of archive files (one for client, one for sever)?

**Comment by whatthedrunk** [comment]
You know what I am being silly here. It's only sound filters that is trying to load on servers. The only issue with this was the louder crickets but I just noticed default options mod is out now for 1.11.2. I'll follow up with sound filters now thanks for trying to help anyway.
