### ISSUE TITLE
more biomes support and fixes

### ISSUE THREAD

**Issue by 0Navis0** [CreativeMD/AmbientSounds#30]
I added Aether biomes in the long list I had made, since the time I told you about it. I'm not sure if they should be classified as plains or forest, since they are between two, but I think forest would fit them more. I let you look at them by yourself. https://aether.gamepedia.com/Biome

RealWorld has been splitted between Plant Mega Pack and Decoration Mega Pack, and the biomes "Bamboo Marsh", "Birch Autumn Forest", "Blue Oak Forest", "Bur Oak Forest", "Bambona Beach",  "Emperor Ridge", "Flatland Thicket", "Silver Birch Hills", "Spiny Forest", "Spruce Mountains" has been removed with it. So all these biomes don't need more support.

I made some error classifying some biomes, notably "Badlands" from Traverse are Savanna and not Plains, and I added some missing and new biomes from Traverse. I added NetherEx biomes as well.

I put everyting all the changes on the list I had made on first issue. https://github.com/CreativeMD/AmbientSounds/issues/27

**Comment by CreativeMD** [comment]
I have been working on a massive AmbientSounds rework. I added more sounds and enhanced the old ones to support smooth looping. I also redid the engine and added some tools to make it feel more immersive.

It's quite untested, but it should (in theory) include your requested changes. I would be very happy if you could test it.

https://www.dropbox.com/s/seoavzwuqfhh413/AmbientSounds_v3.0.0.jar?dl=1

There is also a new command /ambient-debug, which provides detailed about which sound is playing at the moment. It should help to trace down issues.

**Comment by CreativeMD** [comment]
AmbientSounds v3.0.0 has been released!
