### ISSUE TITLE
Version 3.0.1 client crash on death when also have mod DynamicSurroundings

### ISSUE THREAD

**Issue by infamyreloaded** [CreativeMD/AmbientSounds#33]
The client crashes on death when you are running version 3.0.1 or 3.0.0 of ambientsounds and also have dynamicsurroundings loaded. You do not crash when you have ambientsounds version 2.3.

How to reproduce: 
1. Die from zombies
2. Click "Respawn"
3. Client crashes

Crash report: https://gist.github.com/infamyreloaded/4c977f00219a2ad18964bfc26c246ba1

AmbientSounds: 3.0.1
Forge: 14.23.5.2807
Minecraft: 1.12.2
OreLib-1.12.2-3.5.2.2
DynamicSurroundings-1.12.2-3.5.4.3

**Comment by CreativeMD** [comment]
You download AmbientSounds v3.0.0, updated to the newer one and it should work just fine.

**Comment by redxef** [comment]
I have the same issue with AS 3.0.2

[crash-2019-03-24_18.50.13-client.txt](https://github.com/CreativeMD/AmbientSounds/files/3000652/crash-2019-03-24_18.50.13-client.txt)

**Comment by CreativeMD** [comment]
Fixed again in v3.0.3
