### ISSUE TITLE
AmbientSounds 3 NullPointerException crash

### ISSUE THREAD

**Issue by Dimentive** [CreativeMD/AmbientSounds#34]
I disabled a sound in the config of Dynamic Surroundings in-game, and it caused AmbientSounds 3 to crash my game. It also happens while FTB Utilities saved a backup of my world. I don’t know if it has anything to do with either Dynamic Surroundings or FTB Utilities.

I’m playing on a locally hosted server with one friend.

Crash report: https://pastebin.com/raw/ABPNhGwL

**AmbientSounds version:** 3.0.3
**Minecraft version:** 1.12.2
**Forge version:** 14.23.5.2781
**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version 1.63a, latest) (with [some mods added](https://pastebin.com/raw/b2ukLgKv))

**Comment by CreativeMD** [comment]
Can you send me the crashreport?

**Comment by Dimentive** [comment]
Oh, sorry. I uploaded it to Pastebin but forgot to include it in this issue.

Here it is: https://pastebin.com/raw/ABPNhGwL

**Comment by CreativeMD** [comment]
Please update to the newest version. This crash report is from AmbientSounds v3.0.1

**Comment by Dimentive** [comment]
Oh, whoops. I did originally update to version 3.0.3, but then, in the process of updating the modpack I’m playing to the newest version, I accidentally reverted back to AmbientSounds 3.0.1.

My bad. I’ll update AmbientSounds right away. Thank you!
