### ISSUE TITLE
Twilight Forest bird sounds only play underground

### ISSUE THREAD

**Issue by Yodragon** [CreativeMD/AmbientSounds#35]
When you're on the surface, only wind and distant crows can be hard. Once you go into a cave though, the birds suddenly kick into high gear and sound off. I'm assuming the mod is having a hard time figuring out distinguishing between what's the surface, cave, and sky in the Twilight Forest.

**Comment by CreativeMD** [comment]
Is it in a biome with huge trees or just an ordinary one?

**Comment by Yodragon** [comment]
I think it happens in all the Twilight Forest biomes, though I've only thoroughly checked the "Twilight Swamp", "Twilight Clearing", "Twilight Forest", "Mushroom Forest", and "Enchanted Forest" biomes. I'll probably check all the other biomes and get back to you on it.

**Comment by CreativeMD** [comment]
Can you type in /ambient-debug and send me a screenshot of it (in cave and on the surface). It would help me to figure out the fix.

**Comment by Yodragon** [comment]
Oh, my bad, completely forgot I was gonna check the other biomes. Gimme a sec and I'll give ya some screenshots.

**Comment by Yodragon** [comment]
![dark forest canopy 2019-04-22_10 18 10](https://user-images.githubusercontent.com/49503358/56514228-9f0b8280-64e9-11e9-8bb5-61acb99d44e3.png)
![dark forest cave 2019-04-22_10 19 24](https://user-images.githubusercontent.com/49503358/56514229-9f0b8280-64e9-11e9-8563-857ffe900fc0.png)
![dark forest surface 2019-04-22_10 18 57](https://user-images.githubusercontent.com/49503358/56514230-9fa41900-64e9-11e9-8fe3-78b5e77c4c53.png)
![deep mushroom forest canopy 2019-04-22_10 25 59](https://user-images.githubusercontent.com/49503358/56514231-9fa41900-64e9-11e9-981a-d5e142f0727d.png)
![deep mushroom forest cave 2019-04-22_10 14 51](https://user-images.githubusercontent.com/49503358/56514232-9fa41900-64e9-11e9-8a3a-43d81620ccda.png)
![deep mushroom forest surface 2019-04-22_10 14 33](https://user-images.githubusercontent.com/49503358/56514233-9fa41900-64e9-11e9-8a10-d0049133589d.png)
![final plateau cave 2019-04-22_10 11 01](https://user-images.githubusercontent.com/49503358/56514234-9fa41900-64e9-11e9-87ba-172016dbc132.png)
![final plateau surface 2019-04-22_10 10 47](https://user-images.githubusercontent.com/49503358/56514235-9fa41900-64e9-11e9-9dbb-f6d06f62a6f1.png)
![firefly forest cave 2019-04-22_10 22 57](https://user-images.githubusercontent.com/49503358/56514236-a03caf80-64e9-11e9-960e-c7cdf7c9e542.png)
![firefly forest surface 2019-04-22_10 22 19](https://user-images.githubusercontent.com/49503358/56514237-a03caf80-64e9-11e9-94e2-dd6c3f871f33.png)
![glacier cave 2019-04-22_10 21 06](https://user-images.githubusercontent.com/49503358/56514238-a03caf80-64e9-11e9-926a-103cf020473a.png)
![glacier surface 2019-04-22_10 20 42](https://user-images.githubusercontent.com/49503358/56514239-a03caf80-64e9-11e9-86f6-4b6e95772b35.png)
![glacier under ice 2019-04-22_10 20 56](https://user-images.githubusercontent.com/49503358/56514240-a03caf80-64e9-11e9-9c11-9dc8a67d6b1a.png)
![mushroom forest canopy 2019-04-22_10 24 31](https://user-images.githubusercontent.com/49503358/56514241-a03caf80-64e9-11e9-8a10-1e3ef074a03d.png)
![mushroom forest cave 2019-04-22_10 24 55](https://user-images.githubusercontent.com/49503358/56514242-a0d54600-64e9-11e9-85b2-ebe6e0bc912a.png)
![mushroom forest surface 2019-04-22_10 24 45](https://user-images.githubusercontent.com/49503358/56514243-a0d54600-64e9-11e9-98dc-f9e34ee67c88.png)
![oak savannah cave 2019-04-22_10 26 47](https://user-images.githubusercontent.com/49503358/56514244-a0d54600-64e9-11e9-9212-c28aacca42f0.png)
![oak savannah surface 2019-04-22_10 26 38](https://user-images.githubusercontent.com/49503358/56514245-a0d54600-64e9-11e9-872e-00b095407e1f.png)
![snowy forest cave 2019-04-22_10 20 01](https://user-images.githubusercontent.com/49503358/56514246-a0d54600-64e9-11e9-99f3-4fad536edac0.png)
![snowy forest surface 2019-04-22_10 19 47](https://user-images.githubusercontent.com/49503358/56514247-a16ddc80-64e9-11e9-8ea8-e39ea76337bf.png)
![twilight clearing cave 2019-04-22_10 11 49](https://user-images.githubusercontent.com/49503358/56514248-a16ddc80-64e9-11e9-9459-18cbc5f4cafc.png)
![twilight clearing surface 2019-04-22_10 11 33](https://user-images.githubusercontent.com/49503358/56514249-a16ddc80-64e9-11e9-9816-8e9af6d43562.png)
![twilight forest canopy 2019-04-22_10 27 35](https://user-images.githubusercontent.com/49503358/56514250-a16ddc80-64e9-11e9-8168-dc2b4d11d2dc.png)
![twilight forest cave 2019-04-22_10 08 52](https://user-images.githubusercontent.com/49503358/56514251-a16ddc80-64e9-11e9-8406-ad776f61a99b.png)
![twilight forest surface 2019-04-22_10 07 26](https://user-images.githubusercontent.com/49503358/56514252-a2067300-64e9-11e9-9115-eb22b47abb79.png)
![twilight highlands cave 2019-04-22_10 10 05](https://user-images.githubusercontent.com/49503358/56514253-a2067300-64e9-11e9-98ef-c966a0f29984.png)
![twilight highlands surface 2019-04-22_10 09 42](https://user-images.githubusercontent.com/49503358/56514254-a2067300-64e9-11e9-90d2-ce09610aea22.png)
![twilight lake cave 2019-04-22_10 16 56](https://user-images.githubusercontent.com/49503358/56514255-a29f0980-64e9-11e9-9a57-a91deb3b9114.png)
![twilight lake surface 2019-04-22_10 16 36](https://user-images.githubusercontent.com/49503358/56514256-a29f0980-64e9-11e9-9537-2ea612c2be00.png)
![twilight lake underwater 2019-04-22_10 16 43](https://user-images.githubusercontent.com/49503358/56514257-a29f0980-64e9-11e9-92aa-716c12cc9839.png)
![twilight swamp cave 2019-04-22_10 16 02](https://user-images.githubusercontent.com/49503358/56514258-a29f0980-64e9-11e9-942c-f08105b4682a.png)
![twilight swamp surface 2019-04-22_10 15 48](https://user-images.githubusercontent.com/49503358/56514259-a29f0980-64e9-11e9-8a92-82310dadfc4e.png)

**Comment by Yodragon** [comment]
Basically, the biome-specific sounds only play underground for most of the biomes, with the exception of the Twilight Highland and Final Plateau ones which work just fine.

Another strange thing I found is that the forest-related biomes (such as the Dark Forest, Deep Mushroom Forest, Mushroom Forest, Firefly Forest, and Twilight Forest biomes) also played the correct sounds if you were high enough, near the canopy of the trees.

**Comment by CreativeMD** [comment]
Is the suspense.end sound annoying you? This one is actually not bound to caves but to this dimension in general (will always play). I thought it would help the atmosphere but it might also be a little bit too much.

**Comment by Yodragon** [comment]
Well, I don't think it would annoy me, but I actually wouldn't be affected by a change like that. I'm working on a modpack that uses your engine to add my own ambient sounds so all of your sounds will probably be changed or removed.

I was trying to figure out a way to get the sounds working properly in the Twilight Forest so I could make all the biomes sound unique and distinct from the Overworld biomes. For example, the fire swamp would sound much more creepy and volcanic than the normal swamp.

Although, I'm probably just going to end up taking your approach with "suspense.end" and create "suspense.twilight_forest" which'll just play everywhere.

**Comment by CreativeMD** [comment]
Are you familiar with the engine.json [(twilight forest dimension)](https://github.com/CreativeMD/AmbientSounds/blob/1.12/src/main/resources/assets/ambientsounds/engine.json#L90) file? There is no tutorial about the new version, but I can help you (if you want to).

Furthermore you can also release your modified version, I would love to link some addons on the curseforge page. Just let me know what you think about it. I will close this issue for now, because it appears like everything is solved (if I'm not mistaken).
