### ISSUE TITLE
When a player is in two regions with the same defined sound file, the sound echoes

### ISSUE THREAD

**Issue by genandnic** [CreativeMD/AmbientSounds#36]
Say I edited engine.json so that all "surface" regions had a light wind playing. But the "ocean" region is also programmed to play the light wind sound, so the sound ends up playing twice at the same time. Couldn't there be a priority system implemented to prevent the same sound from being played over itself? For example, the ocean's light wind overrides the light wind of the surface wind because it's more specific, or just defined after the surface region in the engine.json. 

I wanted to do this because I like the wind sounds provided by ambience mods, but not so much the noisy fauna that loops endlessly throughout long play sessions. If you disable all the bird/cricket/etc sounds via the config, some biomes (like the forest) are left with no sounds at all; dead silence.

So I want the wind to play in all surface biomes, but I might also want the same wind to play a bit louder in the desert biome without the sound being duplicated.

**Comment by CreativeMD** [comment]
Sounds like you want to modify the engine. The file "assets/ambientsounds/engine" ([link](https://github.com/CreativeMD/AmbientSounds/blob/1.12/src/main/resources/assets/ambientsounds/engine.json)). Maybe take a look at it. It will allow you create the described things. I can also help you to understand how it works.

**Comment by CreativeMD** [comment]
I will close this issue for now. Just let me know if you need any help with it.
