### ISSUE TITLE
[Suggestion] Dimension blacklist/whitelist

### ISSUE THREAD

**Issue by fivelol** [CreativeMD/AmbientSounds#37]
I'm playing this mod with another mod that adds a dimension and already has ambient sounds there, but the sounds from this mod are still playing. Would it be possible to have an option in the config to blacklist this mod's sounds based on dimension id?

**Comment by CreativeMD** [comment]
Can you give me the name of the mod? It can easily be added to the engine.

**Comment by fivelol** [comment]
The mod that adds the ambient sounds is 'the midnight'

**Comment by CreativeMD** [comment]
v3.0.5 should fix it thanks for your report. Just let me know if it works.

**Comment by fivelol** [comment]
This seems to work perfectly, thanks!
