### ISSUE TITLE
Cave sounds play inside of my house.

### ISSUE THREAD

**Issue by Kissune** [CreativeMD/AmbientSounds#38]
The ambient dripping and echos of a cave play while I'm inside my house, which is kind of annoying. My house isn't underground. https://i.imgur.com/FbTRxdy.jpg The cave theme plays only on the main floor of my house, and the front part.

**Comment by CreativeMD** [comment]
Which version of the mod or you using?

**Comment by CreativeMD** [comment]
If you are using the newest version type in /ambient-debug and go to the position where the cave them plays. Take a screenshot and send it to me (it would help a lot).

**Comment by Kissune** [comment]
https://i.imgur.com/5etg0Pk.jpg

**Comment by Kissune** [comment]
https://i.imgur.com/z3JjSCE.jpg

**Comment by Kissune** [comment]
https://i.imgur.com/tutgUhE.jpg here's another place that it plays

**Comment by CreativeMD** [comment]
Can you send me your world? It would make my life a lot easier.

**Comment by CreativeMD** [comment]
Still there?

**Comment by Kissune** [comment]
Hi! Sorry, missed the email before. It's part of the modpack magiculture 2, with the updated version of your mod added on, since it came with an older version.

**Comment by Kissune** [comment]
https://drive.google.com/open?id=1OF3GPj4qJF9z-74rdl3y8wD3yusy86Je And here's the link, since apparently the world was too big for github.

**Comment by CreativeMD** [comment]
This issue should be fixed in the newest version 3.0.8. Thanks for reporting this issue!
