### ISSUE TITLE
How do I disable it for new dimensions from mods?

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#39]
Hello, I have Galacticraft on my server and when I use Ambient Surroundings I'm hearing cricket noises on the planets, I'm wondering how I could edit the config to exclude those biomes/dimensions from the mod?

**Comment by CreativeMD** [comment]
I could do that, but I need the name of the dimensions.

EDIT
Is there an official list or can you find them out ingame?

**Comment by ghost** [comment]
I have the name of the dimensions here. Here's the dimensions and the ID numbers:

Mars (-29)
Moon (-28)
Overworld Space Stations (-27)
Static Space Stations (-26)
Asteroids (-30)
Venus (-31)

If possible I'd like all of them with the exception of Mars and Venus to be silent. 

EDIT: For Venus and Mars, put whatever you'd think appropriate for either of those planets if you already have it available. No need to overwork yourself for me, thank you!

**Comment by CreativeMD** [comment]
Hey sorry, I wanted to respond a lot earlier, but somehow forgot about it.

Feel free to give some suggestions related to venus and mars. I could add some windy sounds easily. The difficult part is to figure out what is suitable. I would love to add some extra sounds for these planets. Just let me know what you think about it.

**Comment by ghost** [comment]
The only ambiance I would imagine would be fitting for Mars/Venus is like a windy-wasteland type of thing. If you have a sound in the mod that already does that you can just use that

**Comment by CreativeMD** [comment]
Uploaded the new version to curseforge, should be available soon. Hope everything works fine now and let me know what you think about the wind sound for mars/ venus.

**Comment by ghost** [comment]
Awesome! Can I get a link to the jar?

**Comment by CreativeMD** [comment]
https://minecraft.curseforge.com/projects/ambientsounds/files/2708371

**Comment by ghost** [comment]
I just tested it out and I'm still hearing birds chirping and stuff on Venus. I even made sure to delete the old config. I haven't tested Mars yet due to time but could you look into that?
\

**Comment by CreativeMD** [comment]
The thing is I need the exact names of the dimension. The ones you gave me unfortunately do not represent the internal ones (as it seems). So I added the dimension name to the debug screen. Just download this version here, type in `/ambient-debug` and send the dim-name to me (on the top right).

https://www.dropbox.com/s/nb11nc76otj6agu/AmbientSounds_v3.0.7_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
You might also try out v3.0.8, which might fix your issue as well:
https://minecraft.curseforge.com/projects/ambientsounds/files/2708946

If not make sure to send the names of the dimensions.

**Comment by ghost** [comment]
Oh yes I apologize, I found the biome IDs on the wiki. Lemme check that other download and see if it works

Moon - moon
Mars - marsFlat (should have wind)
Asteroids - asteroids
Overworld Space Station - space
Venus - planetVenus (should have wind)

All others should have no sound at all, not even cave sounds

Lemme try that second download

**Comment by ghost** [comment]
The version you sent me has no sound on Mars/Venus, but there's no birds chirping

**Comment by CreativeMD** [comment]
The new version v3.0.9 should fix it. Sorry that it took so long ... thanks for your help! Just let me know if everything is fine or not.

**Comment by CreativeMD** [comment]
Guess it is fixed now. Thanks for your help. If there is anything I can do further just let me know.
