### ISSUE TITLE
Add Gradle to project

### ISSUE THREAD

**Issue by Tsoccerguy3** [CreativeMD/AmbientSounds#4]
Add Gradle http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2227/forge-1.11.2-13.20.0.2227-mdk.zip

Heres the Gradle build log Their are 2 errors 

`This mapping 'snapshot_20170207' was designed for MC 1.11! Use at your own peril.This mapping 'snapshot_20170207' was designed for MC 1.11! Use at your own peril.

#################################################
         ForgeGradle 2.2-SNAPSHOT-2112b0a        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches SKIPPED
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:deobfMcMCP SKIPPED
:sourceApiJava
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJavaC:\Users\ASUS\Dev\ambsou\build\sources\main\java\com\creativemd\ambientsounds\TickHandler.java:38: error: cannot find symbol
			EntityPlayer player = mc.thePlayer;
			                        ^
  symbol:   variable thePlayer
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\ambsou\build\sources\main\java\com\creativemd\ambientsounds\TickHandler.java:39: error: cannot find symbol
			World world = mc.theWorld;
			                ^
  symbol:   variable theWorld
  location: variable mc of type Minecraft
Note: C:\Users\ASUS\Dev\ambsou\build\sources\main\java\com\creativemd\ambientsounds\AmbientSounds.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.913 secs
`

**Comment by CreativeMD** [comment]
Looks like you forgot to select the branch "1.11".

**Comment by Tsoccerguy3** [comment]
I was suggesting adding build.gradle to the project , so the project can be automatically built from GIT command line . 
example of Run.bat

Git pull
Git checkout 1.11
Gradle build
etc...

I know that these SRG names have changed for 1.11.2 . was just pointing out , it would be helpful to add Gradle support .

For 1.11.2 I did , Git checkout 1.11 , then added gradle to project from , forge-1.11.2-13.20.0.2227-mdk.zip
I set up with Forge 1.11.2 and latest mcp mappings 

These 2 names are wrong for 1.11.2 symbol not found . probably a missing dependency

compileJavaC:\Users\ASUS\Dev\ambsou\build\sources\main\java\com\creativemd\ambientsounds\TickHandler.java:38: error: cannot find symbol
EntityPlayer player = mc.thePlayer;
                                     ^
symbol: variable thePlayer
location: variable mc of type Minecraft
C:\Users\ASUS\Dev\ambsou\build\sources\main\java\com\creativemd\ambientsounds\TickHandler.java:39: error: cannot find symbol
World world = mc.theWorld;
                           ^
symbol: variable theWorld
                            
It just needs 2 changes to support 1.11.2 . Thanks

**Comment by CreativeMD** [comment]
Like i said you selected the wrong branch. I don't want gradle to be added to my repository. It's my source code and not my development workspace.
