### ISSUE TITLE
Sound Engine crashed with 1.13.2

### ISSUE THREAD

**Issue by AManNamed2** [CreativeMD/AmbientSounds#40]
Excuse my poor reporting as this is my first time actually making an issue, sorry in advance! 
While I can use the mod just fine for a good thirty or so minutes, the sound will go out completely & I'll see this in console https://pastebin.com/5PxHXAza

Sometimes upon joining a server it'll crash instantly & reloading via F3-T does bring back base game sound, it doesn't bring back the mods sound.

**Comment by CreativeMD** [comment]
Can you send me the entire log file?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists just reopen this issue here.
