### ISSUE TITLE
Modded Dimensions and Ambient Sounds

### ISSUE THREAD

**Issue by TechnoMysterio** [CreativeMD/AmbientSounds#42]
I've been using Ambient Sounds 3 for a little while now, and I've generally found it to be an excellent way to improve the atmosphere of the game. However, a few dimensions from other mods are getting some unusual or unfitting soundscapes selected for them, so I'll cover a brief list of the dimensions in question:

- Erebus. Cave noises play, which makes sense for an underground world, but there are various forested or forest-like biomes that don't get appropriate insect or other ambient animal noises.
- The Betweenlands. This one has its own custom soundscape built into the mod, so it's strange to have Ambient Sounds 3 play its own ambient audio on top of the ambience already there.
- Twilight Forest. I'm not sure if this is supposed to happen, but this dimension plays ambient rumbling with only a vague hint of birds/insects/other ambient audio, which seems odd for a very forested world, not counting the other biomes that is.
- A currently unreleased Void-like dimension for a mod I'm helping out with. Obviously this couldn't have gotten any custom support since it hasn't been added into the mod yet, but I'm covering it here so that it can be supported in advance. I've created a custom soundscape for this dimension, so maybe just have a low drone for this dimension, similar to the End. The dimension itself is called the Emptiness ("emptiness" is what '/forge dimensions' lists it as), with the default dimension ID being 14676.

It'd be good if you could tweak the Ambient audio for these dimensions so that they fit a little better. If you need any more info on the dimension I'm helping out with, do let me know. Otherwise, keep up the good work!

**Comment by CreativeMD** [comment]
Can you give me the exact names of the dimensions (/forge dimensions) should be just fine for it.

About the twilight forest. That one "should" be fixed. Just recently someone suggested some enhancements (not sure which version you are using, but maybe an update fixes it). If not please let me know.

BTW, you can also change all that stuff yourself (if you want to). There is a file called engine (located in `assets/ambientsounds/sounds/engine.json`). If you know how to work with json files, you might be able to add the dimension yourself. Feel free to ask if you need any help. (if it works you can also send me your changes, so I can add them for everyone). If you don't want to it yourself that's fine too.

**Comment by TechnoMysterio** [comment]
/forge dimensions lists the Emptiness as "emptiness". For the other dimensions I listed, "twilight_forest", "EREBUS" and "betweenlands".

I've also been looking into some other dimension and world-gen related mods to see how well they work with Ambient Sounds. One I tested was Mystcraft, which seems to work pretty well. However, one thing that I noticed was that the dimension I had created was snowing, but rain sounds were playing. The dimension has spawned very high up in the world, so that's probably why there was snow. Another mod I thought about was Serene Seasons (the one that adds... well, seasons), but I haven't had a chance to test how well that works yet.

I might have a look at the json files at some point, I've done some similar stuff with Dynamic Surroundings in the past. I'll let you know if I have any particular queries.

**Comment by CreativeMD** [comment]
Hey ... it's been way too long, sorry for not responding earlier. Finally I got to do it.

Here is a resourcepack, it would be awesome if you could test it:
https://www.dropbox.com/s/s50lvwymfedk5ld/AmbientSounds_testing_new_dimensions.zip?dl=1

**What it does?**
* 'emptiness' should now have the same ambience as 'the end'.
* 'erebus' should have normal biomes sound, but it could be very very strange. This system is designed for overworlds, not sure how it feels in underground.

**Things left to do**
* I added the sounds for 'betweenlands' myself and it was quite okay. Maybe something has changed in the meantime. Should I remove all ambient sounds from that dimension?
* The 'twilight forest' got some fixes. It also a dark dimension, so I didn't want to play the ambient sounds too loud. I can also change it if you want to.

Really hope we can solve all those issues. Again sorry that it took me so long :(

**Comment by TechnoMysterio** [comment]
Gave the pack a test, and I haven't noticed any change. Not sure if it's because the resource pack isn't working properly or something, but I checked the Emptiness and the Twilight Forest and it seemed basically the same as before.

**Comment by CreativeMD** [comment]
Have you checked 'erebus' as well? You can enter `/ambient-debug`, it provides some more information for me to see what is going on (maybe make screenshot of every dimension). BTW I haven't changed anything about the Twilight Forest yet (so maybe make a screenshot of a certain situation, with debug enabled) and tell me what you feel would suit better.

**Comment by CreativeMD** [comment]
I will close this issue now. There will be a way to disable sounds for specific dimensions soon.
