### ISSUE TITLE
Ambient sounds encounters an error during common_setup event phase

### ISSUE THREAD

**Issue by varappdev** [CreativeMD/AmbientSounds#45]
I do not know what happened I am running the latest version of forge here is latest.log:
[latest.log](https://github.com/CreativeMD/AmbientSounds/files/3475554/latest.log)
I hope it helps, because ambient sounds is very nice and i do not want to play without it.

**Comment by CreativeMD** [comment]
The newest version is for 1.14.3, I will update it soon.
