### ISSUE TITLE
AmbientSound not compatible with forge 28.0.45

### ISSUE THREAD

**Issue by Xyphenore** [CreativeMD/AmbientSounds#46]
Forge has changed "net.minecraftforge.fml.common.gameevent.TickEvent" to "net.minecraftforge.event.TickEvent". 
So my question is when AbientSound will be updated for forge 28.0.45.
Because with the last version of forge, we have this error; "java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/gameevent/TickEvent$RenderTickEvent".

**Comment by krwynn** [comment]
Same issue here. Was fine with 28.0.40 but updated to 28.0.45 and it barfed.

**Comment by CreativeMD** [comment]
I will port it soon.
