### ISSUE TITLE
V3.0.10 error "java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getInstance()Lnet/minecraft/client/Minecraft"

### ISSUE THREAD

**Issue by Xyphenore** [CreativeMD/AmbientSounds#48]
The latest version of your mod doesn't work because we get this error : "java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getInstance()Lnet/minecraft/client/Minecraft".
This error was present in an older version. 

But v3.0.9 works very well, without errors, except for infinite and not smooth sound loops. 
So the temporary solution is the downgrade

**Comment by CreativeMD** [comment]
Is fixed in v3.0.11. Sorry for the inconvenience.
