### ISSUE TITLE
Is there a way to turn off crickets?

### ISSUE THREAD

**Issue by HypnoPants** [CreativeMD/AmbientSounds#5]
Maybe not crickets, but the ones that sound like crickets during the day... can we turn off just that, or lower it's frequency of happening or volume, etc?

**Comment by CreativeMD** [comment]
Not at the moment, but i'm currently rewriting it, then you will be able to turn off the crickets.

**Comment by HypnoPants** [comment]
glad to hear it :) my wife was getting headaches from the over-cricketing, but she loves the overall sounds and effects, but keeps turning it off :(

**Comment by HypnoPants** [comment]
also to note, it was grasshoppers and crickets, so the nighttime and daytime versions

**Comment by CreativeMD** [comment]
If you cannot wait you can try out the newest build: https://www.dropbox.com/s/wpyk5fp0ey5s7gm/AmbientSounds%20v2.0.0%20mc1.11.2.zip?dl=1

If you want to change volume of the cricket sound, just look for the engine.json file. Feel free to ask me anything. Ingame configuration will also be added rather soon (once everything else works fine).

**Comment by HypnoPants** [comment]
ah no worries, our minecraft adventures are put on hold, she found a new show and has been bingewatching :P so we've got time before our next adventure

**Comment by CreativeMD** [comment]
Finally finally, the mod is actually done. I will release it in a few days, now it's only about some final testing. Here is the almost release ready version: https://www.dropbox.com/s/wpyk5fp0ey5s7gm/AmbientSounds%20v2.0.0%20mc1.11.2.zip?dl=1

**Comment by HypnoPants** [comment]
I'm impressed, I imagine it was some seriously tough coding for you.

I am grateful to you, and I appreciate all your hard work!
Or I should say 'we' :P Wife says thank you too. heh

**Comment by CreativeMD** [comment]
I'm glad you like it. 2.0.0 has now been officially released! https://www.youtube.com/watch?v=ysB0Q9wLsYM

**Comment by HypnoPants** [comment]
thanks again :) It's amazing, I have the crickets and cicadas down to 0.3, they're no longer annoying but I can still enjoy them with my speakers on (I can turn them up when I use headphones too) but now my wife turns them off entirely and still enjoys all the other lovely sfx! :)

**Comment by CreativeMD** [comment]
I'm really happy to hear that, thanks for all your feedback. Have a nice day.
