### ISSUE TITLE
Bug: when the game is paused suddenly the sounds start

### ISSUE THREAD

**Issue by sepsol** [CreativeMD/AmbientSounds#51]
They stop for a moment, but then they suddenly start. It's weird.

Minecraft 1.14.4
Forge 28.1.0
AmbientSounds 3.0.13

**Comment by CreativeMD** [comment]
That's an issue of the vanilla sound engine. I finally managed to report this issue to mojang. Let's hope it will be fixed soon: https://bugs.mojang.com/browse/MC-164435

**Comment by sepsol** [comment]
Thank you!
