### ISSUE TITLE
Crash while near a underwater dungeon

### ISSUE THREAD

**Issue by zEpiixz** [CreativeMD/AmbientSounds#52]
https://pastebin.com/qxc5v6Tn

**Comment by CreativeMD** [comment]
That is a very weird issue ... no idea how this can happen. Can you download the newest version and see if it happens again?

**Comment by zEpiixz** [comment]
Yes it sadly does. https://pastebin.com/9FRwVssD

**Comment by CreativeMD** [comment]
Can you test this issue with only ambientsounds installed?

**Comment by CreativeMD** [comment]
Still there?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists reopen it.
