### ISSUE TITLE
Compatibility: doesn't work with Better Muffling mod

### ISSUE THREAD

**Issue by sepsol** [CreativeMD/AmbientSounds#53]
When I turn off Ambient/Environment sounds in [Better Muffling ](https://www.curseforge.com/minecraft/mc-mods/better-muffling)block, the [AmbientSounds 3](https://www.curseforge.com/minecraft/mc-mods/ambientsounds) sound effects don't change at all.

Minecraft 1.14.4
Forge 28.1.76

**Comment by CreativeMD** [comment]
This cannot work. AmbientSounds works client side only, so there is no way for the server to mute specific sounds. Furthermore the sounds don't have a position.

I'm sorry, but you will have to live with it.
