### ISSUE TITLE
Is there no config file or am I blind?

### ISSUE THREAD

**Issue by yuhshii** [CreativeMD/AmbientSounds#55]
I would like to turn off the weather ambient sounds because when combined with serene seasons the snow makes a rain sound in winter, in older versions I could have swore there was a config but I dont have one

**Comment by CreativeMD** [comment]
There is no config file for minecraft 1.14/ 1.15. I plan to add it at some point. Don't know when exactly.

**Comment by CreativeMD** [comment]
I will close this issue for now, as it's more of a feature request. Configuration will come eventually.
