### ISSUE TITLE
Problem After Download

### ISSUE THREAD

**Issue by TheBaccsMC** [CreativeMD/AmbientSounds#56]
I'm trying to download a modpack with this mod in it, but it would stop because of this mod. I downloaded it alone and after it was done a popup said "Error: invalid or corrupt jar file" with a directory to the file location.

**Comment by CreativeMD** [comment]
You cannot launch the mod itself, you have to copy it into the mods folder. I would suggest to watch a tutorial about how to install mods in minecraft.
