### ISSUE TITLE
How do I disable crickets in plains biome?

### ISSUE THREAD

**Issue by cozyducking** [CreativeMD/AmbientSounds#58]
I love this mod but the crickets in plains won't stop playing. And as I am building my base there and will spend a lot of time on the plains it is driving me mad after a few days of playing, it seems to be on full loop.

Is there a way to disable it/change it? I love the bird songs in the forested areas and would like use that or something similar in replacement of the crickets.

**Comment by CreativeMD** [comment]
If you are using 1.12 you can change the volume of sounds ingame in the mod options menu.
If you are using 1.15 there is no direct way to change it. You could remove the sound file in the jar or modify the engine. The engine is located in `/assets/ambientsounds/engine.json`, you can even make it a resourcepack. If you need any assistance just ask here (I will close the issue for now).
