### ISSUE TITLE
Sound doesn't loop properly

### ISSUE THREAD

**Issue by Ghoelian** [CreativeMD/AmbientSounds#59]
On version 3.0.20 of the mod, for Minecraft 1.15.2, there seems to be quite a big gap when the loop restarts.

**Comment by Ghoelian** [comment]
I think this might be what #44 is referring to, but I'm not sure since it's worded so poorly.

**Comment by Ghoelian** [comment]
I just checked to see if the audio files loop correctly in Audacity, and they do, so I assume this is either an issue with the way you're streaming audio, or the way Minecraft streams audio.

**Comment by CreativeMD** [comment]
It's an issue of the new sound engine. This issue will be fixed in 1.16: https://bugs.mojang.com/browse/MC-164435.
