### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/AmbientSounds#6]
The commit https://github.com/CreativeMD/AmbientSounds/commit/e37aaf5c4752ffb4de1446aed5b28f2d677c2866 is not in the [CurseForge release](https://minecraft.curseforge.com/projects/ambientsounds/files/2425742) and is resulting in lots of console spam.

( Or at least, I presume the lack of that commit is what is causing this issue )

![](http://i.imgur.com/76Xle4Z.png)

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. I fixed it in 2.0.1.
