### ISSUE TITLE
Ambient Sounds Biome's O' Plenty Compact Audio List

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#60]

**Comment by Tembie3269** [comment]
There's a couple other mods I may leave sounds for in the future. Keep an eye out, ok?

**Comment by CreativeMD** [comment]
Hey there,
quite some time has past ... but I finally got to look at your list.

The main issue here are permissions. I have looked through all of the sounds and most of them forbid any sort of usage. Some don't specify anything, these need to be asked. Some of the sounds cost money, which probably means even if you buy the sound you could still not redistribute it in a mod. To sum it up, I can probably use 3-4 of the ambiences 

Most of these videos are composing different audio files together and that's what ambientsounds does as well. There are serveral sounds for birds, crickets, wind etc.. I think that this is the better approach, saves up lots of stoarge space. So I rather search for high quality sounds which only include one of these things, so I can combine them later again.

I'm not really sure what to do with your list yet. It's definitely a help to get a feel for how this biome should sound like, but I miss many sounds to actually compose most of these.

If you want to help even further search for free sounds with good quality. Sorry this must be very frustrating for you, but I have to respect their ownership.

Down below I wrote a comment to every entry:

The Ominous Woods Biome: no permission
The Mystic Grove Biome: no permission
The Orchard Biome: would have to ask for permission
The Bog Biome: needs to be bought
The Dead Swamp Biome: no permission
The Marsh Biome: would have to ask for permission
The Outback Biome: Day: would have to ask for permission
The Flower Forest Biome: would have to ask for permission
The Lavender Fields Biome: no permission
The Woodland Biome: no permission
The Flower Field Biome: would have to ask for permission, but will most likely cost something as well. Also has a lot of noise in there.
The Cherry Blossom Grove Biome: no permission
The Tropical Rainforest Biome: Day: can be bought for $17, might be a good Investment as it includes lots of sounds, not sure though Night: no permission
The Wasteland Biome: unclear, might be allowed to use it, maybe have to pay a little bit
The Wetland Biome: 
(Make sure The Origin Island/Beach Biome's are all silent as it us supposed to be a throwback to the old Minecraft)
The Moor Biome: no permission
The Meadow Biome: no permission
The Mangrove Biome: same as Flower Field Biome
The Overgrown Cliffs Biome: needs to be bought
The White Beach Biome: no permission
The Volcanic Island Biome: no permission
The Sacred Springs Biome: no permission
The Redwood Forest Biome: would have to ask for permission
The Boreal Forest Biome: Good channel, could ask for permission
The Bamboo Forest Biome: Good channel, could ask for permission
The Cold Desert Biome: Needs to be bought
The Pasture Biome: no permission.
The Snowy Forest Biome: no permission
The Mountain Foothills Biome: would have to ask for permission
The Seasonal Forest Biome: no permission
The Oasis Biome: needs to be bought
The Visceral Heap Biome: needs to be bought
The Phantasmagoric Inferno Biome: needs to be bought
The Undergarden Biome: needs to be bought
The Corrupted Sands Biome: needs to be bought
The Coniferous Forest Biome: would have to ask for permission
The Dead Forest Biome: needs to be bought
The Lush Swamp Biome: needs to be bought
The Praire Biome: no permission

**Comment by CreativeMD** [comment]
I will close this issue for now. Just open a new issue once things are ready.
