### ISSUE TITLE
Sounds still play despite game being paused

### ISSUE THREAD

**Issue by NielsPilgaard** [CreativeMD/AmbientSounds#61]
When I press esc in singleplayer, all sounds/music stops for a while, but then after about 10 seconds I start hearing seagulls. I would've expected all sounds to pause while the game was paused :p

### Versions
- Minecraft 1.15.2
- AmbientSounds_v3.0.20_mc1.15.2

**Comment by CreativeMD** [comment]
This will be fixed in the newest version for 1.16.2 soon.

**Comment by NielsPilgaard** [comment]
Thank you :)

**Comment by NielsPilgaard** [comment]
Any update on this thissue? :)

**Comment by CreativeMD** [comment]
It's finally out. Sorry that it took me so long.

**Comment by NielsPilgaard** [comment]
Thank you, and no worries :)
