### ISSUE TITLE
Game crash on switching dimension 

### ISSUE THREAD

**Issue by rwallac** [CreativeMD/AmbientSounds#64]
Upon using a waystone to travel to the end, my game immediately crashed with this error. 
Using the Valhelsia: Origins modpack

[crash-2020-08-24_23.24.22-client.txt](https://github.com/CreativeMD/AmbientSounds/files/5121217/crash-2020-08-24_23.24.22-client.txt)

**Comment by CreativeMD** [comment]
Sorry, but I don't support 1.15.2 anymore. If you can please move on to 1.16.2. If this crash occurs there as well make sure to report it again.
