### ISSUE TITLE
[1.16.2] Weather sounds while underground.

### ISSUE THREAD

**Issue by TheCoolestPaul** [CreativeMD/AmbientSounds#67]
Probably related to #65 , but while I'm at Y: 11 I can hear rain and storm sounds as if I'm on the surface or in a house.

**Comment by CreativeMD** [comment]
Could not reproduce this one as well, can you use the command /ambient-debug and send me a screenshot of it while it's happening?

**Comment by TheCoolestPaul** [comment]
Here is my [screenshot](https://ibb.co/ySs3XSF). From my minimap mod you can see that I'm at Y:11 and you can still hear the wind and the storming sound.

**Comment by CreativeMD** [comment]
Actually this is not an issue ... these sound should be played, but maybe it is too deep? At what y level should the sound stop?

**Comment by TheCoolestPaul** [comment]
Well, "sea level" is at 63... I'm thinking like 30? Because I know some outside valleys go pretty far. Is there a method to check if you're underground or in a cave? All I know is that at Y:11 I am way too deep to hear outdoor noises 🤷

**Comment by dabluecaboose** [comment]
Was just discussing with a friend and we have this same issue.  Blizzard sound effects are very loud down at y=30 as if you were inside a wood shack.  Would be nice to add a y level to the config that disables weather below it (or is the bottom of a volume curve)

**Comment by CreativeMD** [comment]
Fixed it, the sound can now be heard until 30 blocks below the surface (it will also get fade out starting at 10 blocks below).
