### ISSUE TITLE
[1.16.2] Seagulls endlessly looping on the same sound

### ISSUE THREAD

**Issue by blizzard4591** [CreativeMD/AmbientSounds#68]
Dear CreativeMD,

first off: Thank you for this wonderful mod, the immersion and feeling this brings about is amazing.
I am currently playing on a world where the spawn is located on a small island (Seed: [-2727565724941951195]), and the seagulls are nice at the start, but I had times when seagull1.ogg or seagull4.ogg played continuously for about 10mins+. Is there a way to configure a silence/sound ratio? Or is there maybe a bug in the selection of these sounds?

For debugging, I have attached a screenshot of the ambient-debug command output.
![2020-09-04_23 34 19](https://user-images.githubusercontent.com/130480/92286760-31a69900-ef08-11ea-9432-6a9a97f2f583.png)

**Comment by flumignano** [comment]
This is a problem for me as well. The loud, looping seagull sounds are really annoying!

**Comment by BugmanBugman** [comment]
Getting this as well on 1.16.3

**Comment by CreativeMD** [comment]
It's finally fixed. Sorry that it took me so damn long. :|

**Comment by Demodus** [comment]
Honestly, though this was a feature. Lived on the West Coast for many years and the Gray gulls there were just that annoying.
