### ISSUE TITLE
Bird sounds in different dimensions 

### ISSUE THREAD

**Issue by Aerokuma** [CreativeMD/AmbientSounds#69]
So I wanna play with the mod 'Atum' and this mod offers a portal that teleports you to a different dimension where everything turns into a desert. When I'm in the dimension I can still hear the bird sounds etc from the overworld. is there anyway to turn off the sounds for specific dimensions? 

Thanks.

**Comment by Aerokuma** [comment]
Never mind, I figured how to turn it off, there's an option in the config -> ambientsounds-client.json -> "silent-dimensions". 

If you could make it possible so we can still hear the mountain sounds in 'Aum' just without the cricket/bird sounds etc that would be absolutely amazing but when it's turned off it's fine aswell.

**Comment by CreativeMD** [comment]
Added support for Atum in the newest version. Hope it works just fine now!

**Comment by Aerokuma** [comment]
Bro thank you so much for this very fast update, really appreciate it. Amazing mod honestly. Yes it works out perfectly
