### ISSUE TITLE
[1.12.2] Nether ambience isn't playing.

### ISSUE THREAD

**Issue by Mysteriaa** [CreativeMD/AmbientSounds#70]
I don't know if 1.12.2 is supported for this mod, but I'll shoot my shot. Basically,  Nether ambience won't play no matter what version I use for Minecraft 1.12, except for the occasional ambient sound, but otherwise it's silent. I've looked in config and couldn't solve it through the config files.

**Comment by CreativeMD** [comment]
Can you type in /ambient-debug (in the nether) and send me the screenshot? Furthermore have you changed something in the config?

**Comment by Mysteriaa** [comment]
> 
> 
> Can you type in /ambient-debug (in the nether) and send me the screenshot? Furthermore have you changed something in the config?

Nothing has been altered in the config, it's all the same.
Using the /ambient-debug command doesn't yield any results, either. Nothing shows up in the chat!

**Comment by CreativeMD** [comment]
Are you maybe using an old version?

**Comment by Mysteriaa** [comment]
> 
> 
> Are you maybe using an old version?

I'm using v3.0.12.

**Comment by CreativeMD** [comment]
Update and also make sure to install CreativeCore.

**Comment by Mysteriaa** [comment]
Did as told. Still no Nether ambience, strangely, even upon re-entering the Nether. Is there a possibility that it's been removed by accident or something? Or maybe it's conflicting with Dynamic Surroundings? Idk.

**Comment by CreativeMD** [comment]
Have you changed anything in the configs?

**Comment by Mysteriaa** [comment]
Nope.

**Comment by Mysteriaa** [comment]
Well then. Now I feel like the biggest oaf on the planet.

Turns out I couldn't hear it because I had the ambience slider in sound settings set to "off". But the weird thing is that it only seemed to mute ambience in the Nether specifically, and nowhere else. Huh.

**Comment by CreativeMD** [comment]
That is weird, maybe this ambience was not added by AmbientSounds.
