### ISSUE TITLE
Sounds in improper places

### ISSUE THREAD

**Issue by Mw119** [CreativeMD/AmbientSounds#72]
I'm in the process of releasing a modpack and was tinkering with a resourcepack for AmbientSounds. The one provided on the Curseforge page is called **Overworld only** and is an example for how to create a resourcepack just for the mod. After loading it however, sounds like bird chirping and such stop when you're in an enclosed space. These settings would make much more sense as base settings for the mod! Without this resourcepack there are tons of overworld sounds that are played in enclosed spaces.

I also noticed that while this resourcepack is enabled, it takes away the custom thunderstorm sounds and probably others I'm not noticing. I would prefer to hear all of the cool sounds in this mod!

If nothing else, I would love help with a resourcepack like **Overworld only** that includes all of the sounds available.

**Comment by CreativeMD** [comment]
Actually there is no overworld only resourcepack for AmbientSounds 3. You used a very old resourcepack and obviously things 
don't work properly.  If you are 1.12 you can add silent dimensions in the mod menu config. You can do that in 1.16 as well, but only through the config file.
