### ISSUE TITLE
[1.16.4] Not *really* client-side only

### ISSUE THREAD

**Issue by NielsPilgaard** [CreativeMD/AmbientSounds#73]
Hey o/

Now that Ambient Sounds requires Creative Core, it's not client-side only anymore, would you mind updating the CurseForge page? :)

**Comment by CreativeMD** [comment]
Fixed in the newest version. It will still say in the menu that you cannot join, but it should work now.

**Comment by NielsPilgaard** [comment]
Lovely, thank you :) 
There is a way to override the X when looking at server fyi. Not sure how though :P

**Comment by CreativeMD** [comment]
If you know how just let me know.

**Comment by NielsPilgaard** [comment]
I think this may do the trick: https://github.com/Shadows-of-Fire/PackMenu/blob/master/src/main/java/shadows/menu/PackMenu.java

**Comment by CreativeMD** [comment]
I already use that one and unfortunately that doesn't work in this case.

**Comment by NielsPilgaard** [comment]
Ah my bad ^^'
