### ISSUE TITLE
[1.12.2] Indoors Doesn't Detect Raining?

### ISSUE THREAD

**Issue by Ameranth** [CreativeMD/AmbientSounds#74]
Hello, and thank you for your wonderful work!

I'm working on modifying your sound engine, and while working with rain parameters I've found two oddities/issues:

 1: In the engine .json, several sounds define the property `"rain"` as false, but the correct property for sounds, according to your documentation, is `"raining"`. This was interesting because adding `"rain": "false"` to all sounds of a region did _not_ remove them all during rain, but using `"raining": "false"` did. So it seems that this might be a mistake, because the latter property appears to work as intended.

 2: Moving indoors (tested with a 1 block thick roof/walls) causes the engine to think that it's no longer raining, and therefore outdoor sounds play as if it weren't. Ideally the rain check could handle this case, but I'm unsure how much you can do about it.

Thank you again for your work, and your time!

**Comment by CreativeMD** [comment]
1. You probably mismatched the dimension properties with the sound properties. It is conditions are called `raining` and `storming`.

2. Yes ... I don't think that is a problem, because vanilla has raining sounds and it would be annoying to have these sounds inside a house for example.

**Comment by Ameranth** [comment]
Thank you for your reply!

1. Apologies, I'm saying that the _default_ engine (in 1.12.2) uses `rain` for sound properties, but your documentation defines `rain` as a dimension property and `raining` as the sound property--which in fact the default engine does not properly prevent sounds that it means to, during rain, because of this.

2. I agree with you; the issue is that sounds like crickets and birds, which are prevented while raining (after fixing 1 above), will play while it is raining if you move indoors.

**Comment by CreativeMD** [comment]
Oh damn, probably forgot to change those. It's fixed in the newest update. Thank you very much for telling me!

The sounds are muted by the raining sound, let me know if this is acceptable. If the cricket sound still play I might need to change something about the engine.

**Comment by Ameranth** [comment]
No problem at all, thank you so much for working on it! However, some savannah cicadas and birds still play during rain.

[This engine.json](https://pastebin.com/raw/RkuJCr9k) should cover all of them, if you'd like to use it.

One problem that does still concern me though is that these sounds start to play again if you are indoors while it is raining, which doesn't make much sense. I had planned on editing engine.json to check for `outside`  for these sounds, but was waiting to see if perhaps you had a better solution.

Again, I can't thank you enough for taking the time to look into these! 👍

**Comment by CreativeMD** [comment]
Ok, I applied your changes and I made it if raining is set to false it will check if it is raining in general not if the player is standing in the rain.

Hope that solves the issue. Thank you very much for your help!

**Comment by Ameranth** [comment]
Wonderful work, this is perfect! Thank you!
