### ISSUE TITLE
Better wall detection?

### ISSUE THREAD

**Issue by Inari-Whitebear** [CreativeMD/AmbientSounds#76]
It appears you only check for blocks to be opaque?

Which makes building with slabs or windows hard, since those are detected as basically open space even when they aren't ^^"

Not really sure if there is a good way to detect spaces other than that though, especially ones that are computationally feasible. I guess one idea would be to try and "flood fill" in another thread until it hits a max block count and stops trying, or finds an enclosed space. Then it could store that space for later usage or something, but no clue.

**Comment by CreativeMD** [comment]
This detection is about performance. AmbientSounds should not have a noticeable impact. Furthermore I don't think it's important to be accurate.

I could treat slabs and windows as walls if you think that improves the detection?

**Comment by CreativeMD** [comment]
I will close this issue for now, but I'm still waiting for a reply to my question.

**Comment by Inari-Whitebear** [comment]
Sorry for the late reply. I feel like maybe a config on which blocks are "blocking" may help, then you could set e.g. glass blocks to block sound despite being non-opaque. But just adding them in fixed would help too I suppose. Stairs too if they aren't.

**Comment by CreativeMD** [comment]
It's released now.
