### ISSUE TITLE
The sound linked with `plains.cricket` in config file is uncomfortable

### ISSUE THREAD

**Issue by Mooncat25** [CreativeMD/AmbientSounds#77]
I have to set the value of `plains.cricket` in config file to `0` because the cricket sound playing in the `biomesoplenty:prairie` biome makes me feel uncomfortable. Its sound is high-pitched, continuous and non-stop.

But I searched the sound list in your source files and couldn't find anything like that. So, I'm not sure if it is a bug or a conflict with other mods.

I'm using [Valhelsia](https://www.curseforge.com/minecraft/modpacks/valhelsia-3) 3.1.2 for Minecraft 1.16.4, with the addition of [Sleeping Beds](https://www.curseforge.com/minecraft/mc-mods/sleeping-bags) 1.0.1 and [Tetra](https://www.curseforge.com/minecraft/mc-mods/tetra) updated to 3.5.3.

**Comment by CreativeMD** [comment]
Sound configuration is added in the newest version. You can change it via the mod config or the command /cmdclientconfig
