### ISSUE TITLE
[Request] Sound Engine: "Snowing" Boolean

### ISSUE THREAD

**Issue by Ameranth** [CreativeMD/AmbientSounds#79]
For _engine.json_, a new selector for `snowing=true/false` would be helpful, because currently `raining` is `false` when it snows.

Thank you for your time, I've been having so much fun working with _engine.json_!

**Comment by CreativeMD** [comment]
Added in the newest version of AmbientSounds.

**Comment by Ameranth** [comment]
Thank you so much, I very much look forward to implementing this in my engine.json!
