### ISSUE TITLE
Crashing on Startup with this mod Specifically

### ISSUE THREAD

**Issue by Zodiarkiron** [CreativeMD/AmbientSounds#81]
Sorry if I missed a step but I'm pretty sure I got everything?

Either way here is the Crash log of 1.16.4

https://pastebin.com/271ZwfrS

**Comment by CreativeMD** [comment]
I need the entire log file in order to help you.

**Comment by Zodiarkiron** [comment]
Ah shit. Gotcha. I work today so when I get home I'll make sure to re run
the crash with just the file and will move from there.

As an aside. I'm using forge. It doesn't happen to use fabric in a
Requirement I missed does it?

**Comment by CreativeMD** [comment]
Yes you need forge, it doesn't work with fabric.

**Comment by Kirori07** [comment]
Tengo un servidor 24/7 en The Hosting Minecraft. Tengo varios mods metidos pero cuando agrego el mod de Ambient Sounds el server crashea, y solo me pasa con este mod. ¿Que necesitas que te enseñe para que puedas echarme una mano?

Gracias!

**Comment by CreativeMD** [comment]
Sorry, I don't speak your language @Kirori07

**Comment by Kirori07** [comment]
> Lo siento, no hablo tu idioma @ Kirori07

I have a 24/7 server. On this server I have 14 mods. When I try to put the Ambient Sounds mod, the server crashes. What can I show you to fix it?

**Comment by CreativeMD** [comment]
AmbientSounds should not be installed on a server.

**Comment by Kirori07** [comment]
> AmbientSounds no debe instalarse en un servidor.

If I install it in my client folder, will I be able to enjoy it myself on the server? Thank you!!

**Comment by CreativeMD** [comment]
I will close this issue for now, if it still persist just let me know.
