### ISSUE TITLE
Crashes with Galacticraft Installed

### ISSUE THREAD

**Issue by Starslinger909** [CreativeMD/AmbientSounds#86]
[crash-2021-03-30_19.42.14-client.txt](https://github.com/CreativeMD/AmbientSounds/files/6237350/crash-2021-03-30_19.42.14-client.txt)

**Comment by Starslinger909** [comment]
Do you need any more info I could record a video of it or something @CreativeMD

**Comment by CreativeMD** [comment]
I don't think this issue is related to my mod. It's clearly stating that something goes wrong with Ambience (https://www.curseforge.com/minecraft/mc-mods/ambience-music-mod). Rather ask there for help, sorry that I haven't responded earlier.
