### ISSUE TITLE
Game crashing at startup with Mod installed

### ISSUE THREAD

**Issue by OnMyNightShift** [CreativeMD/AmbientSounds#87]
[crash-2021-04-30_18.28.34-client.txt.zip](https://github.com/CreativeMD/AmbientSounds/files/6409083/crash-2021-04-30_18.28.34-client.txt.zip)

Here is the crash report, it just crashes continuesly on startup
MC 1.12.2

**Comment by CreativeMD** [comment]
Update CreativeCore.
