### ISSUE TITLE
No Suspense sound in dimensions

### ISSUE THREAD

**Issue by Krampus69** [CreativeMD/AmbientSounds#88]
Hello !
The suspense sounds for nether and end are not playing when in those dimensions.
When I use /ambient-debug in the nether, all I get is cave1 ambient sound instead of nether.ogg
In the end, it is wind.ogg instead of end.ogg playing

My config file has both dimensions set to 1
"nether.nether": 1,
    "end.suspense": 1,

I have modded end (Better End, Endergetic Expansion)
But my Nether is not modded. Any advice on how to fix this ?
Thanks !

**Comment by CreativeMD** [comment]
So you have modified the engine or changed any configurations? Can you please provide the necessary information. Not sure what those two example configuration even mean.

**Comment by Krampus69** [comment]
Hi, sorry for answering this late ( crazy work),
I haven't changed the config file but I did open the .jar and changed 2 sound files for testing (nether.ogg / end.ogg)
I know it's not a great way to do it, I'll change sound files with a resource pack from now on.

Anyway, here are the /ambient-debug records I got in both dimensions : 

Modded Nether :
https://user-images.githubusercontent.com/81943963/118027932-c51b4e00-b362-11eb-997c-3e92b3d26d95.png

Modded End :
https://user-images.githubusercontent.com/81943963/118027994-da907800-b362-11eb-8a45-eb8f0d4443c5.png


Okay so I've been doing some testing on my side. 
I've disabled every single mod but Ambient Sounds (and CreativeCore of course) and I deleted the config file to make sure a new one is loaded when playing.

Vanilla Nether : 
https://user-images.githubusercontent.com/81943963/118028546-7c17c980-b363-11eb-94ca-581329743392.png

Vanilla End : 
https://user-images.githubusercontent.com/81943963/118028593-8afe7c00-b363-11eb-84c1-e5962c4c60da.png

As you can see, even with no mods and a clean save/config file, those dimensions are not playing their suspense sounds. The End dimension is not playing anything but a wind.ogg from time to time. The nether actually plays a suspense sound, but it's the one from Overworld caves (I think it's caves1.ogg and caves2.ogg)

I'm running out of ideas, even while reading the config file everything seems normal.

_I'm on Minecraft 1.16.5 (Forge 36.1.4)
I use : 
- AmbientSounds_v3.1.6_mc1.16.5
- CreativeCore_v2.1.0_mc1.16.5_

This feature used to work on 1.12 and I already tweaked it to create custom dimensions ambience for my servers but now I'm working on a big modpack with a team of devs and I'd like to understand why this ain't working on my side.
Could you please help me out and check on your side if these dimensions are playing the correct .ogg ?

Thank you very much for your help, I appreciate it 🙏

**Comment by CreativeMD** [comment]
Sorry that it took me soo long to respond. AmbientSounds was not detecting the dimension properly. It's fixed in the newest version!
