### ISSUE TITLE
[Issue] Ambient sounds in twilight forest are only present in swamp type biomes from the mod, but only at y level 61 or higher

### ISSUE THREAD

**Issue by Corvus20** [CreativeMD/AmbientSounds#90]
I wish I was joking. I tested multiple biomes, all the forest, taiga, etc. variants from twilight forest, and at their surface level (which seems to be, on average, somewhere between y 32 and y36), the only ambience is wind blowing. Interestingly, swamp biomes from that mod (such as the swamp and fire swamp), have swamp ambience play, but only at altitudes of 61 or higher. Going to this altitude in the other biomes does not yield the same effect. This could be a case of lacking proper biome tags, or it could be something else entirely.

**Comment by CreativeMD** [comment]
Which version of the mod are you using? Also can you use the command /ambient-debug and send me a few screenshots so I can get more information?

**Comment by Corvus20** [comment]
I am using ambient sounds version 3.1.8 for 1.16.5. Twilight forest is 4.0.467 for 1.16.5.

Screenshots:
![2021-05-29_15 42 57](https://user-images.githubusercontent.com/75586106/120083219-1df22280-c095-11eb-9031-5c14ece559af.png)
![2021-05-29_15 43 22](https://user-images.githubusercontent.com/75586106/120083220-1df22280-c095-11eb-933f-b0ab54988357.png)
![2021-05-29_15 44 13](https://user-images.githubusercontent.com/75586106/120083221-1e8ab900-c095-11eb-9b39-bcca7773346d.png)
![2021-05-29_15 44 23](https://user-images.githubusercontent.com/75586106/120083222-1f234f80-c095-11eb-92a6-847a2781ee6d.png)
![2021-05-29_15 44 41](https://user-images.githubusercontent.com/75586106/120083224-1f234f80-c095-11eb-860b-c40819bdd1e8.png)

The complete absence of ambience make me wonder if it is something to do with their ground level being lower than vanilla, or their biomes perhaps not being tagged correctly. I cannot say for certain.

**Comment by CreativeMD** [comment]
The twilightforest dimension was not working properly, that has been fixed in the newest version, but that won't fix the issue you have. Because you are just way too high up to hear the biome sounds. You need to be near the surface in order to hear that.
