### ISSUE TITLE
Nether Sounds in the Overworld

### ISSUE THREAD

**Issue by Matthysse** [CreativeMD/AmbientSounds#91]
Hello!

Since the last update, I have in every biome from the overworld Nether ambiant sounds, which sounds really creepy.
I tried removing the mod and it indeed stops these ambiant sounds.

Here is my list of mods:
https://pastebin.com/2frpPRbR

**Comment by CreativeMD** [comment]
Can you use the command /ambient-debug and send me a screenshot of it during it issue?

**Comment by Matthysse** [comment]
Yep, here it is:

![2021-06-02_14 19 16](https://user-images.githubusercontent.com/32510957/120478864-99ade100-c3ad-11eb-9551-d00be24bb0bc.png)

**Comment by CreativeMD** [comment]
Any resourcepack installed which could change AmbientSounds?

**Comment by Matthysse** [comment]
Yes I have a ressource pack but it doesn't change the base ambiant sounds and only adds a few more, I used the default sounds.json and engine.json and only added the sounds I wanted.

**Comment by CreativeMD** [comment]
That is the problem, changes have been made to the engine so you should include these as well.
