### ISSUE TITLE
No Cave Noise (1.17.1)

### ISSUE THREAD

**Issue by ethanray77** [CreativeMD/AmbientSounds#92]
Hello. Everything seems to work fine, however, no ambient noise is played in the caves. I don't have any mods or resource packs that edit sound. I have attached the debug screenshot too.

![2021-08-18_23 19 34](https://user-images.githubusercontent.com/48543234/130007288-9adb6ca5-bdf2-4803-b380-4947094dbe60.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue with all the necessary info!
