### ISSUE TITLE
Crash on client.

### ISSUE THREAD

**Issue by Sunekaer** [CreativeMD/AmbientSounds#93]
Crash log: https://paste.feed-the-beast.com/view/3079df34
Forge:36.2.4
AmbientSounds_v3.1.9_mc1.16.5

**Comment by CreativeMD** [comment]
This issue has been reported several times and I have no idea how this occur. Try to reinstall the mod? Just make sure to get the mod from curseforge. Could never reproduce it on my own.

**Comment by CreativeMD** [comment]
Will close this issue for now. No idea if it's still there.
