### ISSUE TITLE
No ambience soundtracks playing in caves.

### ISSUE THREAD

**Issue by MrReality02** [CreativeMD/AmbientSounds#94]
There's simply no ambience in the caves. 
![2021-10-06_22 15 04](https://user-images.githubusercontent.com/92058410/136277912-fb7f4159-12f6-459b-9027-75eae676482e.png)

**Comment by CreativeMD** [comment]
Thanks a lot. Could figure out the issue. It's fixed in the newest version!

**Comment by MrReality02** [comment]
You are the best, thanks for the quick fix! It's working flawlessly now.
