### ISSUE TITLE
[1.12] Acidic Plains biome from Stygian End plays overworld ambience and there is no way to disable it only for the End

### ISSUE THREAD

**Issue by Roadhog360** [CreativeMD/AmbientSounds#95]

**Comment by CreativeMD** [comment]
Can you go into that dimension, type in /ambient-debug and send me a screenshot of it?

**Comment by Roadhog360** [comment]
It might happen because you check for the name "plains" in a biome and forget to look for a dimension. Maybe a new option similar to making the whole dimension silent, where you put in a biome name to have no ambience or different ambience for compatibility reasons?

Acidic Plains debug:
![image](https://user-images.githubusercontent.com/11903511/137536848-3d263ea5-56bb-4b6c-9b49-b65d0a761242.png)

Debug in the default biome as a control:
![image](https://user-images.githubusercontent.com/11903511/137536926-b2efed92-145d-4996-89e7-46fd2611e156.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue and helping out with screenshots!
