### ISSUE TITLE
Custom Sea levels not supported

### ISSUE THREAD

**Issue by 1eo1i** [CreativeMD/AmbientSounds#96]
Hi, I have a custom map which has a sea level of 22. Many sounds are not playing. (e.g. sea and beach sounds.) According to the debug, it doesn't detect that I am in the 'ocean' region. 
I'm guessing I need to edit the engine.json, but I don't know how. Could you make a tutorial on how to create a custom configuration?

Your help is much appreciated!

![2021-10-23_23 25 24](https://user-images.githubusercontent.com/61970761/138552454-1f3fd2cd-8275-4ac1-ad16-7e16b57159c6.png)

**Comment by CreativeMD** [comment]
In theory the engine scans the environment using relative height, so there should be no difference. Maybe it ignores water. Which version of the mod and which minecraft version are you using?

**Comment by 1eo1i** [comment]
I am playing in 1.16.5, using v3.1.9_mc1.16.5

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. There was an issue with the height calculations. Thanks for reporting this issue!

**Comment by 1eo1i** [comment]
Thanks so much!

**Comment by CreativeMD** [comment]
The newest version will take a few more minutes until it's approved.
