### ISSUE TITLE
Sound passes through stairs, slabs, glass panes etc.

### ISSUE THREAD

**Issue by 1eo1i** [CreativeMD/AmbientSounds#98]
Hi, could you please update the following blocks to block sounds? 

- Stairs
- Slabs
- Glass Panes
- Walls (Cobblestone wall etc.)
- Trapdoors

And possibly more. Personally, I think to improve wall detection, any block that fills an area of 1/2 or more of a normal block should block sound. I would rather they fully blocked sound like a normal block (even if ideally they should only partially block sound) than have sound completely pass through them.

Versions tested:
AmbientSounds_v3.1.10_mc1.16.5
AmbientSounds_v4.0.3_mc1.17.1

**Comment by CreativeMD** [comment]
AmbientSounds does not have a "blocking" feature sound. Actually AmbientSounds does not change anything about sound behavior. So I have no idea what you mean, maybe you are talking about a different mod?

**Comment by 1eo1i** [comment]
Sorry if I wasn't very clear. I was pretty much referring to this previous post. It seems you have resolved the sound passing through glass issue but not the stairs and other blocks. https://github.com/CreativeMD/AmbientSounds/issues/76

**Comment by CreativeMD** [comment]
As stated in the linked issue, ambientsounds does not try to be accurate. It's about saving performance while providing an immersive ambience.

**Comment by 1eo1i** [comment]
You said 'I could treat slabs and windows as walls if you think that improves the detection?'
So this means they could be changed?
I'm simply asking if you could change those blocks listed in my first post to behave like any other normal block.

**Comment by CreativeMD** [comment]
If the blocks are not considered full blocks they will be ignored. I don't want to add exclusions to this, it's extra work and wouldn't work with modded blocks anyway.

For 1.18 ambientsounds has to change a bit more than usual. So I might rework some of that stuff then. But can't promise anything.

**Comment by 1eo1i** [comment]
Ok, no problem! Thanks for your help anyway, I really like this mod! It truly adds a lot to the game.

**Comment by CreativeMD** [comment]
Sorry if I sounded a bit harsh. I'm just a single person. I cannot do everything and these details usually get ignored for other things. Hope you can understand that.

If you are interested in these kind of things consider starting modding. It's not that difficult and ambientsounds could need a lot of improvements.

**Comment by 1eo1i** [comment]
All good, I totally understand! It's honestly amazing how much you have achieved already. Yeah, thanks for the suggestion, I may give modding a try in the future.
