### ISSUE TITLE
Crash 1.16.5

### ISSUE THREAD

**Issue by senorpllave** [CreativeMD/AmbientSounds#99]
[crash-2021-11-02_15.16.08-client-1.txt](https://github.com/CreativeMD/AmbientSounds/files/7464262/crash-2021-11-02_15.16.08-client-1.txt)

How it happened: you die and server crashes (before you respawn)  and when server restarts and you join, the game crashes & you can't play / you can't spawn(for a second you appear dead and it crashes) and log says ambient sounds (not sure if it's because of that mod tho, there are like 380 mods in the pack)

**Comment by CreativeMD** [comment]
This mod only works on client side. You cannot install it on a server.
